language: node_js
sudo: false
node_js:
  - "node"
script: "npm run travis"
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
notifications:
  slack: basisjs:1P6GlAfiFonogcgzU2ROlXDt
