/*!
 * Basis javasript library 
 * http://code.google.com/p/basis-js/
 *
 * @license
 * GNU General Public License v2.0 <http://www.gnu.org/licenses/gpl-2.0.html>
 */

(function(l){function q(a,b){for(var c in b)a[c]=b[c];return a}function v(a,b){for(var c in b)c in a==false&&(a[c]=b[c]);return a}function A(a){return a==null||a==void 0}function u(a){return a}function B(a){var b={};a.names=function(a){return Object.slice(b,typeof a=="string"?a.qw():a)};a.extend=function(a){v(b,a);q(this,a);return this};return a}function y(a,b){for(var c=a.split("."),d=l,f,h,k;c.length;)if(f=c.shift(),h=(h?h+".":"")+f,d[f]||(d[f]=B((!c.length?b:null)||function(){},h),k&&(k.namespaces_[h]=
d[f])),d=d[f],!k&&(k=d,!k.namespaces_))k.namespaces_={};return n[a]=d}q(Object,{extend:q,complete:v,keys:function(a){var b=[],c;for(c in a)b.push(c);return b},values:function(a){var b=[],c;for(c in a)b.push(a[c]);return b},slice:function(a,b){var c={};if(!b)return q(c,a);for(var d=0,f;f=b[d++];)f in a&&(c[f]=a[f]);return c},splice:function(a,b){var c={};if(!b)return q(c,a);for(var d=0,f;f=b[d++];)f in a&&(c[f]=a[f],delete a[f]);return c},iterate:function(a,b,c){var d=[],f;for(f in a)d.push(b.call(c,
f,a[f]));return d},coalesce:function(){for(var a=arguments,b=0;b<a.length;b++)if(a[b]!=null)return a[b]}});var o=function(){},t=function(){var a=1,b={},c={};a++;return function(d,f){var h,k;if(!f){if(d.getter)return d.getter;if(typeof d=="function")return d}if(typeof d!="function")c[d]?h=c[d]:(h=new Function("object","return object != null ? object."+d+" : object"),h.path=d,h.getterIdx_=a++,c[d]=h);else if(h=d,!h.getterIdx_)h.getterIdx_=a++;k=h.getterIdx_;var j=b[k];if(j)if(typeof f=="undefined"){if(j.nmg)return j.nmg}else for(k=
0;k<j.length;k++){if(j[k].modificator===f)return j[k].getter}else j=b[k]=[];var p=true;switch(f&&typeof f){case "string":k=function(a){return f.format(h(a))};break;case "function":k=function(a){return f(h(a))};break;case "object":p=false;k=function(a){return f[h(a)]};break;default:k=h.path?h:function(a){return h(a)}}if(p&&(j.push({getter:k,modificator:f}),typeof f=="undefined"))j.nmg=k;return k.getter=k}}();q(Function,{$undefined:function(a){return a==void 0},$defined:function(a){return a!=void 0},
$isNull:A,$isNotNull:function(a){return a!=null&&a!=void 0},$isSame:function(a){return a===this},$isNotSame:function(a){return a!==this},$self:u,$const:function(a){return function(){return a}},$false:function(){return false},$true:function(){return true},$null:function(){return null},$undef:o,getter:t,def:function(a,b,c){c=c||A;return function(d){d=a(d);return c(d)?b:d}},wrapper:function(a){return function(b){var c={};c[a]=b;return c}},lazyInit:function(a,b){var c=0,d;return function(){c++||(d=a.apply(b||
this,arguments));return d}},lazyInitAndRun:function(a,b,c){var d=0,f;return function(){d++||(f=a.call(c||this));b.apply(f,arguments);return f}},runOnce:function(a,b){var c=0;return function(){if(!c++)return a.apply(b||this,arguments)}}});v(Function.prototype,{bind:function(a){var b=this,c=Array.from(arguments,1);return c.length?function(){return b.apply(a,c.concat.apply(c,arguments))}:function(){return b.apply(a,arguments)}}});v(Array,{isArray:function(a){return Object.prototype.toString.call(a)===
"[object Array]"}});q(Array,{from:function(a,b){if(a!=null){var c=a.length;if(typeof c=="undefined")return[a];b||(b=0);if(c-b>0){for(var d=[],f=0,h=b;h<c;)d[f++]=a[h++];return d}}return[]},create:function(a,b,c){for(var d=[],f=typeof b=="function",h=0;h<a;h++)d[h]=f?b.call(c,h,d):b;return d}});v(Array.prototype,{indexOf:function(a,b){b=parseInt(b)||0;if(b<0)return-1;for(;b<this.length;b++)if(this[b]===a)return b;return-1},lastIndexOf:function(a,b){for(var c=this.length,b=parseInt(b),b=isNaN(b)||b>=
c?c-1:(b+c)%c;b>=0;b--)if(this[b]===a)return b;return-1},forEach:function(a,b){for(var c=0,d=this.length;c<d;c++)c in this&&a.call(b,this[c],c,this)},every:function(a,b){for(var c=0,d=this.length;c<d;c++)if(c in this&&!a.call(b,this[c],c,this))return false;return true},some:function(a,b){for(var c=0,d=this.length;c<d;c++)if(c in this&&a.call(b,this[c],c,this))return true;return false},filter:function(a,b){for(var c=[],d=0,f=this.length;d<f;d++)d in this&&a.call(b,this[d],d,this)&&c.push(this[d]);
return c},map:function(a,b){for(var c=[],d=0,f=this.length;d<f;d++)d in this&&(c[d]=a.call(b,this[d],d,this));return c},reduce:function(a,b){var c=this.length,d=arguments.length;if(c==0&&d==1)throw new TypeError;var f,h=0;d>1&&(f=b,h=1);for(d=0;d<c;d++)d in this&&(f=h++?a.call(null,f,this[d],d,this):this[d]);return f}});q(Array.prototype,{flatten:function(){return this.concat.apply([],this)},repeat:function(a){return Array.create(parseInt(a)||0,this).flatten()},item:function(a){a=parseInt(a||0);return this[a>=
0?a:this.length+a]},search:function(a,b,c){Array.lastSearchIndex=-1;for(var b=Function.getter(b||u),c=parseInt(c)||0,d=this.length;c<d;c++)if(b(this[c])===a)return this[Array.lastSearchIndex=c]},lastSearch:function(a,b,c){Array.lastSearchIndex=-1;for(var b=Function.getter(b||u),d=this.length,c=isNaN(c)||c==null?d:parseInt(c),d=c>d?d:c;d-- >0;)if(b(this[d])===a)return this[Array.lastSearchIndex=d]},binarySearchPos:function(a,b,c,d,f,h){if(!this.length)return d?-1:0;var b=Function.getter(b||u),c=!!c,
k,f=isNaN(f)?0:f,j=isNaN(h)?this.length-1:h;do if(h=f+j>>1,k=b(this[h]),c?a>k:a<k)j=h-1;else if(c?a<k:a>k)f=h+1;else return a==k?h:d?-1:0;while(f<=j);return d?-1:h+(k<a^c)},binarySearch:function(a,b){return this.binarySearchPos(a,b,false,true)},add:function(a){return this.indexOf(a)==-1&&!!this.push(a)},remove:function(a){a=this.indexOf(a);return a!=-1&&!!this.splice(a,1)},has:function(a){return this.indexOf(a)!=-1},merge:function(a){return this.reduce(q,a||{})},sortAsObject:function(a,b,c){a=Function.getter(a);
c=c?-1:1;return this.map(function(b,c){return{i:c,v:a(b)}}).sort(b||function(a,b){return c*(a.v>b.v||-(a.v<b.v)||(a.i>b.i?1:-1))}).map(function(a){return this[a.i]},this)},set:function(a){if(this!==a)this.length=0,this.push.apply(this,a);return this},clear:function(){this.length=0;return this}});if(![1,2].splice(1).length){var x=Array.prototype.splice;Array.prototype.splice=function(){var a=Array.from(arguments);if(a.length<2)a[1]=this.length;return x.apply(this,a)}}var i={"<":">","[":"]","(":")",
"{":"}","\u00ab":"\u00bb"};String.Entity={laquo:"\u00ab",raquo:"\u00bb",nbsp:"\u00a0",quot:'"',quote:'"',copy:"\u00a9",shy:"\u00ad",para:"\u00b6",sect:"\u00a7",deg:"\u00b0",mdash:"\u2014",hellip:"\u2026"};v(String,{toLowerCase:function(a){return String(a).toLowerCase()},toUpperCase:function(a){return String(a).toUpperCase()},trim:function(a){return String(a).trim()},trimLeft:function(a){return String(a).trimLeft()},trimRight:function(a){return String(a).trimRight()},isEmpty:function(a){return a==
null||String(a)==""},isNotEmpty:function(a){return a!=null&&String(a)!=""}});v(String.prototype,{trimLeft:function(){return this.replace(/^\s+/,"")},trimRight:function(){return this.replace(/\s+$/,"")},trim:function(){return this.trimLeft().trimRight()}});q(String.prototype,{toObject:function(a){try{return Function("return 0,"+this)()}catch(b){if(a)throw b;}},toArray:(new String("a"))[0]?function(){return Array.from(this)}:function(){for(var a=[],b=this.length,c=0;c<b;c++)a[c]=this.charAt(c);return a},
repeat:function(a){return Array(parseInt(a)+1||0).join(this)},qw:function(){var a=this.trim();return a?a.split(/\s+/):[]},forRegExp:function(){return this.replace(/[\/\\\(\)\[\]\?\{\}\|\*\+\-\.\^\$]/g,"\\$&")},format:function(a){for(var b={},c=0;c<arguments.length;c++)b[c]=arguments[c];typeof a=="object"&&q(b,a);return this.replace(/\{([a-z\d\_]+)(?::([\.0])(\d+)|:(\?))?\}/gi,function(a,c,h,k,j){a=c in b?b[c]:j?"":a;return h&&!isNaN(a)?(a=Number(a),h=="."?a.toFixed(k):a.lead(k)):a})},quote:function(a,
b){var a=a||'"',b=b||i[a]||a,c=(a.length==1?a:"")+(b.length==1?b:"");return a+(c?this.replace(RegExp("["+c.forRegExp()+"]","g"),"\\$&"):this)+b},capitalize:function(){return this.charAt(0).toUpperCase()+this.substr(1).toLowerCase()},camelize:function(){return this.replace(/-(.)/g,function(a,b){return b.toUpperCase()})},dasherize:function(){return this.replace(/[A-Z]/g,function(a){return"-"+a.toLowerCase()})}});String.format=String.prototype.format;if("|||".split(/\|/).length+"|||".split(/(\|)/).length!=
11)String.prototype.split=function(a){if(a==""||a&&a.source=="")return this.toArray();var b=[],c=0,d;if(a instanceof RegExp)for(a.global||(a=RegExp(a.source,/\/([mi]*)$/.exec(a)[1]+"g"));d=a.exec(this);)d[0]=this.substring(c,d.index),b.push.apply(b,d),c=a.lastIndex;else for(;(d=this.indexOf(a,c))!=-1;)b.push(this.substring(c,d)),c=d+a.length;b.push(this.substr(c));return b};if("12".substr(-1)!="2"){var r=String.prototype.substr;String.prototype.substr=function(a,b){return r.call(this,a<0?Math.max(0,
this.length+a):a,b)}}q(Number.prototype,{fit:function(a,b){return!isNaN(a)&&this<a?Number(a):!isNaN(b)&&this>b?Number(b):this},between:function(a,b){return!isNaN(this)&&this>=a&&this<=b},quote:function(a,b){return(this+"").quote(a,b)},toHex:function(){return parseInt(this).toString(16).toUpperCase()},sign:function(){return this<0?-1:+(this>0)},base:function(a){return!a||isNaN(a)?0:Math.floor(this/a)*a},lead:function(a,b){return(this+"").replace(/\d+/,function(c){return(a-=c.length-1)>1?Array(a).join(b||
0)+c:c})},group:function(a,b){return(this+"").replace(/\d+/,function(c){return c.replace(/\d/g,function(d,f){return!f+(c.length-f)%(a||3)?d:(b||" ")+d})})},format:function(a,b,c,d,f){a=this.toFixed(a);if(b||f)a=a.replace(/(\d+)(\.?)/,function(a,c,d){return(b?Number(c).group(3,b):c)+(d?f||d:"")});c&&(a=a.replace(/^-?/,"$&"+(c||"")));return a+(d||"")}});v(Date,{now:function(){return+new Date}});(new Date).getYear()<1900&&q(Date.prototype,{getYear:function(){return this.getFullYear()-1900},setYear:function(a){return this.setFullYear(!isNaN(a)&&
a<100?Number(a)+1900:a)}});var n={},z=function(){function a(a,b){for(var c=n[a],d=b?b.split(/\./):[];c&&d.length;)c=c[d.shift()];return c}var b=l.document?l.document.getElementsByTagName("SCRIPT"):null,c=(b?b[b.length-1].src:module.filename).replace(/[^\/]+$/,""),d={},f;typeof require=="function"?f=function(a){return require(requirePath+a.replace(/\./g,"/"))}:(f=function(b,k){var j=b.match(/^([a-z][a-zA-Z0-9\_]*(\.[a-z][a-zA-Z0-9\_]*)*)?/)[0],p=b.substr(j.length?j.length+1:0),D=a(j,p),g=/^basis\./.test(j)?
c:(location?location.href:"").replace(/[a-z0-9\-\_\.]+\.[a-z0-9]+$/,"");if(!n[j]||!D)if(/^https?:/.test(g))if(d[b])throw"Attempt to load namespace, probably cycle require";else{d[b]=1;var g=g+(k||"")+b.replace(/\./g,"/")+".js",e=new XMLHttpRequest;e.open("POST",g,false);e.send(null);if(e.status==200){try{(new Function(e.responseText)).call(l)}catch(i){throw i;}f.sequence.push(b.replace(/\./g,"/")+".js")}else if(e.status==404&&p)z(j);else throw"!";}else throw"Path `"+b+"` can't be resolved";return D||
a(j,p)},f.sequence=[]);return f}(),w=function(){function a(a){return typeof a=="function"&&a.basisClass_}var b=Function(),c=1,d={},f=function(){for(var a in{toString:1})return;return true}();q(b,{className:"basis.Class",extendConstructor_:false,prototype:{constructor:null,init:Function(),toString:function(){return"[object "+(this.constructor||this).className+"]"},destroy:function(){for(var a in this)this[a]=null;this.destroy=o}},create:function(f){typeof f!="function"&&(f=b);var p=Function();p.prototype=
f.prototype;for(var p=new p,h={className:f.className+"._SubClass_",basisClass_:true,superClass_:f,extendConstructor_:!!f.extendConstructor_,__extend__:function(c){return c&&(typeof c=="object"||typeof c=="function"&&!a(c))&&c!==d?b.create.call(null,m,c):c},extend:b.extend,subclass:function(){return b.create.apply(null,[m].concat(Array.from(arguments)))},prototype:p},k=arguments,g=1;g<k.length;g++)h.extend(typeof k[g]=="function"&&!a(k[g])?k[g](f.prototype):k[g]);var e={},m=h.extendConstructor_?function(a,
b){this.eventObjectId=c++;var m,d;for(d in a)m=this[d],this[d]=m&&m.__extend__?m.__extend__(a[d]):a[d];this.init(b||e)}:function(){this.eventObjectId=c++;this.init.apply(this,arguments)};p.constructor=m;for(var F in p)p[F]===d&&(p[F]=m);q(m,h);return m},extend:function(a){var b=this.prototype;if(a.prototype)a=a.prototype;for(var c in a){var d=a[c],h=b[c];c=="className"||c=="extendConstructor_"?this[c]=d:b[c]=h&&h.__extend__?h.__extend__(d):d}if(f&&a[c="toString"]!==Object.prototype[c])b[c]=a[c];return this}});
var h=function(a,b){return{__extend__:function(a){var c=Function();c.prototype=this;c=new c;b(c,a);return c}}.__extend__(a)},k=function(a){return h(a,q)};return y("basis.Class",b.create).extend({SELF:d,BaseClass:b,create:b.create,isClass:a,CustomExtendProperty:h,ExtensibleProperty:k,NestedExtProperty:function(a){return h(a,function(a,b){for(var c in b){var d=a[c];a[c]=d&&d.__extend__?d.__extend__(b[c]):k(b[c])}})}})}(),s=function(){function a(a){var d=c[a];d||(d=c[a]=function(){var c=this.handlers_,
d,f;if(c&&c.length)for(var c=b.call(c),k=c.length;k-- >0;)d=c[k],f=d.handler[a],typeof f=="function"&&f.apply(d.thisObject,arguments)});return d}var b=Array.prototype.slice,c={},d,f=w(null,{handlers_:null,event_destroy:d=a("destroy","object"),listen:w.NestedExtProperty(),extendConstructor_:true,init:function(){if(this.handler)(this.handlers_||(this.handlers_=[])).push({handler:this.handler,thisObject:this.handlerContext||this})},addHandler:function(a,b){var c=this.handlers_;if(!c)c=this.handlers_=
[];b||(b=this);for(var d=c.length,f;d-- >0;)if(f=c[d],f.handler===a&&f.thisObject===b)return false;return!!c.push({handler:a,thisObject:b||this})},removeHandler:function(a,b){var c=this.handlers_;if(c){b||(b=this);for(var d=c.length,f;d-- >0;)if(f=c[d],f.handler===a&&f.thisObject===b)return!!c.splice(d,1);return false}},destroy:function(){if(this.handlers_)d.call(this,this),this.handlers_=null}});f.createEvent=a;f.event=c;return f}(),g=function(){var a=[];return{add:function(b){b!=null&&a.push(b)},
remove:function(b){a.remove(b)}}}();(function(){function a(a){if(b){if(a.source!=l||a.data!=c)return;basis.dom.event.kill(a)}d.length&&(a=d.shift(),delete f[a.key],a.fn())}var b=typeof addEventListener=="function"&&typeof postMessage=="function",c="zeroTimeoutMessage",d=[],f={},h=1;b&&l.addEventListener("message",a,true);var g=setTimeout;l.setTimeout=function(p,e){var j;e?j=g.call(l,p,e):(j={key:"z"+h++,fn:typeof p=="function"?p:new Function(p)},f[j.key]=j,d.push(j),b?postMessage(c,"*"):j.timer=g.call(l,
a,0),j=j.key);return j};var e=clearTimeout;l.clearTimeout=function(a){if(/z\d+/.test(a)){var b=f[a];b&&(clearTimeout(b.timer),d.remove(b),delete f[a])}else return e.call(l,a)}})();var e=function(){function a(){if(!D)if(h.length){var a=Date.now(),b=Math.max(h[0].eventTime,a);b<j&&(clearTimeout(p),p=setTimeout(c,(j=b)-a))}else p=clearTimeout(p),j=d}function b(b,c){var d=b.eventObjectId,m=e[c]&&e[c][d];m&&(h.remove(m),delete e[c][d],a())}function c(){var b=Date.now(),b=h.binarySearchPos(b+15,f);D=true;
h.splice(0,b).forEach(function(a){delete e[a.eventName][a.object.eventObjectId];a.callback.call(a.object)});D=false;j=d;a()}var d=2E12,f=t("eventTime"),h=[],e={},j=d,p=null,D=false;g.add({destroy:function(){D=true;clearTimeout(p);h.length=0;e=null}});return{add:function(c,d,p){var m=c.eventObjectId,F=e[d];F||(F=e[d]={});var C=F[m];if(C){if(isNaN(p))return b(c,d);if(C.eventTime==p)return;h.remove(C);C.eventTime=p}else{if(isNaN(p))return;C=F[m]={eventName:d,object:c,eventTime:p,callback:c[d]}}h.splice(h.binarySearchPos(p,
f),0,C);a()},remove:b}}();y("basis").extend({namespace:y,platformFeature:{},EventObject:s,TimeEventManager:e,Cleaner:g,require:z});l.basis.locale={}})(this);
(function(l,q){function v(i){for(var g=1E6,i=String(i).split("."),e=0,a=0;e<4&&e<i.length;e++,g/=100)a+=i[e]*g;return a}function A(){for(var i=0;i<arguments.length;i++){var g=arguments[i].toLowerCase();if(g in B){if(B[g])return true}else{var e=g.match(/^([a-z]+)(([\d\.]+)([+-=]?))?$/i);if(e){B[g]=false;var a=e[1].toLowerCase(),b=v(e[3]),e=e[4]||"=";if(a=y[a])return B[g]=!b||e=="="&&a==b||e=="+"&&a>=b||e=="-"&&a<b}}}return false}var u="basis.ua",B={},y={},o=q.navigator&&q.navigator.userAgent,t="unknown",
x={MSIE:["Internet Explorer","msie","ie"],Gecko:["Gecko","gecko"],Safari:["Safari","safari"],"iPhone OS":["iPhone","iphone"],AdobeAir:["AdobeAir","air"],AppleWebKit:["WebKit"],Chrome:["Chrome","chrome"],FireFox:["FireFox","firefox","ff"],Iceweasel:["FireFox","firefox","ff"],Shiretoko:["FireFox","firefox","ff"],Opera:["Opera","opera"]},i;for(i in x)if(!(i=="MSIE"&&q.opera)&&!(i=="Safari"&&o.match(/chrome/i))&&!(i=="AppleWebKit"&&o.match(/iphone/i))&&o.match(RegExp(i+".(\\d+(\\.\\d+)*)","i")))for(var r=
x[i],n=q.opera&&typeof q.opera.version=="function"?q.opera.version():RegExp.$1,z=v(n),t=r[0]+" "+n,n=0;n<r.length;n++)y[r[n].toLowerCase()]=z;l.platformFeature.datauri=false;o=typeof Image!="undefined"?new Image:{};o.onload=function(){l.platformFeature.datauri=true};o.src="data:image/gif;base64,R0lGODlhAQABAIAAAP///wAAACH5BAEAAAAALAAAAAABAAEAAAICRAEAOw==";if(A("IE7-"))try{document.execCommand("BackgroundImageCache",false,true)}catch(w){}u=l.namespace(u);u.toString=function(){return t};return u.extend({testImage:o,
prettyName:t,test:A,is:function(i){return A(i)},Cookies:{set:function(i,g,e,a){document.cookie=i+"="+(g==null?"":escape(g))+";path="+(a||(location.pathname.indexOf("/")==0?"":"/")+location.pathname)+(e?";expires="+(new Date(Date.now()+e*1E3)).toGMTString():"")},get:function(i){return(i=document.cookie.match(RegExp("(^|;)\\s*"+i+"\\s*=\\s*(.*?)\\s*(;|$)")))&&unescape(i[2])},remove:function(i,g){document.cookie=i+"=;expires="+(new Date(0)).toGMTString()+";path="+(g||(location.pathname.indexOf("/")==
0?"":"/")+location.pathname)}}})})(basis,this);
(function(l,q){function v(a,b,d){if(b!=null)return a.insertBefore(c(b)?b:y(b),d||null)}function A(a){return t("",a.cloneNode(true)).innerHTML}function u(a){return c(a)||a&&a.nodeType?a:typeof a=="string"?n.getElementById(a):null}function B(b,c,f){var h,k=[],f=typeof f=="string"?getter(f):f||Function.$true;c&26&&f(b)&&k.push(b);switch(c){case 1:case 2:for(h=b;(h=h[s])&&h!==b.document;)f(h)&&k.push(h);break;case 64:for(h=b[g];h;)f(h)&&k.push(h),h=h[e];break;case 4:case 8:b[g]&&(c=new d(b),c.nodes(f,
k));break;case 128:c=new d(b,f);for(c.cursor_=b[e]||b[s];h=c.next();)k.push(h);break;case 256:for(h=b;h=h[e];)f(h)&&k.push(h);break;case 32:f(b[s])&&k.push(b[s]);break;case 512:c=new d(b,f,d.BACKWARD);for(c.cursor_=b[a]||b[s];h=c.next();)k.push(h);break;case 1024:for(h=b;h=h[a];)f(h)&&k.push(h)}return k}function y(a){return n.createTextNode(a!=null?a:"")}function o(){for(var a=n.createDocumentFragment(),b=arguments.length,c=o.array=[],d=0;d<b;d++)c.push(v(a,arguments[d]));return a}function t(a,b){var c=
a!=void 0&&typeof a!="string",d=(c?a.description:a)||"",f="div",m=d.match(/^([a-z0-9\_\-]+)(.*)$/i);m&&(f=m[1],d=m[2]);if(d!=""){for(var F=[],C={},J;m=j.exec(d);){if(m[8])throw Error("Create element error in basis.dom.createElement()\n\nDescription:\n> "+d+"\n\nProblem place:\n> "+d.substr(0,m.index)+"--\>"+d.substr(m.index)+"<--");J=m[1]||m[2]||m[3];m[1]?C.id=J:m[2]?F.push(J):J!="class"&&(C[J]=m[4]?r(m[5],m[6],m[7]):J)}h&&C.name&&/^(input|textarea|select)$/i.test(f)&&(f="<"+f+" name="+C.name+">")}d=
n.createElement(f);if(C){if(C.style&&k)d.style.cssText=C.style;for(var g in C)d.setAttribute(g,C[g],0)}if(F&&F.length)d.className=F.join(" ");arguments.length>1&&v(d,o.apply(0,Array.from(arguments,1).flatten()));if(c&&(a.css&&l.cssom&&l.cssom.setStyle(d,a.css),l.dom.event))for(var e in a)typeof a[e]=="function"?l.dom.event.addHandler(d,e,a[e],d):a[e]instanceof l.dom.event.Handler&&l.dom.event.addHandler(d,e,a[e].handler,a[e].thisObject);return d}function x(a,b){return a[s]?a[s].replaceChild(b,a):
a}function i(a){if(n.selection){var b=n.selection.createRange();b.compareEndPoints("StartToEnd",b)!=0&&b.collapse(a);return b.getBookmark().charCodeAt(2)-2}}var r=Object.coalesce,n=q.document,z=l.Class,w=n.createElement("div"),s="parentNode",g="firstChild",e="nextSibling",a="previousSibling",b;b=typeof w.compareDocumentPosition=="function"?function(a,b){return a.compareDocumentPosition(b)}:function(a,b){return a==b?0:a.document!=b.document?33:a.sourceIndex>b.sourceIndex?2|8*b.contains(childA):4|16*
a.contains(childB)};var c;if(typeof Node!="undefined"){if(c=function(a){return a instanceof Node},!Node.prototype.contains)Node.prototype.contains=function(a){return!!(this.compareDocumentPosition(a)&16)}}else c=function(a){return a&&a.ownerDocument===n};var d=z(null,{root_:null,cursor_:null,filter:Function.$true,init:function(a,b,c){this.setRoot(a);this.setDirection(c);if(typeof b=="function")this.filter=b},setDirection:function(b){Object.extend(this,b?{a:"lastChild",b:a,c:e,d:g}:{a:g,b:e,c:a,d:"lastChild"})},
setRoot:function(a){this.root_=a||n;this.reset()},reset:function(){this.cursor_=null},first:function(a){this.reset();return this.next(a)},last:function(a){this.reset();return this.prev(a)},nodes:function(a,b){var c;b||(b=[]);for(this.reset();c=this.next(a);)b.push(c);return b},next:function(a){var a=a||this.filter,b=this.cursor_||this.root_;do for(var c=b[this.a];!c;){if(b===this.root_)return this.cursor_=null;(c=b[this.b])||(b=b[s])}while(!a(b=c));return this.cursor_=b},prev:function(a){var a=a||
this.filter,b=this.cursor_,c=this.c,d=this.d;do{var f=b?b[c]:this.root_[d];if(f){for(;f[d];)f=f[d];b=f}else b&&(b=b[s]);if(!b||b===this.root_){b=null;break}}while(!a(b));return this.cursor_=b},destroy:function(){this.cursor_=this.root_=null}});d.BACKWARD=true;var f="textContent innerText nodeValue".qw(),h=function(){var a=n.createElement("input");a.name="a";return!/name/.test(A(a))}(),k;w.setAttribute("style","color: red");k=w.style.color!=="red";var j=/#([a-z0-9\_\-\:]+)|\.([a-z0-9\_\-\:]+)|\[([a-z0-9\_\-:]+)(="((?:\\.|[^"])*)"|='((?:\\.|[^'])*)'|=((?:\\.|[^\]])*))?\s*\]|\s*(\S)/gi;
return l.namespace("basis.dom").extend({ELEMENT_NODE:1,ATTRIBUTE_NODE:2,TEXT_NODE:3,CDATA_SECTION_NODE:4,ENTITY_REFERENCE_NODE:5,ENTITY_NODE:6,PROCESSING_INSTRUCTION_NODE:7,COMMENT_NODE:8,DOCUMENT_TYPE_NODE:10,DOCUMENT_NODE:9,DOCUMENT_FRAGMENT_NODE:11,NOTATION_NODE:12,AXIS_ANCESTOR:1,AXIS_ANCESTOR_OR_SELF:2,AXIS_DESCENDANT:4,AXIS_DESCENDANT_OR_SELF:8,AXIS_SELF:16,AXIS_PARENT:32,AXIS_CHILD:64,AXIS_FOLLOWING:128,AXIS_FOLLOWING_SIBLING:256,AXIS_PRESCENDING:512,AXIS_PRESCENDING_SIBLING:1024,INSERT_BEGIN:"begin",
INSERT_END:"end",INSERT_BEFORE:"before",INSERT_AFTER:"after",TreeWalker:d,outerHTML:A,textContent:function(a){for(var b=0,c;c=f[b++];)if(a[c]!=null)return a[c];return B(a,4,function(a){return a.nodeType==3}).map(getter("nodeValue")).join("")},get:u,tag:function(a,b){a=u(a)||n;return b=="*"&&a.all?Array.from(a.all):Array.from(a.getElementsByTagName(b||"*"))},axis:B,findAncestor:function(a,b,c){for(;a&&a!==c;){if(b(a))return a;a=a.parentNode}},createElement:t,createText:y,createFragment:o,insert:function(a,
b,d,f){a=u(a);if(!a)throw Error("basis.dom.insert: destination node can't be null");switch(d){case void 0:case "end":f=null;break;case "begin":f=a[g];break;case "before":break;case "after":f=f[e];break;default:f=Number(d).between(0,a.childNodes.length)?a.childNodes[d]:null}d=!c(a);if(!b||!Array.isArray(b))d=d?b&&a.insertBefore(b,f):v(a,b,f);else if(d)for(var d=[],h=0,m=b.length;h<m;h++)d[h]=a.insertBefore(b[h],f);else a.insertBefore(o.apply(0,b),f),d=o.array;return d},remove:function(a){return a[s]?
a[s].removeChild(a):a},replace:x,swap:function(a,c){if(a===c||b(a,c)&25)return false;x(a,w);x(c,a);x(w,c);return true},clone:function(a,b){var c=a.cloneNode(!b);c.attachEvent&&B(c,8).forEach(Event.clearHandlers);return c},clear:function(a){for(a=u(a);a.lastChild;)a.removeChild(a.lastChild);return a},wrap:function(a,b,c){var d=[],c=Function.getter(c||Function.$self),f;for(f in b)for(var m=0;m<a.length;m++){var h=c(a[m]);d[m]=b[f](a[m],m,h)?t(f,h):a[m]}return d},setAttribute:function(a,b,c){c==null?
a.removeAttribute(b):a.setAttribute(b,c)},parentOf:function(a,b){return a.contains(b)},isInside:function(a,b){return a==b||b.contains(a)},focus:function(a,b){try{a=u(a),a.focus(),b&&a.select&&a.select()}catch(c){}},setSelectionRange:function(a,b,c){arguments.length<3&&(c=b);if(a.setSelectionRange)a.setSelectionRange(b,c);else if(a.createTextRange){var d=a.createTextRange();d.collapse(true);d.moveStart("character",b);d.moveEnd("character",c-b);d.select()}},getSelectionStart:function(a){return typeof a.selectionStart!=
"undefined"?a.selectionStart:i(true)},getSelectionEnd:function(a){return typeof a.selectionEnd!="undefined"?a.selectionEnd:i(false)}})})(basis,this);
(function(l,q){function v(a){return a||q.event}function A(a){return typeof a=="string"?r.get(a):a}function u(a){a=v(a);a.stopPropagation?a.stopPropagation():a.cancelBubble=true}function B(a){a=v(a);a.preventDefault?a.preventDefault():a.returnValue=false}function y(a){var b=Array.from(s[a.type]);if(b)for(var c=b.length;c-- >0;){var d=b[c];d.handler.call(d.thisObject,a)}}function o(a,b,c,d){a=A(a);if(!a)throw Error("Event.addHandler: can't attach event listener to undefined");if(typeof c!="function")throw Error("Event.addHandler: handler must be a function");
a[z]||(a[z]={});var f={handler:c,thisObject:d},h=a[z],e=h[b];if(e){for(a=0;b=e[a];a++)if(b.handler===c&&b.thisObject===d)return;e.push(f)}else e=h[b]=[f],e.fireEvent=function(a){a=v(a);if(g&&a&&typeof a.returnValue=="undefined"){y(a);if(a.cancelBubble===true)return;if(typeof a.returnValue=="undefined")a.returnValue=true}for(var b=0,c;c=e[b++];)c.handler.call(c.thisObject,a)},a.addEventListener?a.addEventListener(b,e.fireEvent,false):a.attachEvent("on"+b,e.fireEvent)}function t(a,b,c,d){var a=A(a),
f=a[z];if(f&&(f=f[b]))for(var h=0,e;e=f[h];h++)if(e.handler===c&&e.thisObject===d){f.splice(h,1);f.length||x(a,b);break}}function x(a,b){var a=A(a),c=a[z];if(c)if(typeof b!="string")for(b in c)x(a,b);else{var d=c[b];d&&(a.removeEventListener?a.removeEventListener(b,d.fireEvent,false):a.detachEvent("on"+b,d.fireEvent),delete c[b])}}var i=q.document,r=l.dom,n=Function.$null,z="__basisEvents",w={mousewheel:["mousewheel","DOMMouseScroll"]},s={},g=!i.addEventListener,e=function(){function a(){b++||setTimeout(function(){for(var a=
0;a<c.length;a++)c[a].callback.call(c[a].thisObject)},10)}var b=false,c=[];if(l.ua.is("ie7-"))(function(){var b="_"+Date.now();i.write('<script id="'+b+'" defer src="//:"><\/script>');A(b).onreadystatechange=function(){this.readyState=="complete"&&(r.remove(this),a())}})();else if(l.ua.is("safari525-"))var d=setInterval(function(){/loaded|complete/.test(i.readyState)&&(clearInterval(d),a())},15);else o(i,"DOMContentLoaded",a,false);o(i,"load",a,false);o(q,"load",a,false);return function(a,d){b||c.push({callback:a,
thisObject:d})}}();return l.namespace("basis.dom.event",v).extend({KEY:{BACKSPACE:8,TAB:9,CTRL_ENTER:10,ENTER:13,SHIFT:16,CTRL:17,ALT:18,ESC:27,ESCAPE:27,SPACE:32,PAGEUP:33,PAGEDOWN:34,END:35,HOME:36,LEFT:37,UP:38,RIGHT:39,DOWN:40,INSERT:45,DELETE:46,F5:116},MOUSE_LEFT:{VALUE:1,BIT:1},MOUSE_RIGHT:{VALUE:3,BIT:2},MOUSE_MIDDLE:{VALUE:2,BIT:4},browserEvents:function(a){return w[a]||[a]},Handler:function(a,b){this.handler=a;this.thisObject=b},sender:function(a){a=v(a);return a.target||a.srcElement},cancelBubble:u,
cancelDefault:B,kill:function(a,b){(b=A(b))?o(b,a,Event.kill):(B(a),u(a))},key:function(a){a=v(a);return a.keyCode||a.which||0},charCode:function(a){a=v(a);return a.charCode||a.keyCode||0},mouseButton:function(a,b){a=v(a);return typeof a.which=="number"?a.which==b.VALUE:a.button&b.BIT},mouseX:function(a){a=v(a);return a.changedTouches?a.changedTouches[0].pageX:"pageX"in a?a.pageX:a.clientX+(i.documentElement.scrollLeft||i.body.scrollLeft)},mouseY:function(a){a=v(a);return a.changedTouches?a.changedTouches[0].pageY:
"pageY"in a?a.pageY:a.clientY+(i.documentElement.scrollTop||i.body.scrollTop)},wheelDelta:function(a){a=v(a);return"wheelDelta"in a?a.wheelDelta/120:a.type=="DOMMouseScroll"?-a.detail/3:0},addGlobalHandler:function(a,b,c){var d=s[a];if(d)for(a=d.length;a-- >0;){var f=d[a];if(f.handler===b&&f.thisObject===c)return}else i.addEventListener?i.addEventListener(a,y,true):o(i,a,n),d=s[a]=[];d.push({handler:b,thisObject:c})},removeGlobalHandler:function(a,b,c){var d=s[a];if(d)for(var f=0,h;h=d[f];f++)if(h.handler===
b&&h.thisObject===c){d.splice(f,1);d.length||(delete s[a],i.removeEventListener?i.removeEventListener(a,y,true):t(i,a,n));break}},addHandler:o,addHandlers:function(a,b,c){var a=A(a),d;for(d in b)o(a,d,b[d],c)},removeHandler:t,clearHandlers:x,fireEvent:function(a,b){var a=A(a),c=a[z];c&&c[b]&&c[b].fireEvent()},onLoad:e,onUnload:function(a,b){o(q,"unload",a,b)}})})(basis,this);
(function(){function l(a,b,c){for(var d=1,f;b;)b&1&&(f=n[d],c&d?(a.addHandler(f.handler,f.context),f.action(f.context.add,a)):(a.removeHandler(f.handler,f.context),f.action(f.context.remove,a))),b>>=1,d<<=1}function q(a){return Array.isArray(a)?a.map(q):{data:a}}var v=basis.Class,A=basis.EventObject,u=Object.values,B=Function.$self,y=A.createEvent,o=A.event,t={},x=[],i={},r={PRIORITY:[],values_:{},add:function(a,b){var c=a.toUpperCase(),d=a.toLowerCase();this[c]=d;i[d]=true;b&&(b=this.indexOf(b),
b==-1?this.PRIORITY.push(d):this.PRIORITY.splice(b,0,d))}};r.add("READY");r.add("DEPRECATED");r.add("UNDEFINED");r.add("ERROR");r.add("PROCESSING");var n={},z=1,w={NONE:0,MASK:0,add:function(a,b,c){n[z]={handler:b,action:c,context:{add:function(b,c){if(c){var h=w[a]+"_"+b.eventObjectId;if(!c.subscribers_)c.subscribers_={};if(!c.subscribers_[h]){var e=c.subscriberCount;c.subscribers_[h]=b;c.subscriberCount+=1;c.event_subscribersChanged(c,e)}}},remove:function(b,c){if(c){var h=w[a]+"_"+b.eventObjectId;
if(c.subscribers_[h]){var e=c.subscriberCount;delete c.subscribers_[h];c.subscriberCount-=1;c.event_subscribersChanged(c,e)}}}}};w[a]=z;w.MASK|=z;z<<=1}};w.add("DELEGATE",{delegateChanged:function(a,b){this.remove(a,b);this.add(a,a.delegate)}},function(a,b){a(b,b.delegate)});w.add("TARGET",{targetChanged:function(a,b){this.remove(a,b);this.add(a,a.target)}},function(a,b){a(b,b.target)});var s=v(A,{state:r.READY,data:null,canHaveDelegate:true,delegate:null,root:null,cascadeDestroy:false,isTarget:false,
target:null,active:false,subscribeTo:w.DELEGATE+w.TARGET,subscriberCount:0,subscribers_:null,event_update:y("update","object","delta"),event_stateChanged:y("stateChanged","object","oldState"),event_delegateChanged:y("delegateChanged","object","oldDelegate"),event_rootChanged:y("rootChanged","object","oldRoot"),event_targetChanged:y("targetChanged","object","oldTarget")&&function(a,b){var c=this.listen.target;c&&(b&&b.removeHandler(c,this),this.target&&this.target.addHandler(c,this));o.targetChanged.call(this,
a,b)},event_subscribersChanged:y("subscribersChanged","object"),event_activeChanged:y("activeChanged","object"),listen:{delegate:{update:function(a,b){this.data=a.data;this.event_update(this,b)},stateChanged:function(a,b){this.state=a.state;this.event_stateChanged(this,b)},targetChanged:function(a,b){this.target=a.target;this.event_targetChanged(this,b)},rootChanged:function(a,b){this.data=a.data;this.event_rootChanged(this,b)},destroy:function(){this.cascadeDestroy?this.destroy():this.setDelegate()}}},
init:function(a){A.prototype.init.call(this,a);if(a=this.delegate)this.delegate=null,this.data=a.data,this.state=a.state,this.setDelegate(a);else{this.root=this;if(!this.data)this.data={};if(this.isTarget)this.target=this}this.active&&l(this,this.subscribeTo,w.MASK)},isConnected:function(a){if(a instanceof s){for(;a&&a!==this&&a!==a.delegate;)a=a.delegate;return a===this}return false},getRootDelegate:function(){for(var a=this;a.delegate&&a.delegate!==a;)a=a.delegate;return a},setDelegate:function(a){if(this.canHaveDelegate&&
a&&a instanceof s){if(a.delegate&&this.isConnected(a))return false}else a=null;if(this.delegate!==a){var b=this.state,c=this.data,d=this.delegate,f=this.target,h=this.root,e={};d&&d.removeHandler(this.listen.delegate,this);if(a){this.delegate=a;this.root=a.root;this.data=a.data;this.state=a.state;this.target=a.target;a.addHandler(this.listen.delegate,this);for(var g in a.data)g in c===false&&(e[g]=void 0);for(g in c)c[g]!==a.data[g]&&(e[g]=c[g])}else for(g in this.target=this.delegate=null,this.root=
this,this.data={},c)this.data[g]=c[g];this.event_delegateChanged(this,d);this.root!==h&&this.event_rootChanged(this,h);this.target!==f&&this.event_targetChanged(this,f);if(a){for(g in e){this.event_update(this,e);break}b!==this.state&&(String(b)!=this.state||b.data!==this.state.data)&&this.event_stateChanged(this,b)}return true}return false},setState:function(a,b){var c=this.target||this.getRootDelegate();if(c!==this)return c.setState(a,b);c=String(a);if(!i[c])throw Error("Wrong state value");if(this.state!=
c||this.state.data!=b){var d=this.state;this.state=Object(c);this.state.data=b;this.event_stateChanged(this,d);return true}return false},deprecate:function(){this.state!=r.PROCESSING&&this.setState(r.DEPRECATED)},update:function(a){var b=this.target||this.getRootDelegate();if(b!==this)return b.update(a);if(a){var b={},c=0,d;for(d in a)this.data[d]!==a[d]&&(c++,b[d]=this.data[d],this.data[d]=a[d]);if(c)return this.event_update(this,b),b}return false},setActive:function(a){a=!!a;return this.active!=
a?(this.active=a,this.event_activeChanged(this),l(this,this.subscribeTo,w.MASK*a),true):false},setSubscription:function(a){a&=w.MASK;var b=this.subscribeTo^a;return b?(this.subscribeTo=a,this.active&&l(this,b,a),true):false},destroy:function(){this.active&&l(this,this.subscribeTo,0);this.delegate&&this.setDelegate();A.prototype.destroy.call(this);this.data=t;this.state=r.UNDEFINED;this.target=this.root=null}}),B=v(null,{itemClass:s,keyGetter:B,map_:null,extendConstructor_:true,init:function(){this.map_=
{};basis.Cleaner.add(this)},resolve:function(a){return this.get(this.keyGetter(a),a)},create:function(a){var b={};a instanceof s?b.delegate=a:b.data={id:a,title:a};return new this.itemClass(b)},get:function(a,b){var c=a instanceof s?a.eventObjectId:a,d=this.map_[c];!d&&b&&(d=this.map_[c]=this.create(a,b),d.addHandler({destroy:function(){delete this.map_[c]}},this));return d},destroy:function(){basis.Cleaner.remove(this);for(var a=u(this.map_),b=0,c;c=a[b++];)c.destroy()}}),g=v(s,{state:r.UNDEFINED,
itemCount:0,item_:null,memberMap_:null,cache_:null,event_datasetChanged:y("datasetChanged","dataset","delta")&&function(a,b){var c,d=0,f=0,h;if(c=b.inserted)for(;h=c[d];)this.item_[h.eventObjectId]=h,d++;if(c=b.deleted)for(;h=c[f];)delete this.item_[h.eventObjectId],f++;this.itemCount+=d-f;this.cache_=null;o.datasetChanged.call(this,a,b)},init:function(a){s.prototype.init.call(this,a);this.memberMap_={};this.item_={}},has:function(a){return!(!a||!this.item_[a.eventObjectId])},getItems:function(){if(!this.cache_)this.cache_=
u(this.item_);return this.cache_},pick:function(){for(var a in this.item_)return this.item_[a];return null},top:function(a){var b=[];if(a)for(var c in this.item_)if(b.push(this.item_[c])>=a)break;return b},add:function(){},remove:function(){},set:function(){},sync:function(){},clear:function(){},destroy:function(){this.clear();s.prototype.destroy.call(this);this.cache_=x;this.itemCount=0;this.item_=this.memberMap_=null}}),e=v(g,{listen:{item:{destroy:function(a){this.memberMap_[a.eventObjectId]&&
this.remove([a])}}},init:function(a){g.prototype.init.call(this,a);if(a=this.items)this.set(a),this.items=null},add:function(a){for(var b,c=this.memberMap_,d=[],f=0;f<a.length;f++){var h=a[f];if(h instanceof s){var e=h.eventObjectId;c[e]||(c[e]=h,h.addHandler(this.listen.item,this),d.push(h))}}d.length&&this.event_datasetChanged(this,b={inserted:d});return b},remove:function(a){for(var b,c=this.memberMap_,d=[],f=0;f<a.length;f++){var h=a[f];if(h instanceof s){var e=h.eventObjectId;c[e]&&(h.removeHandler(this.listen.item,
this),delete c[e],d.push(h))}}d.length&&this.event_datasetChanged(this,b={deleted:d});return b},set:function(a){if(!this.itemCount)return this.add(a);if(!a.length)return this.clear();for(var b=this.memberMap_,c={},d=[],f=[],h,e,g,i=0;i<a.length;i++)if(h=a[i],h instanceof s)e=h.eventObjectId,c[e]=h,b[e]||(b[e]=h,h.addHandler(this.listen.item,this),f.push(h));for(e in b)c[e]||(h=b[e],h.removeHandler(this.listen.item,this),delete b[e],d.push(h));var l;var a={},n;if(f&&f.length)n=a.inserted=f;if(d&&d.length)n=
a.deleted=d;n&&(l=a);(g=l)&&this.event_datasetChanged(this,g);return g},sync:function(a,b){if(a){e.setAccumulateState(true);for(var c=this.memberMap_,d,f,h={},g=[],j,i=0;i<a.length;i++)if(d=a[i],d instanceof s)f=d.eventObjectId,h[f]=d,c[f]||g.push(d);for(f in this.item_)h[f]||this.item_[f].destroy();b&&g.length&&(j=this.add(g));e.setAccumulateState(false);return j}},clear:function(){var a,b=this.getItems();if(b.length){for(a=b.length;a-- >0;)b[a].removeHandler(this.listen.item,this);this.event_datasetChanged(this,
a={deleted:b});this.memberMap_={}}return a}});e.setAccumulateState=function(){function a(a){var b=a.dataset;f.call(b,b,a)}function b(b,c){var d=b.eventObjectId,e=c.inserted,h=c.deleted,m=j[d];if(e&&h)return m&&(delete j[d],a(m)),f.call(b,b,c);if(m){var g=m[e?"inserted":"deleted"];if(g)return g.push.apply(g,e||h);else a(m)}j[d]=c;c.dataset=b}function c(){e=1;setAccumulateState(false)}var d=g.prototype,f=d.event_datasetChanged,e=0,k,j={};return function(g){if(g){if(e==0)d.event_datasetChanged=b,k=setTimeout(c,
0);e++}else if(e-=e>0,e==0)clearTimeout(k),d.event_datasetChanged=f,g=j,j={},u(g).forEach(a)}}();basis.namespace("basis.data",q).extend({STATE:r,SUBSCRIPTION:w,Object:s,DataObject:s,KeyObjectMap:B,AbstractDataset:g,Dataset:e})})(basis,this);
(function(l,q){function v(a,c,d,f){for(var c=c.split(/\{([a-z0-9\_]+(?:\|[^}]*)?)\}/i),e=s(),k,j=0;j<c.length;j++)j%2?(k=c[j].split(/\|/),a.getters[k[0]]=d+"childNodes["+f+"]",k=k.length>1?k[1]:k[0]):k=c[j].length?c[j]:null,k!=null&&(w&&(e.lastChild&&e.appendChild(o.createComment("")),f++),e.appendChild(g(k)),f++);return e}function A(a){return function(c){if(!c||!(c.type=="click"&&c.which==3)){var d=l.dom.event.sender(c),f,e;do if(f=d.getAttributeNode&&d.getAttributeNode(a))break;while(d=d.parentNode);
if(d&&f){do if(e=d.basisObjectId)if((e=r[e])&&e.templateAction){d=f.nodeValue.qw();f=0;for(var g;g=d[f++];)e.templateAction(g,l.dom.event(c));break}while(d=d.parentNode)}}}}function u(a,c,d){c=c.trim();if(!c)return"";for(var f="",e;e=z.exec(c);){var g=e[2],j=e[4]||e[5]||g;e[3]&&(a.getters[e[3]]=d+'.getAttributeNode("'+g+'")');if(e=g.match(/^event-([a-z]+)/i)){var p=e[1];if(!i[p]){i[p]=true;e=0;for(var p=l.dom.event.browserEvents(p),n;n=p[e++];)l.dom.event.addGlobalHandler(n,A(g))}if(!window.__basis_emitEvent)window.__basis_emitEvent=
function(a,b){var a=l.dom.event(a),c=this,m;do if(m=c.basisObjectId)if((m=r[m])&&m.templateAction){for(var c=b.qw(),d=0,C;C=c[d++];)m.templateAction(C,l.dom.event(a));break}while(c=c.parentNode)}}f+=g=="class"?j.trim().replace(/^(.)|\s+/g,".$1"):"["+g+(j?"="+j.quote('"'):"")+"]"}return f}function B(a,c){if(!a.stack)a.stack=[];if(!a.source)a.source=a.str;c||(c=".");for(var d=s(),f,e=0,g,j=a.stack;g=n.exec(a.str);){f=RegExp.leftContext;a.str=a.str.substr(f.length+g[0].length);if(f.length)d.appendChild(v(a,
f,c,e)),e=d.childNodes.length;if(g[5])if(g[5]==j[j.length-1])return j.pop(),d;else throw"Wrong end tag";if(g[6])g[7]&&(a.getters[g[7]]=c+"childNodes["+e+"]"),d.appendChild(o.createComment(g[6]));else{f=g[1];var i=g[2],l=!!g[4],q=c+"childNodes["+e+"]";g=t.createElement(f+u(a,g[3],q));i&&(a.getters[i]=q);l||(j.push(f),g.appendChild(B(a,q+".")));d.appendChild(g)}e++}a.str.length&&d.appendChild(v(a,a.str,c,e));if(j.length)throw"No end tag for "+j.reverse();return d}function y(a){if(!this.proto){a=this.source;
if(typeof a=="function")this.source=a=a();for(var a=a.trim(),a={str:a,getters:{element:".childNodes[0]"}},c=B(a),a=Object.iterate(a.getters,function(a,b){for(var d=a.split(/\|/).map(String.format,"obj_.{0}"),f=b.split(/(\.?childNodes\[(\d+)\])/),e=c,g=0;g<f.length;g+=3){var m=f[g+2];if(!m)break;f[g+2]="";e=e.childNodes[m];e.previousSibling?e.nextSibling||(f[g+1]=".lastChild"):f[g+1]=".firstChild"}return{name:d[0],alias:d.join("="),path:"dom_"+f.join("")}}).sortAsObject("path"),d=0;d<a.length;d++)for(var f=
RegExp("^"+a[d].path.forRegExp()),e=d+1,g;g=a[e++];)g.path=g.path.replace(f,a[d].name);this.createInstance=(new Function("proto_","map_","var obj_, dom_; return "+function(a,b){obj_=a||{};dom_=proto_.cloneNode(true);_code_();if(b&&obj_.element){var c=obj_.element.basisObjectId=map_.seed++;map_[c]=b}return obj_}.toString().replace("_code_()",a.map(String.format,"{alias}={path};\n").join(""))))(c,r);this.clearInstance=(new Function("map_","var obj_; return "+function(a){obj_=a;(a=obj_.element&&obj_.element.basisObjectId)&&
delete map_[a];_code_()}.toString().replace("_code_()",a.map(String.format,"{alias}=null;\n").join(""))))(r)}}var o=q.document,t=l.dom,x=l.Class,i={},r={seed:1},n=/<([a-z0-9\_]+)(?:\{([a-z0-9\_\|]+)\})?([^>]*?)(\/?)>|<\/([a-z0-9\_]+)>|<\!--(\s*\{([a-z0-9\_\|]+)\}\s*|.*?)--\>/i,z=/(?:([a-z0-9\_\-]+):)?([a-z0-9\_\-]+)(?:\{([a-z0-9\_\|]+)\})?(?:="((?:\\.|[^"])*?)"|='((?:\\.|[^'])*?)')?\s*/gi;t.createFragment();var w=t.createElement("","a","b").cloneNode(true).childNodes.length==1,s=t.createFragment,
g=t.createText,e=x(null,{__extend__:function(a){return a instanceof e?a:new e(a)},init:function(a){this.source=a},createInstance:function(a,c){y.call(this);return this.createInstance(a,c)},clearInstance:function(){y.call(this)}}),a=o.createElement("DIV");return l.namespace("basis.html").extend({Template:e,escape:function(a){return t.createElement("DIV",t.createText(a)).innerHTML},unescape:function(b){a.innerHTML=b;return a.firstChild.nodeValue},string2Html:function(b){a.innerHTML=b;return t.createFragment.apply(null,
Array.from(a.childNodes))}})})(basis,this);
(function(l){function q(a){return a.sortingValue||0}function v(a,b){a=a.sortingValue||0;b=b.sortingValue||0;return+(a>b)||-(a<b)}function A(a,b){a=a.sortingValue||0;b=b.sortingValue||0;return-(a>b)||+(a<b)}function u(a){return a.childNodes.sort(a.localSortingDesc?A:v)}function B(a,b){var c=b.length-1;a.childNodes=b;a.firstChild=b[0]||null;a.lastChild=b[c]||null;for(var d=c;c=b[d];d--)c.nextSibling=b[d+1]||null,c.previousSibling=b[d-1]||null,a.insertBefore(c,c.nextSibling)}function y(a,b){var c=a.childFactory||
a.document&&a.document.childFactory,d,b=Object.extend({document:a.document,contextSelection:a.selection||a.contextSelection},b);if(c&&(d=c.call(a,b),d instanceof a.childClass))return d;if(!d)throw"basis.dom.wrapper: Child node is null";throw"basis.dom.wrapper: Child node has wrong class (expected "+(a.childClass&&a.childClass.className)+" but "+(d&&d.constructor&&d.constructor.className)+")";}function o(){return l.ui.apply(this,arguments)}var t=l.Class,x=l.dom,i=l.data,r=i.SUBSCRIPTION,n=i.DataObject,
z=i.AbstractDataset,w=i.Dataset,s=x.AXIS_DESCENDANT,g=x.AXIS_DESCENDANT_OR_SELF,e=Function.getter,a=Object.complete,b=x.axis,i=l.EventObject.createEvent,c=l.EventObject.event;r.add("DATASOURCE",{dataSourceChanged:function(a,b){this.remove(a,b);this.add(a,a.dataSource)}},function(a,b){a(b,b.dataSource)});var d=t.ExtensibleProperty(),f={ownerChanged:function(){},destroy:function(a){x.replace(a.element,this)}},h=function(){var a=this.key,b=this.config,c=this.owner,d=typeof b.existsIf!="function"||b.existsIf(c),
e=c.satellite[a];if(d){var d="delegate"in b,g="dataSource"in b,h=typeof b.delegate=="function"?b.delegate(c):null,i=typeof b.dataSource=="function"?b.dataSource(c):null;if(e)d&&e.setDelegate(h),g&&e.setDataSource(i);else{var E=c.tmpl[b.replace||a],e={owner:c};if(d)e.delegate=h;if(g)e.dataSource=i;b.config&&Object.complete(e,typeof b.config=="function"?b.config(c):b.config);e=new b.instanceOf(e);c.satellite[a]=e;E&&e instanceof l.ui.Node&&e.element&&(x.replace(E,e.element),e.addHandler(f,E))}}else if(e)e.destroy(),
e.owner=null,delete c.satellite[a]},k=t.CustomExtendProperty({update:true},function(a,b){for(var c in b)a[c]=b[c]?h:null}),j=t(n,{event_update:function(a,b){n.prototype.event_update.call(this,a,b);var c=this.parentNode;c&&(c.matchFunction&&(this.match(),this.match(c.matchFunction)),c.insertBefore(this,this.nextSibling))},event_childNodesModified:i("childNodesModified","node","delta"),event_dataSourceChanged:i("dataSourceChanged","node","oldDataSource"),event_localGroupingChanged:i("localGroupingChanged",
"node","oldGroupingNode"),event_localSortingChanged:i("localSortingChanged","node","oldLocalSorting","oldLocalSortingDesc"),event_ownerChanged:i("ownerChanged","node","oldOwner"),event_satellitesChanged:i("satellitesChanged","node","delta"),subscribeTo:n.prototype.subscribeTo+r.DATASOURCE,listen:{owner:{destroy:function(){this.setOwner()}}},autoDelegateParent:false,nodeType:"DOMWrapperNode",canHaveChildren:false,childNodes:null,dataSource:null,colMap_:null,destroyDataSourceMember:true,document:null,
parentNode:null,nextSibling:null,previousSibling:null,firstChild:null,lastChild:null,localSorting:null,localSortingDesc:false,localGrouping:null,localGroupingClass:null,groupNode:null,satelliteConfig:d,satellite:null,owner:null,init:function(a){var b=this.dataSource,c=this.childNodes,e=this.localGrouping;if(b)this.dataSource=null;n.prototype.init.call(this,a);if(e)this.localGrouping=null,this.setLocalGrouping(e);if(this.canHaveChildren)this.childNodes=[],b?(this.dataSource=null,this.setDataSource(b)):
c&&this.setChildNodes(c);else{if(c)this.childNodes=null;if(b)this.dataSource=null}if(!this.satellite)this.satellite={};if(this.satelliteConfig!==d)for(var f in this.satelliteConfig)if(a=this.satelliteConfig[f],t.isClass(a)&&(a={instanceOf:a}),typeof a=="object"){b={key:f,owner:this,config:a};a=a.hook?k.__extend__(a.hook):k;for(f in a)if(a[f]===h){this.addHandler(a,b);break}h.call(b)}if(f=this.owner)this.owner=null,this.setOwner(f)},appendChild:function(){},insertBefore:function(){},removeChild:function(){},
replaceChild:function(){},clear:function(){},hasChildNodes:function(){return this.childNodes.length>0},setChildNodes:function(){},setLocalGrouping:function(){},setLocalSorting:function(){},setDataSource:function(){},setOwner:function(a){if(!a||a instanceof j==false)a=null;if(this.owner!==a){var b=this.owner;b&&b.removeHandler(this.listen.owner,this);(this.owner=a)&&a.addHandler(this.listen.owner,this);this.event_ownerChanged(this,b)}},destroy:function(){n.prototype.destroy.call(this);this.dataSource?
this.setDataSource():this.firstChild&&this.clear();this.parentNode&&this.parentNode.removeChild(this);if(this.localGrouping)this.localGrouping.destroy(),this.localGrouping=null;this.owner&&this.setOwner();if(this.satellite){for(var a in this.satellite){var b=this.satellite[a];b.destroy();b.owner=null}this.satellite=null}this.lastChild=this.firstChild=this.nextSibling=this.previousSibling=this.parentNode=this.childNodes=this.document=null}}),p=t(j,{autoDestroyIfEmpty:false,nodes:null,first:null,last:null,
init:function(a){this.nodes=[];j.prototype.init.call(this,a)},insert:function(a,b){var c=this.nodes,d=b?c.indexOf(b):-1;d==-1?(c.push(a),this.last=a):c.splice(d,0,a);this.first=c[0];a.groupNode=this;this.event_childNodesModified(this,{inserted:[a]})},remove:function(a){var b=this.nodes;if(b.remove(a))this.first=b[0]||null,this.last=b[b.length-1]||null,a.groupNode=null,this.event_childNodesModified(this,{deleted:[a]});!this.first&&this.autoDestroyIfEmpty&&this.destroy()},clear:function(){if(this.first){for(var a=
this.nodes,b=a.length;b-- >0;)a[b].groupNode=null;this.nodes=[];this.last=this.first=null;this.event_childNodesModified(this,{deleted:a});this.autoDestroyIfEmpty&&this.destroy()}},destroy:function(){j.prototype.destroy.call(this);this.last=this.first=this.nodes=null}}),D={canHaveChildren:true,childClass:j,childFactory:null,listen:{dataSource:{datasetChanged:function(a,b){var c={},d=[];if(b.deleted)if(c.deleted=d,this.childNodes.length==b.deleted.length){d.push.apply(d,this.childNodes);var e=this.dataSource;
this.dataSource=null;this.clear(true);this.dataSource=e;this.colMap_={}}else for(var e=0,f;f=b.deleted[e];e++){f=f.eventObjectId;var g=this.colMap_[f];delete this.colMap_[f];g.canHaveDelegate=true;this.removeChild(g);d.push(g)}if(b.inserted){c.inserted=[];for(e=0;f=b.inserted[e];e++)g=y(this,{cascadeDestroy:false,delegate:f}),g.canHaveDelegate=false,this.colMap_[f.eventObjectId]=g,c.inserted.push(g),this.firstChild&&this.insertBefore(g)}this.firstChild?this.event_childNodesModified(this,c):this.setChildNodes(c.inserted);
if(this.destroyDataSourceMember&&d.length)for(e=0;f=d[e];e++)f.destroy()},destroy:function(a){this.dataSource===a&&this.setDataSource()}}},appendChild:function(a){return this.insertBefore(a)},insertBefore:function(a,c){if(!this.canHaveChildren)throw"basis.dom.wrapper: Node can't be inserted at specified point in hierarchy";if(a.firstChild){var d=this;do if(d==a)throw"basis.dom.wrapper: Node can't be inserted at specified point in hierarchy";while(d=d.parentNode)}if(this.dataSource&&!this.dataSource.has(a.delegate))throw"basis.dom.wrapper: Operation is not allowed because node is under dataSource control";
a instanceof this.childClass==false&&(a=y(this,a instanceof n?{delegate:a}:a));var e=a.parentNode===this,f=a.groupNode,g=this.localGrouping,h=this.localSorting,i,E=this.childNodes,k,j,l=null,d=-1,p=false,o;if(e)o=a.nextSibling,j=a.previousSibling;if(h&&(c=null,i=this.localSortingDesc,k=h(a)||0,e))if(k===a.sortingValue)p=true;else if((!o||(i?o.sortingValue<=k:o.sortingValue>=k))&&(!j||(i?j.sortingValue>=k:j.sortingValue<=k)))a.sortingValue=k,p=true;if(g){l=g.getGroupNode(a);j=l.nodes;if(f===l&&(p||
e&&o===c))return a;h?p?d=o&&o.groupNode===l?j.indexOf(o):j.length:(d=j.binarySearchPos(k,q,i),a.sortingValue=k):d=c&&c.groupNode===l?j.indexOf(c):j.length;if(d<j.length)c=j[d];else if(l.last)c=l.last.nextSibling;else{d=l;for(c=null;d=d.nextSibling;)if(c=d.first)break}if(a===c||e&&a.nextSibling===c)return f!==l&&(f&&f.remove(a),l.insert(a)),a;d=-1}else if(h){if(p)return a;d=E.binarySearchPos(k,q,i);c=E[d];a.sortingValue=k;if(a===c||e&&o===c)return a}else{if(c&&c.parentNode!==this)throw"basis.dom.wrapper: Node was not found";
if(e){if(o===c)return a;if(a===c)throw"basis.dom.wrapper: Node can't be inserted at specified point in hierarchy";}}e?(a.nextSibling?a.nextSibling.previousSibling=a.previousSibling:this.lastChild=a.previousSibling,a.previousSibling?a.previousSibling.nextSibling=a.nextSibling:this.firstChild=a.nextSibling,a.previousSibling=null,a.nextSibling=null,d==-1?E.remove(a):(i=E.indexOf(a),E.splice(i,1),i<d&&d--),f&&(f.remove(a),f=null)):a.parentNode&&a.parentNode.removeChild(a);f!=l&&l.insert(a,c);if(c){d==
-1&&(d=E.indexOf(c));if(d==-1)throw"basis.dom.wrapper: Node was not found";a.nextSibling=c;E.splice(d,0,a)}else d=E.length,E.push(a),c={previousSibling:this.lastChild},this.lastChild=a;a.parentNode=this;a.previousSibling=c.previousSibling;d==0?this.firstChild=a:c.previousSibling.nextSibling=a;c.previousSibling=a;var r=false,t=false,u=this.selection||this.contextSelection;if(!a.document&&a.document!==this.document)r=this.document,a.document=this.document;if(!a.contextSelection&&a.contextSelection!==
u)a.contextSelection=u,t=!a.selection,a.selected&&u.add([a]);a.firstChild&&(r||t)&&b(a,s).forEach(function(a){if(r&&!a.document)a.document=r;if(t&&!a.contextSelection)a.selected&&a.unselect(),a.contextSelection=u});e||(a.match&&a.match(this.matchFunction),a.autoDelegateParent&&a.setDelegate(this),this.dataSource||this.event_childNodesModified(this,{inserted:[a]}));return a},removeChild:function(a){if(a==null||a.parentNode!==this)throw"basis.dom.wrapper: Node was not found";if(a instanceof this.childClass==
false)throw"basis.dom.wrapper: Child node has wrong class";if(this.dataSource&&this.dataSource.has(a))throw"basis.dom.wrapper: Operation is not allowed because node is under dataSource control";this.childNodes.splice(this.childNodes.indexOf(a),1);a.parentNode=null;a.nextSibling?a.nextSibling.previousSibling=a.previousSibling:this.lastChild=a.previousSibling;a.previousSibling?a.previousSibling.nextSibling=a.nextSibling:this.firstChild=a.nextSibling;a.nextSibling=null;a.previousSibling=null;a.document===
this.document&&b(a,g).forEach(function(a){if(a.document==this.document)a.document=null},this);if(a.contextSelection){for(var c=a.contextSelection,d=a,e=[];d;){if(d.contextSelection===c)d.selected&&e.push(d),d.contextSelection=null;if(!d.selection&&d.firstChild)d=d.firstChild;else if(d.nextSibling)d=d.nextSibling;else for(;d=d.parentNode;)if(d.nextSibling){d=d.nextSibling;break}}c.remove(e)}a.groupNode&&a.groupNode.remove(a);this.dataSource||this.event_childNodesModified(this,{deleted:[a]});a.autoDelegateParent&&
a.setDelegate();return a},replaceChild:function(a,b){if(this.dataSource)throw"basis.dom.wrapper: Operation is not allowed because node is under dataSource control";if(b==null||b.parentNode!==this)throw"basis.dom.wrapper: Node was not found";this.insertBefore(a,b);return this.removeChild(b)},clear:function(a){if(this.dataSource)this.setDataSource();else if(this.firstChild){var c=this.childNodes;this.lastChild=this.firstChild=null;this.childNodes=[];this.event_childNodesModified(this,{deleted:c});for(var d=
c.length;d-- >0;){var e=c[d];e.parentNode=null;e.groupNode=null;a?((e.selection||e.document)&&b(e,x.AXIS_DESCENDANT_OR_SELF).forEach(function(a){if(this.selection&&a.selection===this.selection)a.selected&&a.selection.remove([a]),a.selection=null;if(a.document===this.document)a.document=null},this),e.nextSibling=null,e.previousSibling=null,e.autoDelegateParent&&e.setDelegate()):e.destroy()}if(this.localGrouping){a=this.localGrouping.childNodes;for(d=a.length-1;c=a[d];d--)c.clear()}}},setChildNodes:function(a,
b){this.dataSource||this.clear(!!b);if(a&&("length"in a==false&&(a=[a]),a.length)){var c=this.event_childNodesModified;this.event_childNodesModified=Function.$undef;for(var d=0,e=a.length;d<e;d++)this.insertBefore(a[d]);this.event_childNodesModified=c;this.event_childNodesModified(this,{inserted:this.childNodes})}},setDataSource:function(a){if(!a||!this.canHaveChildren||a instanceof z==false)a=null;if(this.dataSource!==a){var b=this.dataSource;if(b)this.colMap_=this.dataSource=null,b.removeHandler(this.listen.dataSource,
this),b.itemCount&&this.clear();if(a)this.dataSource=a,this.colMap_={},a.addHandler(this.listen.dataSource,this),a.itemCount&&this.listen.dataSource.datasetChanged.call(this,a,{inserted:a.getItems()});this.event_dataSourceChanged(this,b)}},setLocalGrouping:function(a){if(typeof a=="function"||typeof a=="string")a={groupGetter:e(a)};a instanceof H==false&&(a=a!=null&&typeof a=="object"?new this.localGroupingClass(Object.complete({},a)):null);if(this.localGrouping!==a){var b=this.localGrouping,c;if(this.localGrouping){if(!a&&
(this.localGrouping=null,this.firstChild)){c=this.localSorting?u(this):this.childNodes;for(var d=c.length;d-- >0;)c[d].groupNode=null;B(this,c)}b.setOwner()}if(a&&(this.localGrouping=a,a.setOwner(this),this.firstChild)){c=this.localSorting?u(this):this.childNodes;for(d=0;a=c[d];d++)a.groupNode=this.localGrouping.getGroupNode(a);for(d=0;a=c[d];d++)a.groupNode.nodes.push(a);c.length=0;for(d=this.localGrouping.nullGroup;d;d=d.nextSibling)a=d.nodes,d.first=a[0]||null,d.last=a[a.length-1]||null,c.push.apply(c,
a),d.event_childNodesModified(d,{inserted:a});B(this,c)}this.event_localGroupingChanged(this,b)}},setLocalSorting:function(a,b){a&&(a=e(a));if(this.localSorting!=a||this.localSortingDesc!=!!b){var c=this.localSorting,d=this.localSortingDesc;this.localSortingDesc=!!b;this.localSorting=a||null;if(a&&this.firstChild){var f=[],g;for(g=this.firstChild;g;g=g.nextSibling)g.sortingValue=a(g)||0;if(this.localGrouping)for(var h=this.localGrouping.nullGroup;h;h=h.nextSibling)g=h.nodes=u({childNodes:h.nodes,
localSortingDesc:this.localSortingDesc}),h.first=g[0]||null,h.last=g[g.length-1]||null,f.push.apply(f,g);else f=u(this);B(this,f)}this.event_localSortingChanged(this,c,d)}},setMatchFunction:function(a){if(this.matchFunction!=a){var b=this.matchFunction;this.matchFunction=a;for(var c=this.lastChild;c;c=c.previousSibling)c.match(a);this.event_matchFunctionChanged(this,b)}}},r=t(j,{event_enable:i("enable","node"),event_disable:i("disable","node"),event_select:i("select","node"),event_unselect:i("unselect",
"node"),event_match:i("match","node"),event_unmatch:i("unmatch","node"),event_matchFunctionChanged:i("matchFunctionChanged","node","oldMatchFunction"),selectable:true,selected:false,selection:null,contextSelection:null,matchFunction:null,matched:true,disabled:false,init:function(a){if(this.selection&&this.selection instanceof z==false)this.selection=new I(this.selection);j.prototype.init.call(this,a);this.disabled&&this.event_disable(this);if(this.selected)this.selected=false,this.select(true)},setSelection:function(a){if(this.selection==
a)return false;var c=this.selection;b(this,s,function(b){if(b.contextSelection==c)b.selected&&c&&c.remove([b]),b.contextSelection=a});this.selection=a;return true},hasOwnSelection:function(){return!!this.selection},select:function(a){var b=this.selected,c=this.contextSelection;if(c)a?b?c.remove([this]):c.add([this]):this.selectable&&c.set([this]);else if(!b&&this.selectable&&!this.isDisabled())this.selected=true,this.event_select(this);return this.selected!=b},unselect:function(){var a=this.selected;
if(a){var b=this.contextSelection;b?b.remove([this]):(this.selected=false,this.event_unselect(this))}return this.selected!=a},enable:function(){if(this.disabled)this.disabled=false,this.event_enable(this)},disable:function(){if(!this.disabled)this.disabled=true,this.event_disable(this)},isDisabled:function(){return this.disabled||this.document&&this.document.disabled||!!x.findAncestor(this,e("disabled"))},match:function(a){if(typeof a!="function")if(this.matched){if(this.underMatch_)this.underMatch_(this,
true),this.underMatch_=null}else this.matched=true,this.event_match(this);else if(a(this)){if(this.underMatch_=a,!this.matched)this.matched=true,this.event_match(this)}else if(this.underMatch_=null,this.matched)this.matched=false,this.event_unmatch(this)},setMatchFunction:function(){},destroy:function(){this.hasOwnSelection()&&(this.selection.destroy(),delete this.selection);this.unselect();j.prototype.destroy.call(this)}}),G=t(r,D,{}),H=t(j,D,{event_childNodesModified:function(a,b){c.childNodesModified.call(this,
a,b);this.nullGroup.nextSibling=this.firstChild;if(b.inserted&&this.dataSource&&this.nullGroup.first)for(var d=this.owner,e=Array.from(this.nullGroup.nodes),f=e.length;f-- >0;)d.insertBefore(e[f],e[f].nextSibling)},event_ownerChanged:function(a,b){b&&b.localGrouping===this&&b.setLocalGrouping(null,true);this.owner&&this.owner.localGrouping!==this&&this.owner.setLocalGrouping(this);c.ownerChanged.call(this,a,b);!this.owner&&this.autoDestroyWithNoOwner&&this.destroy()},map_:null,autoDestroyWithNoOwner:true,
autoDestroyEmptyGroups:true,titleGetter:e("data.title"),groupGetter:Function.$undef,childClass:p,childFactory:function(b){return new this.childClass(a(b,{titleGetter:this.titleGetter,autoDestroyIfEmpty:this.dataSource?false:this.autoDestroyEmptyGroups}))},init:function(a){this.map_={};this.nullGroup=new p({autoDestroyIfEmpty:false});j.prototype.init.call(this,a)},getGroupNode:function(a){var a=this.groupGetter(a),b=a instanceof n,c=this.map_[b?a.eventObjectId:a];!c&&!this.dataSource&&(c=this.appendChild(b?
{delegate:a}:{data:{id:a,title:a}}));return c||this.nullGroup},insertBefore:function(a,b){a=D.insertBefore.call(this,a,b);if("groupId_"in a==false)a.groupId_=a.delegate?a.delegate.eventObjectId:a.data.id,this.map_[a.groupId_]=a;if(a.first){var c=this.owner,d=c.childNodes,e=a.first,f=a.last,g,h,E;for(g=a;g=g.previousSibling;)if(E=g.last)break;if(!E)E=this.nullGroup.last;for(g=a;g=g.nextSibling;)if(h=g.first)break;if(e.previousSibling!==E||f.nextSibling!==h){if(e.previousSibling)e.previousSibling.nextSibling=
f.nextSibling;if(f.nextSibling)f.nextSibling.previousSibling=e.previousSibling;g=d.splice(d.indexOf(e),a.nodes.length);var i=d.indexOf(h);g.unshift(i!=-1?i:d.length,0);d.splice.apply(d,g);e.previousSibling=E;f.nextSibling=h;if(E)E.nextSibling=e;if(h)h.previousSibling=f;c.firstChild=d[0];c.lastChild=d[d.length-1]}}return a},removeChild:function(a){D.removeChild.call(this,a);delete this.map_[a.groupId_];return a},clear:function(){D.clear.call(this);this.map_={}},destroy:function(){this.setOwner();j.prototype.destroy.call(this);
this.map_=null}});j.prototype.localGroupingClass=H;var i=t(z,{autoDestroy:true,sourceNode:null,listen:{sourceNode:{childNodesModified:function(a,b){var c=this.memberMap_,d={},e=0,f=0,g=b.inserted,h=b.deleted;if(g&&g.length)for(d.inserted=g;a=g[e];)c[a.eventObjectId]=a,e++;if(h&&h.length)for(d.deleted=h;a=h[f];)delete c[a.eventObjectId],f++;(e||f)&&this.event_datasetChanged(this,d)},destroy:function(){this.autoDestroy?this.destroy():this.setSourceNode()}}},event_sourceNodeChanged:i("sourceNodeChanged")&&
function(a,b){c.sourceNodeChanged.call(this,a,b);!this.sourceNode&&this.autoDestroy&&this.destroy()},extendConstructor_:false,init:function(a,b){z.prototype.init.call(this,b);a&&this.setSourceNode(a)},setSourceNode:function(a){a instanceof j==false&&(a=null);if(a!==this.sourceNode){var b=this.sourceNode;b&&(b.removeHandler(this.listen.sourceNode,this),this.listen.sourceNode.childNodesModified.call(this,b,{deleted:b.childNodes}));a&&(a.addHandler(this.listen.sourceNode,this),this.listen.sourceNode.childNodesModified.call(this,
a,{inserted:a.childNodes}));this.sourceNode=a;this.event_sourceNodeChanged(this,b)}},destroy:function(){this.setSourceNode();z.prototype.destroy.call(this)}}),I=t(w,{multiple:false,event_datasetChanged:function(a,b){w.prototype.event_datasetChanged.call(this,a,b);if(b.inserted)for(var c=0,d;d=b.inserted[c];c++)if(!d.selected)d.selected=true,d.event_select();if(b.deleted)for(c=0;d=b.deleted[c];c++)if(d.selected)d.selected=false,d.event_unselect()},add:function(a){if(!this.multiple)if(this.itemCount)return this.set(a);
else a.splice(1);for(var b=[],c=0,d;d=a[c];c++)d.contextSelection==this&&d.selectable&&b.push(d);return w.prototype.add.call(this,b)},set:function(a){for(var b=[],c=0,d;d=a[c];c++)d.contextSelection==this&&d.selectable&&b.push(d);this.multiple||a.splice(1);return w.prototype.set.call(this,b)}});l.namespace("basis.dom.wrapper",o).extend({AbstractNode:j,InteractiveNode:r,Node:G,GroupingNode:H,PartitionNode:p,simpleTemplate:o,ChildNodesDataset:i,Selection:I})})(basis);
(function(l,q){function v(a,b){return B(b,true).getRule(a,true)}function A(a,b){var c=a.match(/^([^{]+)\{(.*)\}\s*$/);if(c){for(var d=c[1].trim().split(/\s*,\s*/),e=0;e<d.length;e++)this.addRule(d[e],c[2]||null,b++);return b-1}}function u(a,b){var c=s.createElement(!a?'STYLE[type="text/css"]':'LINK[type="text/css"][rel="{alt}stylesheet"][href={url}]'.format({alt:b?"alternate ":"",url:a.quote('"')}));s.tag(null,"HEAD")[0].appendChild(c);c=c.sheet||c.styleSheet;try{if(!c.cssRules)c.cssRules=c.rules}catch(d){}if(!c.insertRule)c.insertRule=
A;if(!c.deleteRule)c.deleteRule=c.removeRule;return c}function B(a,b){a||(a="DefaultGenericStyleSheet");d[a]||b&&(d[a]=new k(u()));return d[a]}function y(a,b,c,d){for(var d=d||{},b=b.qw(),e=0,g;g=b[e];e++)if(typeof h.style[g]!="undefined"){c&&(l.platformFeature["css-"+a]=g);f[a]={key:g,getter:d[g]};break}}function o(a,b){var c=f[a];if(a=c?c.key:a.replace(/^-ms-/,"ms-").camelize())return{key:a,value:c&&c.getter?c.getter(b):b}}function t(a,b,c){if(typeof a.setProperty=="function")return a.setProperty(b,
c);if(b=o(b,c))return a.style[b.key]=b.value}function x(a,b){for(var c in b)t(a,c,b[c]);return a}function i(a,b){return t(a,"display",typeof b=="string"?b:b?"":"none")}function r(a,b){return t(a,"visibility",b?"":"hidden")}function n(a){return H[a]||(H[a]=RegExp("\\s*\\b"+a+"\\b"))}function z(a,b){var c=(b?"g":"s")+a;return m[c]||(m[c]=RegExp((b?"":"\\s*")+"\\b"+a+".*\\b"))}var w=q.document,s=l.dom,g=l.dom.event,e=l.Class,a=/\s*!important/i,b=String("important"),c=1,d={},f={},h=s.createElement("DIV");
y("opacity","opacity MozOpacity KhtmlOpacity filter",true,{fitler:function(a){return"alpha(opacity:"+parseInt(a*100)+")"}});y("border-radius","borderRadius MozBorderRadius WebkitBorderRadius",true);y("float","cssFloat styleFloat");var k=e(null,{styleSheet:null,rules:null,init:function(a){this.styleSheet=a;this.rules=[];this.map_={}},getRule:function(a,b){if(!this.map_[a]&&b){for(var c=this.styleSheet,d=this.rules.length,e=c.insertRule(a+"{}",d),f=d;f<=e;f++)this.rules.push(new j(c.cssRules[f]));this.map_[a]=
d!=e?new p(this.rules.splice(d)):this.rules[d]}return this.map_[a]},deleteRule:function(a){var b=this.map_[a];if(b){for(var b=b.rules||[b],c=0;c<b.length;c++){var d=this.rules.indexOf(b[c]);this.stylesheet.deleteRule(d);this.rules.splice(d,1)}delete this.map_[a]}},destroy:function(){delete this.rules}}),j=e(null,{rule:null,selector:"",init:function(a){if(a)this.rule=a,this.selector=a.selectorText},setProperty:function(c,d){var e,f=!!a.test(d),g=this.rule.style;if(f||g.getPropertyPriority&&g.getPropertyPriority(c)==
b){if(d=d.replace(a,""),e=o(c,d)){var h=e.key;g.setProperty?(f||g.removeProperty(h),g.setProperty(h,e.value,f?b:"")):g.cssText=g.cssText.replace(RegExp(g[h]?h+"\\s*:\\s*"+g[h]+"(\\s*!"+b+")?\\s*;?":"^","i"),h+": "+e.value+(f?" !"+b:"")+";")}}else t(this.rule,c,d)},setStyle:function(a){Object.iterate(a,this.setProperty,this)},clear:function(){this.rule.style.cssText=""},destroy:function(){delete this.rule}}),p=e(null,{rules:null,init:function(a){this.rules=a},destroy:function(){delete this.rules}});
["setProperty","setStyle","clear"].forEach(function(a){p.prototype[a]=function(){for(var b,c=0;b=this.rules[c];c++)b[a].apply(b,arguments)}});var D={};["em","ex","px","%"].forEach(function(a){D[a=="%"?"percent":a]=function(b){return b==0||isNaN(b)?"0":b+a}});var G,H={},I=e(null,{init:function(a){this.element=a},toString:function(){return this.element.className},set:function(a){this.clear();a.qw().forEach(this.add,this)},replace:function(a,b,c){c=c||"";typeof a!="undefined"&&this.remove(c+a);typeof b!=
"undefined"&&this.add(c+b)},bool:function(a,b){b?this.add(a):this.remove(a)},clear:function(){this.element.className=""},contains:function(a){return!!this.element.className.match(n(a))},item:function(a){return this.element.className.qw()[a]},add:function(a){this.element.className.match(n(a))||(this.element.className+=" "+a)},remove:function(a){var b=this.element.className,a=b.replace(n(a),"");if(a!=b)this.element.className=a},toggle:function(a){var b=this.contains(a);b?this.remove(a):this.add(a);
return!b}}),m={},F=e(null,{delim:"-",init:function(a,b){this.classList=b;this.prefix=a+this.delim},add:function(a){this.classList.add(this.prefix+a)},remove:function(a){this.classList.remove(this.prefix+a)},items:function(){var a=this.classList.toString();if(a)return a.toString().match(z(this.prefix,true))},set:function(a){var b=this.items(),a=typeof a!="undefined"?this.prefix+a:"",c=this.classList;if(b)if(b.length==1){if(b[0]===a)return;c.remove(b[0])}else this.clear();a&&c.add(a)},clear:function(){this.items().forEach(this.classList.remove,
this.classList)}});q.DOMTokenList&&w.documentElement.classList?(e=I.prototype,Object.extend(q.DOMTokenList.prototype,{set:e.set,replace:e.replace,bool:e.bool,clear:function(){for(var a=this.length;a-- >0;)this.remove(this[a])},setPrefixToken:e.setPrefixToken}),G=function(a){return(typeof a=="string"?s.get(a):a).classList}):G=function(a){return new I(typeof a=="string"?s.get(a):a)};g.onLoad(function(){G(w.body).bool("opacity-not-support",!l.platformFeature["css-opacity"])});s.extend({setStyleProperty:t,
setStyle:x,display:i,show:function(a){return i(a,1)},hide:function(a){return i(a)},visibility:r,visible:function(a){return r(a,1)},invisible:function(a){return r(a)}});return l.namespace("basis.cssom").extend({setStyleProperty:t,setStyle:x,classList:function(a,b){return b?new F(b,G(a)):G(a)},uniqueRule:function(a){var b="genericRule-"+c++;a&&G(a).add(b);a=v("."+b);a.token=b;return a},cssRule:v,getStyleSheet:B,addStyleSheet:u,CssStyleSheetWrapper:k,CssRuleWrapper:j,CssRuleWrapperSet:p}).extend(D)})(basis,
this);
(function(){function l(g,e){var a={},b;if(g&&g.length)b=a.inserted=g;if(e&&e.length)b=a.deleted=e;if(b)return a}var q=basis.Class,v=Object.extend,A=Function.$self,u=Function.$true,B=Function.$false,y=basis.EventObject.createEvent,o=basis.data.SUBSCRIPTION,t=basis.data.DataObject,x=basis.data.KeyObjectMap,i=basis.data.AbstractDataset,r=basis.data.Dataset;o.add("SOURCE",{sourceChanged:function(g,e){this.remove(g,e);this.add(g,g.source)},sourcesChanged:function(g,e){var a;if(a=e.inserted)for(var b=a.length;b-- >
0;)this.add(g,a[b]);if(a=e.deleted)for(b=a.length;b-- >0;)this.remove(g,a[b])}},function(g,e){for(var a=e.sources||[e.source],b=0,c;c=a[b++];)g(e,c)});o.add("MINUEND",{operandsChanged:function(g,e){this.minuend!==e&&(this.remove(g,e),this.add(g,g.minuend))}},function(g,e){g(e,e.minuend)});o.add("SUBTRAHEND",{operandsChanged:function(g,e,a){this.subtrahend!==a&&(this.remove(g,a),this.add(g,g.subtrahend))}},function(g,e){g(e,e.subtrahend)});var n=q(i,{subscribeTo:o.SOURCE,event_sourcesChanged:y("sourcesChanged",
"dataset","delta"),sources:null,rule:function(g){return g>0},listen:{source:{datasetChanged:function(g,e){var a=this.memberMap_,b={},c,d;if(e.inserted)for(var f=0;c=e.inserted[f];f++)d=c.eventObjectId,a[d]?a[d].count++:a[d]={count:1,object:c},b[d]=a[d];if(e.deleted)for(f=0;c=e.deleted[f];f++)d=c.eventObjectId,b[d]=a[d],a[d].count--;this.applyRule(b)},destroy:function(g){this.removeSource(g)}}},init:function(g){i.prototype.init.call(this,g);g=this.sources;this.sources=[];g&&g.forEach(this.addSource,
this)},setRule:function(g){if(typeof g!="function")g=n.UNION;if(this.rule!==g)this.rule=g,this.applyRule()},applyRule:function(g){var e=this.memberMap_,a=this.rule,b=this.sources.length,c=[],d=[],f,h,i;g||(g=e);for(var j in g)f=e[j],h=b&&f.count&&a(f.count,b),h!=!!this.item_[j]&&(h?c:d).push(f.object),f.count==0&&delete e[j];(i=l(c,d))&&this.event_datasetChanged(this,i)},addSource:function(g){if(g instanceof i&&this.sources.add(g)){g.addHandler(this.listen.source,this);var e=this.memberMap_,a;for(a in g.item_)e[a]?
e[a].count++:e[a]={count:1,object:g.item_[a]};this.applyRule();this.event_sourcesChanged(this,{inserted:[g]});return true}},removeSource:function(g){if(this.sources.remove(g)){g.removeHandler(this.listen.source,this);var e=this.memberMap_,a;for(a in g.item_)e[a].count--;this.applyRule();this.event_sourcesChanged(this,{deleted:[g]});return true}},setSources:function(g){for(var e=Array.from(this.sources),a=0,b;b=g[a];a++)b instanceof i&&(e.remove(b)||this.addSource(b));e.forEach(this.removeSource,this)},
clear:function(){Array.from(this.sources).forEach(this.removeSource,this)},destroy:function(){i.prototype.destroy.call(this);this.sources=null}});n.UNION=n.prototype.rule;n.INTERSECTION=function(g,e){return g==e};n.DIFFERENCE=function(g){return g==1};n.MORE_THAN_ONE_INCLUDE=function(g,e){return e==1||g>1};n.AT_LEAST_ONE_EXCLUDE=function(g,e){return e==1||g<e};var z=function(g){return!this.has(g)},w=q(i,{subscribeTo:o.MINUEND+o.SUBTRAHEND,minuend:null,subtrahend:null,event_operandsChanged:y("operandsChanged",
"dataset","oldMinuend","oldSubtrahend"),listen:{minuend:{datasetChanged:function(g,e){if(this.subtrahend){var a=l(e.inserted&&e.inserted.filter(z,this.subtrahend),e.deleted&&e.deleted.filter(this.has,this));a&&this.event_datasetChanged(this,a)}},destroy:function(){this.setOperands(null,this.subtrahend)}},subtrahend:{datasetChanged:function(g,e){if(this.minuend){var a=l(e.deleted&&e.deleted.filter(z,this),e.inserted&&e.inserted.filter(this.has,this));a&&this.event_datasetChanged(this,a)}},destroy:function(){this.setOperands(this.minuend,
null)}}},init:function(g){i.prototype.init.call(this,g);var g=this.minuend,e=this.subtrahend;this.subtrahend=this.minuend=null;(g||e)&&this.setOperands(g,e)},setOperands:function(g,e){var a,b=false;g instanceof i==false&&(g=null);e instanceof i==false&&(e=null);var c=this.minuend,d=this.subtrahend;if(c!==g)b=true,c&&c.removeHandler(this.listen.minuend,this),(this.minuend=g)&&g.addHandler(this.listen.minuend,this);if(d!==e)b=true,d&&d.removeHandler(this.listen.subtrahend,this),(this.subtrahend=e)&&
e.addHandler(this.listen.subtrahend,this);if(!b)return false;this.event_operandsChanged(this,c,d);if(!g||!e)this.itemCount&&this.event_datasetChanged(this,a={deleted:this.getItems()});else{var b=[],c=[],f;for(f in this.item_)(!g.item_[f]||e.item_[f])&&b.push(this.item_[f]);for(f in g.item_)!this.item_[f]&&!e.item_[f]&&c.push(g.item_[f]);(a=l(c,b))&&this.event_datasetChanged(this,a)}return a},clear:function(){this.setOperands()}}),s=q(i,{subscribeTo:o.SOURCE,source:null,event_sourceChanged:y("sourceChanged",
"dataset","oldSource"),map:A,reduce:B,rule:B,addMemberRef:null,removeMemberRef:null,sourceMap_:null,listen:{sourceObject:{update:function(g){var e=this.map?this.map(g):g;if(e instanceof t==false||this.reduce(e))e=null;var a=this.sourceMap_[g.eventObjectId],b=a.member;if(b!=e){var c=this.memberMap_,d,f,h;a.member=e;if(b)a=b.eventObjectId,this.removeMemberRef&&this.removeMemberRef(b,g),--c[a]==0&&(delete c[a],h=[b]);if(e)b=e.eventObjectId,this.addMemberRef&&this.addMemberRef(e,g),c[b]?c[b]++:(c[b]=
1,f=[e]);(d=l(f,h))&&this.event_datasetChanged(this,d)}}},source:{datasetChanged:function(g,e){var a=this.sourceMap_,b=this.memberMap_,c=[],d=[],f,h,i;r.setAccumulateState(true);if(e.inserted)for(var j=0;f=e.inserted[j];j++){i=this.map?this.map(f):f;if(i instanceof t==false||this.reduce(i))i=null;f.addHandler(this.listen.sourceObject,this);a[f.eventObjectId]={sourceObject:f,member:i};if(i)h=i.eventObjectId,b[h]?b[h]++:(b[h]=1,c.push(i)),this.addMemberRef&&this.addMemberRef(i,f)}if(e.deleted)for(j=
0;f=e.deleted[j];j++)if(h=f.eventObjectId,i=a[h].member,f.removeHandler(this.listen.sourceObject,this),delete a[h],i)h=i.eventObjectId,--b[h]==0&&(delete b[h],d.push(i)),this.removeMemberRef&&this.removeMemberRef(i,f);r.setAccumulateState(false);(e=l(c,d))&&this.event_datasetChanged(this,e)},destroy:function(){this.setSource()}}},init:function(g){i.prototype.init.call(this,g);this.sourceMap_={};if(g=this.source)this.source=null,this.setSource(g)},setRule:function(g){typeof g!="function"&&(g=u);if(this.rule!==
g)return this.rule=g,this.applyRule()},setMap:function(g){typeof g!="function"&&(g=A);if(this.map!==g)return this.map=g,this.applyRule()},setSource:function(g){g instanceof i==false&&(g=null);if(this.source!==g){var e=this.source;e&&(e.removeHandler(this.listen.source,this),this.listen.source.datasetChanged.call(this,e,{deleted:e.getItems()}));if(this.source=g)g.addHandler(this.listen.source,this),this.listen.source.datasetChanged.call(this,g,{inserted:g.getItems()});this.event_sourceChanged(this,
e)}},applyRule:function(){var g=this.sourceMap_,e=this.memberMap_,a,b,c,d,f,h=[],i=[],j,n;for(n in g){f=g[n];d=f.sourceObject;a=f.member;b=this.map?this.map(d):d;if(b instanceof t==false||this.reduce(b))b=null;if(a!=b){f.member=b;if(a)c=a.eventObjectId,this.removeMemberRef&&this.removeMemberRef(a,d),e[c]--;if(b)a=b.eventObjectId,this.addMemberRef&&this.addMemberRef(b,d),a in e?e[a]++:(e[a]=1,h.push(b))}}for(c in this.item_)e[c]==0&&(delete e[c],i.push(this.item_[c]));(j=l(h,i))&&this.event_datasetChanged(this,
j);return j},clear:function(){this.setSource()},destroy:function(){i.prototype.destroy.call(this);this.sourceMap_=null}}),B=q(s,{reduce:function(g){return!this.rule(g)},rule:u}),q=q(s,{map:function(g){return this.keyMap.resolve(g)},rule:u,subsetClass:i,keyMap:null,addMemberRef:function(g,e){g.event_datasetChanged(g,{inserted:[e]})},removeMemberRef:function(g,e){g.event_datasetChanged(g,{deleted:[e]})},init:function(g){if(!this.keyMap||this.keyMap instanceof x==false)this.keyMap=new x(v({keyGetter:this.rule,
itemClass:this.subsetClass},this.keyMap));s.prototype.init.call(this,g)},getSubset:function(g,e){return this.keyMap.get(g,e)},destroy:function(){s.prototype.destroy.call(this);this.keyMap.destroy();this.keyMap=null}});basis.namespace("basis.data.dataset").extend({Merge:n,Subtract:w,MapReduce:s,Subset:B,Split:q})})(basis,this);
(function(l){function q(a){h[a]=h[a]||0;return a+h[a]++}function v(){var a=Array.from(arguments),b=a.pop();typeof b!="function"&&console.warn("Last argument for calculate field constructor must be a function");for(var c=[],d=[],e=0,f;e<a.length;e++)f=a[e].quote('"'),c.push(f+" in delta"),d.push("data["+f+"]");b=(new Function("calc","return function(delta, data, oldValue){"+(c.length?"if ("+c.join(" || ")+")":"")+"return calc("+d.join(", ")+");"+(c.length?"return oldValue;":"")+"}"))(b);b.args=a;b.isCalcField=
true;return b}function A(){return v.apply(null,Array.from(arguments).concat(function(){for(var a=[],b=arguments.length;b-- >0;){if(arguments[b]==null)return null;a.push(arguments[b])}return a.join("-")}))}var u=l.Class,B=l.Cleaner,y=Object.extend,o=Function.$self,t=Function.getter,x=l.data,i=l.EventObject,r=x.Dataset,n=x.dataset.Subset,z=x.dataset.Split,w=x.DataObject,s=x.STATE,g={},e={string:1,number:1},a=[],b=function(a){return isNaN(a)?null:Number(a)},c=function(a){return isNaN(a)?null:Number(a)},
d=function(a){return isNaN(a)?null:parseInt(a)},f=function(a){return a==null?null:String(a)},h={},k=l.Class(null,{init:function(a){var b=this.index={};this.normalize=a;this.valueWrapper=function(c,d){var e=a(c,d);return e!==d&&b[e]?d:e};this.calcWrapper=function(c,d){var e=a(c,d);if(e!==d&&b[e])throw"Duplicate value for index "+d+" => "+c;return e};B.add(this)},get:function(a,b){var c=this.index[a];if(c&&(!b||c instanceof b))return c},add:function(a,b){var c=this.index[a];if(b&&(!c||c===b))return this.index[a]=
b,true},remove:function(a,b){if(this.index[a]===b)return delete this.index[a],true},destroy:function(){this.index=null}}),x=function(a,b){return function(c){return a.prototype[b].call(this,c&&c.map(this.wrapper))}},j=function(a,b){return function(c){if(!this.name)this.name=q(b);a.prototype.init.call(this,c)}},p=function(a){return function(b,c){r.setAccumulateState(true);b=(b||[]).map(this.wrapper);r.setAccumulateState(false);return a.prototype.sync.call(this,b,c)}},D=u(r,{wrapper:Function.$self,init:j(r,
"EntitySet"),sync:p(r),set:x(r,"set"),add:x(r,"add"),remove:x(r,"remove"),destroy:function(){r.prototype.destroy.call(this);delete this.wrapper}}),G=u(D,{set:Function.$false,add:Function.$false,remove:Function.$false,clear:Function.$false}),H=u(n,{init:j(n,"EntityCollection"),sync:p(n)});H.sourceHandler=n.sourceHandler;var I=u(z,{subsetClass:G,init:j(z,"EntityGrouping"),sync:p(z),getSubset:function(a,b){var c=z.prototype.getSubset.call(this,a,b);if(c)c.wrapper=this.wrapper;return c}}),m=function(a){if(this instanceof
m){var b=new F(a||o);return function(a,c){return a!=null?(c instanceof D||(c=b.createEntitySet()),c.set(a instanceof r?a.getItems():Array.from(a)),c):null}}};m.className="basis.entity.EntitySetWrapper";var F=u(null,{init:function(a){this.wrapper=a},createEntitySet:function(){return new D({wrapper:this.wrapper,name:"Set of "+((this.wrapper.entityType||this.wrapper).name||"").quote("{")})}}),C=function(a){if(this instanceof C){var b=function(a,b){if(a!=null){if(a===b||a.entityType===c)return a;var h,
i=c.idField;if(e[typeof a]){if(!i)return;h=a;a={};a[i]=h}else if(c.compositeKey)h=c.compositeKey(a,a);else if(i)h=a[i];else if(g&&(b=c.singleton,!b))return c.singleton=new f(a);h!=null&&d&&(b=d.get(h,c.entityClass));b&&b.entityType===c?b.update(a):b=new f(a);return b}else return c.singleton},c=new N(a||{},b),d=c.index__,f=c.entityClass,g=c.isSingleton;y(b,{toString:function(){return this.typeName+"()"},entityType:c,type:b,typeName:c.name,index:d,reader:function(a){return c.reader(a)},get:function(a){return c.get(a)},
addField:function(a,b){c.addField(a,b)},all:c.all,createCollection:function(a,d,e){var f=c.collection_[a];return!f&&d?c.collection_[a]=new H({wrapper:b,source:e||c.all,rule:d}):f},getCollection:function(a){return c.collection_[a]},createGrouping:function(a,d,e){var f=c.grouping_[a];return!f&&d?c.grouping_[a]=new I({wrapper:b,source:e||c.all,rule:d}):f},getGrouping:function(a){return c.grouping_[a]},getSlot:function(a,b){return c.getSlot(a,b)}});return b}};C.className="basis.entity.EntityTypeWrapper";
var J=t("singleton"),K={};u(w,{});var N=u(null,{name:"UntitledEntityType",defaults:null,fields:null,extensible:false,index__:null,slot_:null,init:function(b,c){this.name=b.name||q(this.name);this.index__=b.index;this.idFields={};a.push(this);this.isSingleton=b.isSingleton;this.wrapper=c;this.all=new G(Object.extend(b.all||{},{wrapper:c}));this.slot_={};if(b.extensible)this.extensible=true;this.fields={};this.defaults={};this.aliases={};this.getters={};Object.iterate(b.fields,this.addField,this);b.constrains&&
b.constrains.forEach(function(a){this.addCalcField(null,a)},this);if(this.isSingleton)this.get=J;b.aliases&&Object.iterate(b.aliases,this.addAlias,this);this.collection_={};if(b.collections)for(var d in b.collections)this.collection_[d]=new H({name:d,wrapper:c,source:this.all,rule:b.collections[d]||Function.$true});this.grouping_={};if(b.groupings)for(d in b.groupings)this.grouping_[d]=new I({name:d,wrapper:c,source:this.all,rule:b.groupings[d]||Function.$true});this.entityClass=M(this,this.all,this.index__,
this.slot_,this.fields,this.defaults,this.getters).extend({entityType:this,type:c,typeName:this.name,getId:function(){return this.__id__}})},reader:function(a){var b={};if(e[typeof a])return this.idField?(b[this.idField]=a,b):null;if(!a||a==null)return null;for(var c in a){var d=c in this.aliases?this.aliases[c]:"";d&&d in this.fields&&(b[d]=this.fields[d].reader?this.fields[d].reader(a[c]):a[c])}return b},addAlias:function(a,b){b in this.fields&&a in this.aliases==false&&(this.aliases[a]=b)},addField:function(a,
e){if(!this.all.itemCount){this.aliases[a]=a;typeof e=="function"&&(e={type:e});if("type"in e&&typeof e.type!="function")e.type=o;var g=e.type||o;if([b,c,d,f].has(g))e.id=true;if(e.id){if(!this.index__)this.index__=new k(String);this.idFields[a]=true;this.idField||this.compositeKey?(this.idField=null,this.compositeKey=A.apply(null,Object.keys(this.idFields))):this.idField=a}e.calc?this.addCalcField(a,e.calc,void 0):this.fields[a]=g;this.defaults[a]="defValue"in e?e.defValue:g();this.getters["get_"+
a]=function(){return this.data[a]};K[a]||(K[a]={destroy:function(){this.set(a,null)}})}},addCalcField:function(a,b,c){if(!a||!this.fields[a]){if(!this.calcs)this.calcs=[];for(var d={args:b.args,wrapper:!c?b:function(a,d,e){return c(b(a,d,e))}},e=this.calcs.length,f=0,g=0;g<this.calcs.length;g++)b.args.has(this.calcs[g].key)&&(f=g+1);if(a){d.key=a;for(g=0;g<this.calcs.length;g++)if(this.calcs[g].args.has(a)){e=g;break}if(f>e)return;if(this.idField&&a==this.idField)this.compositeKey=b;this.fields[a]=
function(a,b){typeof console!="undefined"&&console.log("Calculate fields are readonly");return b}}else e=f;this.calcs.splice(Math.min(e,f),0,d)}},get:function(a){a=this.getId(a);if(a!=null)return this.index__.get(a,this.entityClass)},getId:function(a){if((this.idField||this.compositeKey)&&a!=null){if(e[typeof a])return a;if(a&&a.entityType===this)return a.__id__;if(a instanceof w)a=a.data;return this.compositeKey?this.compositeKey(a,a):a[this.idField]}},getSlot:function(a){var b=this.getId(a);if(b!=
null){var c=this.slot_[b];c||(e[typeof a]&&(c={},this.idField&&!this.compositeKey&&(c[this.idField]=a),a=c),c=this.slot_[b]=new w({delegate:this.get(b),data:a}));return c}}}),L=u(w,{init:i.prototype.init,event_rollbackUpdate:i.createEvent("rollbackUpdate")}),M=function(a,b,c,d,e,f,h){function j(b,c,d){var e=false,f=a.calcs,g=b.__id__,h=b.data;try{if(f)for(var i=0,n;n=f[i++];){var m=n.key;if(m){var o=h[m];h[m]=n.wrapper(c,h,h[m]);h[m]!==o&&(c[m]=o,e=true)}else n.wrapper(c,h)}if(a.compositeKey)b.__id__=
a.compositeKey(c,h,b.__id__);else if(l&&l in c)b.__id__=h[l];b.__id__!==g&&a.index__.calcWrapper(b.__id__)}catch(q){b.__id__=g;for(var p in c)b.data[p]=c[p];if(d)for(p in d)if(!b.modified)b.modified=d;e=false}b.__id__!==g&&k(b,g,b.__id__);return e}function k(a,b,e){b!=null&&(c.remove(b,a),d[b]&&d[b].setDelegate());e!=null&&(c.add(e,a),d[e]&&d[e].setDelegate(a))}var l=a.idField;return u(L,h,{canHaveDelegate:false,modified:null,isTarget:true,extendConstructor_:false,init:function(a){L.prototype.init.call(this);
this.fieldHandlers_={};this.data={};this.root=this;this.target=this;var c,d={},g;for(g in e)g in a?(d[g]=f[g],c=e[g](a[g])):c=f[g],c&&c!==this&&c instanceof i&&c.addHandler(K[g],this)&&(this.fieldHandlers_[g]=true),this.data[g]=c;j(this,d);b.event_datasetChanged(b,{inserted:[this]})},toString:function(){return"[object "+this.constructor.className+"("+this.entityType.name+")]"},get:function(a){return this.data[a]},set:function(b,c,d,f){var g=e[b];if(!g){if(!a.extensible)return;g=o}var h,k=this.modified,
c=g(c,this.data[b]),g=this.data[b];if(c!==g&&(!c||!g||c.constructor!==Date||g.constructor!==Date||+c!==+g))a:{h={};if(b!=l)if(d){if(!k)this.modified=k={};if(b in k===false)h.rollback={key:b,value:void 0},k[b]=g;else if(k[b]===c&&(h.rollback={key:b,value:c},delete k[b],!Object.keys(k).length))this.modified=null}else if(k&&b in k)if(k[b]!==c){h.rollback={key:b,value:k[b]};k[b]=c;break a}else return false;this.data[b]=c;this.fieldHandlers_[b]&&(g.removeHandler(K[b],this),this.fieldHandlers_[b]=false);
c&&c!==this&&c instanceof i&&c.addHandler(K[b],this)&&(this.fieldHandlers_[b]=true);h.key=b;h.value=g;h.delta={};h.delta[b]=g}else if(!d&&k&&b in k&&(h={rollback:{key:b,value:k[b]}},delete k[b],!Object.keys(k).length))this.modified=null;if(!f&&h){var d=h.key,b=h.delta||{},m;if(h.rollback)m={},m[h.rollback.key]=h.rollback.value;j(this,b,m)&&(d=true);if(d)this.event_update(this,b),h.delta=b;m&&this.event_rollbackUpdate(this,m)}return h||false},update:function(a,b){if(a){var c,d={},e,f={},g,h;for(h in a)if(g=
this.set(h,a[h],b,true)){if(g.key)c=true,d[g.key]=g.value;if(g.rollback)e=true,f[g.rollback.key]=g.rollback.value}j(this,d,f)&&(c=true);c&&this.event_update(this,d);e&&this.event_rollbackUpdate(this,f)}return c?d:false},reset:function(){this.update(f)},clear:function(){var a={},b;for(b in this.data)a[b]=void 0;return this.update(a)},commit:function(a){if(this.modified){var b=this.modified;this.modified=null}this.update(a);b&&this.event_rollbackUpdate(this,b)},rollback:function(){if(this.state!=s.PROCESSING){if(this.modified){var a=
this.modified;this.modified=null;this.update(a);this.event_rollbackUpdate(this,a)}this.setState(s.READY)}},destroy:function(){for(var a in this.fieldHandlers_)this.data[a].removeHandler(K[a],this);this.fieldHandlers_=g;this.__id__&&k(this,this.__id__,null);w.prototype.destroy.call(this);b.event_datasetChanged(b,{deleted:[this]});this.data=g;this.modified=null}})};l.namespace("basis.entity").extend({isEntity:function(a){return a&&a instanceof M},NumericId:b,NumberId:c,IntId:d,StringId:f,Index:k,CalculateField:v,
EntityType:C,Entity:M,BaseEntity:L,EntitySetType:m,EntitySet:D,ReadOnlyEntitySet:G,Collection:H,Grouping:I})})(basis);
