/*!
 * Basis javasript library 
 * http://code.google.com/p/basis-js/
 *
 * @license
 * GNU General Public License v2.0 <http://www.gnu.org/licenses/gpl-2.0.html>
 */

(function(k){function p(a,e){for(var j in e)a[j]=e[j];return a}function v(a,e){for(var j in e)!1==j in a&&(a[j]=e[j]);return a}function z(a){return null==a||void 0==a}function t(a){return a}function A(a){var e={};a.names=function(a){return Object.slice(e,"string"==typeof a?a.qw():a)};a.extend=function(a){v(e,a);p(this,a);return this};return a}function y(a,e){for(var j=a.split("."),b=k,c,f,h;j.length;)if(c=j.shift(),f=(f?f+".":"")+c,b[c]||(b[c]=A((!j.length?e:null)||function(){},f),h&&(h.namespaces_[f]=
b[c])),b=b[c],!h&&(h=b,!h.namespaces_))h.namespaces_={};return l[a]=b}p(Object,{extend:p,complete:v,keys:function(a){var e=[],b;for(b in a)e.push(b);return e},values:function(a){var e=[],b;for(b in a)e.push(a[b]);return e},slice:function(a,e){var b={};if(!e)return p(b,a);for(var d=0,c;c=e[d++];)c in a&&(b[c]=a[c]);return b},splice:function(a,e){var b={};if(!e)return p(b,a);for(var d=0,c;c=e[d++];)c in a&&(b[c]=a[c],delete a[c]);return b},iterate:function(a,e,b){var d=[],c;for(c in a)d.push(e.call(b,
c,a[c]));return d},coalesce:function(){for(var a=arguments,e=0;e<a.length;e++)if(null!=a[e])return a[e]}});var q=function(){},s=function(){var a=1,e={},b={};a++;return function(d,c){var f,h;if(!c){if(d.getter)return d.getter;if("function"==typeof d)return d}if("function"!=typeof d)b[d]?f=b[d]:(f=new Function("object","return object != null ? object."+d+" : object"),f.path=d,f.getterIdx_=a++,b[d]=f);else if(f=d,!f.getterIdx_)f.getterIdx_=a++;h=f.getterIdx_;var m=e[h];if(m)if("undefined"==typeof c){if(m.nmg)return m.nmg}else for(h=
0;h<m.length;h++){if(m[h].modificator===c)return m[h].getter}else m=e[h]=[];var n=!0;switch(c&&typeof c){case "string":h=function(a){return c.format(f(a))};break;case "function":h=function(a){return c(f(a))};break;case "object":n=!1;h=function(a){return c[f(a)]};break;default:h=f.path?f:function(a){return f(a)}}if(n&&(m.push({getter:h,modificator:c}),"undefined"==typeof c))m.nmg=h;return h.getter=h}}();p(Function,{$undefined:function(a){return void 0==a},$defined:function(a){return void 0!=a},$isNull:z,
$isNotNull:function(a){return null!=a&&void 0!=a},$isSame:function(a){return a===this},$isNotSame:function(a){return a!==this},$self:t,$const:function(a){return function(){return a}},$false:function(){return!1},$true:function(){return!0},$null:function(){return null},$undef:q,getter:s,def:function(a,e,b){b=b||z;return function(d){d=a(d);return b(d)?e:d}},wrapper:function(a){return function(e){var b={};b[a]=e;return b}},lazyInit:function(a,e){var b=0,d;return function(){b++||(d=a.apply(e||this,arguments));
return d}},lazyInitAndRun:function(a,e,b){var d=0,c;return function(){d++||(c=a.call(b||this));e.apply(c,arguments);return c}},runOnce:function(a,e){var b=0;return function(){if(!b++)return a.apply(e||this,arguments)}}});v(Function.prototype,{bind:function(a){var e=this,b=Array.from(arguments,1);return b.length?function(){return e.apply(a,b.concat.apply(b,arguments))}:function(){return e.apply(a,arguments)}}});v(Array,{isArray:function(a){return"[object Array]"===Object.prototype.toString.call(a)}});
p(Array,{from:function(a,e){if(null!=a){var b=a.length;if("undefined"==typeof b)return[a];e||(e=0);if(0<b-e){for(var d=[],c=0,f=e;f<b;)d[c++]=a[f++];return d}}return[]},create:function(a,e,b){for(var c=[],g="function"==typeof e,f=0;f<a;f++)c[f]=g?e.call(b,f,c):e;return c}});v(Array.prototype,{indexOf:function(a,e){e=parseInt(e)||0;if(0>e)return-1;for(;e<this.length;e++)if(this[e]===a)return e;return-1},lastIndexOf:function(a,e){for(var b=this.length,e=parseInt(e),e=isNaN(e)||e>=b?b-1:(e+b)%b;0<=e;e--)if(this[e]===
a)return e;return-1},forEach:function(a,e){for(var b=0,c=this.length;b<c;b++)b in this&&a.call(e,this[b],b,this)},every:function(a,e){for(var b=0,c=this.length;b<c;b++)if(b in this&&!a.call(e,this[b],b,this))return!1;return!0},some:function(a,e){for(var b=0,c=this.length;b<c;b++)if(b in this&&a.call(e,this[b],b,this))return!0;return!1},filter:function(a,e){for(var b=[],c=0,g=this.length;c<g;c++)c in this&&a.call(e,this[c],c,this)&&b.push(this[c]);return b},map:function(a,e){for(var b=[],c=0,g=this.length;c<
g;c++)c in this&&(b[c]=a.call(e,this[c],c,this));return b},reduce:function(a,b){var c=this.length,d=arguments.length;if(0==c&&1==d)throw new TypeError;var g,f=0;1<d&&(g=b,f=1);for(d=0;d<c;d++)d in this&&(g=f++?a.call(null,g,this[d],d,this):this[d]);return g}});p(Array.prototype,{flatten:function(){return this.concat.apply([],this)},repeat:function(a){return Array.create(parseInt(a)||0,this).flatten()},item:function(a){a=parseInt(a||0);return this[0<=a?a:this.length+a]},search:function(a,b,c){Array.lastSearchIndex=
-1;for(var b=Function.getter(b||t),c=parseInt(c)||0,d=this.length;c<d;c++)if(b(this[c])===a)return this[Array.lastSearchIndex=c]},lastSearch:function(a,b,c){Array.lastSearchIndex=-1;for(var b=Function.getter(b||t),d=this.length,c=isNaN(c)||null==c?d:parseInt(c),d=c>d?d:c;0<d--;)if(b(this[d])===a)return this[Array.lastSearchIndex=d]},binarySearchPos:function(a,b,c,d,g,f){if(!this.length)return d?-1:0;var b=Function.getter(b||t),c=!!c,h,g=isNaN(g)?0:g,m=isNaN(f)?this.length-1:f;do if(f=g+m>>1,h=b(this[f]),
c?a>h:a<h)m=f-1;else if(c?a<h:a>h)g=f+1;else return a==h?f:d?-1:0;while(g<=m);return d?-1:f+(h<a^c)},binarySearch:function(a,b){return this.binarySearchPos(a,b,!1,!0)},add:function(a){return-1==this.indexOf(a)&&!!this.push(a)},remove:function(a){a=this.indexOf(a);return-1!=a&&!!this.splice(a,1)},has:function(a){return-1!=this.indexOf(a)},merge:function(a){return this.reduce(p,a||{})},sortAsObject:function(a,b,c){a=Function.getter(a);c=c?-1:1;return this.map(function(b,e){return{i:e,v:a(b)}}).sort(b||
function(a,b){return c*(a.v>b.v||-(a.v<b.v)||(a.i>b.i?1:-1))}).map(function(a){return this[a.i]},this)},set:function(a){if(this!==a)this.length=0,this.push.apply(this,a);return this},clear:function(){this.length=0;return this}});if(![1,2].splice(1).length){var x=Array.prototype.splice;Array.prototype.splice=function(){var a=Array.from(arguments);if(2>a.length)a[1]=this.length;return x.apply(this,a)}}var i={"<":">","[":"]","(":")","{":"}","\u00ab":"\u00bb"};String.Entity={laquo:"\u00ab",raquo:"\u00bb",
nbsp:"\u00a0",quot:'"',quote:'"',copy:"\u00a9",shy:"\u00ad",para:"\u00b6",sect:"\u00a7",deg:"\u00b0",mdash:"\u2014",hellip:"\u2026"};v(String,{toLowerCase:function(a){return(""+a).toLowerCase()},toUpperCase:function(a){return(""+a).toUpperCase()},trim:function(a){return(""+a).trim()},trimLeft:function(a){return(""+a).trimLeft()},trimRight:function(a){return(""+a).trimRight()},isEmpty:function(a){return null==a||""==""+a},isNotEmpty:function(a){return null!=a&&""!=""+a}});v(String.prototype,{trimLeft:function(){return this.replace(/^\s+/,
"")},trimRight:function(){return this.replace(/\s+$/,"")},trim:function(){return this.trimLeft().trimRight()}});p(String.prototype,{toObject:function(a){try{return Function("return 0,"+this)()}catch(b){if(a)throw b;}},toArray:(new String("a"))[0]?function(){return Array.from(this)}:function(){for(var a=[],b=this.length,c=0;c<b;c++)a[c]=this.charAt(c);return a},repeat:function(a){return Array(parseInt(a)+1||0).join(this)},qw:function(){var a=this.trim();return a?a.split(/\s+/):[]},forRegExp:function(){return this.replace(/[\/\\\(\)\[\]\?\{\}\|\*\+\-\.\^\$]/g,
"\\$&")},format:function(a){for(var b={},c=0;c<arguments.length;c++)b[c]=arguments[c];"object"==typeof a&&p(b,a);return this.replace(/\{([a-z\d\_]+)(?::([\.0])(\d+)|:(\?))?\}/gi,function(a,c,j,h,m){a=c in b?b[c]:m?"":a;return j&&!isNaN(a)?(a=Number(a),"."==j?a.toFixed(h):a.lead(h)):a})},quote:function(a,b){var a=a||'"',b=b||i[a]||a,c=(1==a.length?a:"")+(1==b.length?b:"");return a+(c?this.replace(RegExp("["+c.forRegExp()+"]","g"),"\\$&"):this)+b},capitalize:function(){return this.charAt(0).toUpperCase()+
this.substr(1).toLowerCase()},camelize:function(){return this.replace(/-(.)/g,function(a,b){return b.toUpperCase()})},dasherize:function(){return this.replace(/[A-Z]/g,function(a){return"-"+a.toLowerCase()})}});String.format=String.prototype.format;if(11!="|||".split(/\|/).length+"|||".split(/(\|)/).length)String.prototype.split=function(a){if(""==a||a&&""==a.source)return this.toArray();var b=[],c=0,d;if(a instanceof RegExp)for(a.global||(a=RegExp(a.source,/\/([mi]*)$/.exec(a)[1]+"g"));d=a.exec(this);)d[0]=
this.substring(c,d.index),b.push.apply(b,d),c=a.lastIndex;else for(;-1!=(d=this.indexOf(a,c));)b.push(this.substring(c,d)),c=d+a.length;b.push(this.substr(c));return b};if("2"!="12".substr(-1)){var w=String.prototype.substr;String.prototype.substr=function(a,b){return w.call(this,0>a?Math.max(0,this.length+a):a,b)}}p(Number.prototype,{fit:function(a,b){return!isNaN(a)&&this<a?Number(a):!isNaN(b)&&this>b?Number(b):this},between:function(a,b){return!isNaN(this)&&this>=a&&this<=b},quote:function(a,b){return(this+
"").quote(a,b)},toHex:function(){return parseInt(this).toString(16).toUpperCase()},sign:function(){return 0>this?-1:+(0<this)},base:function(a){return!a||isNaN(a)?0:Math.floor(this/a)*a},lead:function(a,b){return(this+"").replace(/\d+/,function(c){return 1<(a-=c.length-1)?Array(a).join(b||0)+c:c})},group:function(a,b){return(this+"").replace(/\d+/,function(c){return c.replace(/\d/g,function(d,g){return!g+(c.length-g)%(a||3)?d:(b||" ")+d})})},format:function(a,b,c,d,g){a=this.toFixed(a);if(b||g)a=
a.replace(/(\d+)(\.?)/,function(a,c,d){return(b?Number(c).group(3,b):c)+(d?g||d:"")});c&&(a=a.replace(/^-?/,"$&"+(c||"")));return a+(d||"")}});v(Date,{now:function(){return+new Date}});1900>(new Date).getYear()&&p(Date.prototype,{getYear:function(){return this.getFullYear()-1900},setYear:function(a){return this.setFullYear(!isNaN(a)&&100>a?Number(a)+1900:a)}});var l={},r=function(){function a(a,b){for(var c=l[a],e=b?b.split(/\./):[];c&&e.length;)c=c[e.shift()];return c}var b=k.document?k.document.getElementsByTagName("SCRIPT"):
null,c=(b?b[b.length-1].src:module.filename).replace(/[^\/]+$/,""),d={},g;"function"==typeof require?g=function(a){return require(requirePath+a.replace(/\./g,"/"))}:(g=function(b,e){var m=b.match(/^([a-z][a-zA-Z0-9\_]*(\.[a-z][a-zA-Z0-9\_]*)*)?/)[0],n=b.substr(m.length?m.length+1:0),C=a(m,n),D=/^basis\./.test(m)?c:(location?location.href:"").replace(/[a-z0-9\-\_\.]+\.[a-z0-9]+$/,"");if(!l[m]||!C)if(/^https?:/.test(D)){if(d[b])throw"Attempt to load namespace, probably cycle require";d[b]=1;var D=D+
(e||"")+b.replace(/\./g,"/")+".js",H=new XMLHttpRequest;H.open("POST",D,!1);H.send(null);if(200==H.status){try{(new Function(H.responseText)).call(k)}catch(i){throw i;}g.sequence.push(b.replace(/\./g,"/")+".js")}else if(404==H.status&&n)r(m);else throw"!";}else throw"Path `"+b+"` can't be resolved";return C||a(m,n)},g.sequence=[]);return g}(),B=function(){function a(a){return"function"==typeof a&&a.basisClass_}var b=Function(),c=1,d={},g=function(){for(var a in{toString:1})return;return!0}();p(b,
{className:"basis.Class",extendConstructor_:!1,prototype:{constructor:null,init:Function(),toString:function(){return"[object "+(this.constructor||this).className+"]"},destroy:function(){for(var a in this)this[a]=null;this.destroy=q}},create:function(g){"function"!=typeof g&&(g=b);var n=Function();n.prototype=g.prototype;for(var n=new n,C={className:g.className+"._SubClass_",basisClass_:!0,superClass_:g,extendConstructor_:!!g.extendConstructor_,__extend__:function(c){return c&&("object"==typeof c||
"function"==typeof c&&!a(c))&&c!==d?b.create.call(null,o,c):c},extend:b.extend,subclass:function(){return b.create.apply(null,[o].concat(Array.from(arguments)))},prototype:n},f=arguments,h=1;h<f.length;h++)C.extend("function"==typeof f[h]&&!a(f[h])?f[h](g.prototype):f[h]);var i={},o=C.extendConstructor_?function(a,b){this.eventObjectId=c++;var o,E;for(E in a)o=this[E],this[E]=o&&o.__extend__?o.__extend__(a[E]):a[E];this.init(b||i)}:function(){this.eventObjectId=c++;this.init.apply(this,arguments)};
n.constructor=o;for(var E in n)n[E]===d&&(n[E]=o);p(o,C);return o},extend:function(a){var b=this.prototype;if(a.prototype)a=a.prototype;for(var c in a){var e=a[c],d=b[c];"className"==c||"extendConstructor_"==c?this[c]=e:b[c]=d&&d.__extend__?d.__extend__(e):e}if(g&&a[c="toString"]!==Object.prototype[c])b[c]=a[c];return this}});var f=function(a,b){return{__extend__:function(a){var c=Function();c.prototype=this;c=new c;b(c,a);return c}}.__extend__(a)},h=function(a){return f(a,p)};return y("basis.Class",
b.create).extend({SELF:d,BaseClass:b,create:b.create,isClass:a,CustomExtendProperty:f,ExtensibleProperty:h,NestedExtProperty:function(a){return f(a,function(a,b){for(var c in b){var e=a[c];a[c]=e&&e.__extend__?e.__extend__(b[c]):h(b[c])}})}})}(),u=function(){function a(a){var d=c[a];d||(d=c[a]=function(){var c=this.handlers_,n,d;if(c&&c.length)for(var c=b.call(c),j=c.length;0<j--;)n=c[j],d=n.handler[a],"function"==typeof d&&d.apply(n.thisObject,arguments)});return d}var b=Array.prototype.slice,c=
{},d,g=B(null,{handlers_:null,event_destroy:d=a("destroy","object"),listen:B.NestedExtProperty(),extendConstructor_:!0,init:function(){if(this.handler)(this.handlers_||(this.handlers_=[])).push({handler:this.handler,thisObject:this.handlerContext||this})},addHandler:function(a,b){var c=this.handlers_;if(!c)c=this.handlers_=[];b||(b=this);for(var e=c.length,d;0<e--;)if(d=c[e],d.handler===a&&d.thisObject===b)return!1;return!!c.push({handler:a,thisObject:b||this})},removeHandler:function(a,b){var c=
this.handlers_;if(c){b||(b=this);for(var e=c.length,d;0<e--;)if(d=c[e],d.handler===a&&d.thisObject===b)return!!c.splice(e,1);return!1}},destroy:function(){if(this.handlers_)d.call(this,this),this.handlers_=null}});g.createEvent=a;g.event=c;return g}(),b=function(){var a=[];return{add:function(b){null!=b&&a.push(b)},remove:function(b){a.remove(b)}}}();(function(){function a(a){if(b){if(a.source!=k||a.data!=c)return;basis.dom.event.kill(a)}d.length&&(a=d.shift(),delete g[a.key],a.fn())}var b="function"==
typeof addEventListener&&"function"==typeof postMessage,c="zeroTimeoutMessage",d=[],g={},f=1;b&&k.addEventListener("message",a,!0);var h=setTimeout;k.setTimeout=function(n,C){var D;C?D=h.call(k,n,C):(D={key:"z"+f++,fn:"function"==typeof n?n:new Function(n)},g[D.key]=D,d.push(D),b?postMessage(c,"*"):D.timer=h.call(k,a,0),D=D.key);return D};var m=clearTimeout;k.clearTimeout=function(a){if(/z\d+/.test(a)){var b=g[a];b&&(clearTimeout(b.timer),d.remove(b),delete g[a])}else return m.call(k,a)}})();var c=
function(){function a(){if(!C)if(f.length){var a=Date.now(),b=Math.max(f[0].eventTime,a);b<m&&(clearTimeout(n),n=setTimeout(j,(m=b)-a))}else n=clearTimeout(n),m=d}function c(b,e){var d=b.eventObjectId,o=h[e]&&h[e][d];o&&(f.remove(o),delete h[e][d],a())}function j(){var b=Date.now(),b=f.binarySearchPos(b+15,g);C=!0;f.splice(0,b).forEach(function(a){delete h[a.eventName][a.object.eventObjectId];a.callback.call(a.object)});C=!1;m=d;a()}var d=2E12,g=s("eventTime"),f=[],h={},m=d,n=null,C=!1;b.add({destroy:function(){C=
!0;clearTimeout(n);f.length=0;h=null}});return{add:function(b,d,n){var o=b.eventObjectId,E=h[d];E||(E=h[d]={});var G=E[o];if(G){if(isNaN(n))return c(b,d);if(G.eventTime==n)return;f.remove(G);G.eventTime=n}else{if(isNaN(n))return;G=E[o]={eventName:d,object:b,eventTime:n,callback:b[d]}}f.splice(f.binarySearchPos(n,g),0,G);a()},remove:c}}();y("basis").extend({namespace:y,platformFeature:{},EventObject:u,TimeEventManager:c,Cleaner:b,require:r});k.basis.locale={}})(this);
(function(k,p){function v(i){for(var b=1E6,i=(""+i).split("."),c=0,a=0;4>c&&c<i.length;c++,b/=100)a+=i[c]*b;return a}function z(){for(var i=0;i<arguments.length;i++){var b=arguments[i].toLowerCase();if(b in A){if(A[b])return!0}else{var c=b.match(/^([a-z]+)(([\d\.]+)([+-=]?))?$/i);if(c){A[b]=!1;var a=c[1].toLowerCase(),e=v(c[3]),c=c[4]||"=";if(a=y[a])return A[b]=!e||"="==c&&a==e||"+"==c&&a>=e||"-"==c&&a<e}}}return!1}var t="basis.ua",A={},y={},q=p.navigator&&p.navigator.userAgent,s="unknown",x={MSIE:["Internet Explorer",
"msie","ie"],Gecko:["Gecko","gecko"],Safari:["Safari","safari"],"iPhone OS":["iPhone","iphone"],AdobeAir:["AdobeAir","air"],AppleWebKit:["WebKit"],Chrome:["Chrome","chrome"],FireFox:["FireFox","firefox","ff"],Iceweasel:["FireFox","firefox","ff"],Shiretoko:["FireFox","firefox","ff"],Opera:["Opera","opera"]},i;for(i in x)if(!("MSIE"==i&&p.opera)&&!("Safari"==i&&q.match(/chrome/i))&&!("AppleWebKit"==i&&q.match(/iphone/i))&&q.match(RegExp(i+".(\\d+(\\.\\d+)*)","i")))for(var w=x[i],l=p.opera&&"function"==
typeof p.opera.version?p.opera.version():RegExp.$1,r=v(l),s=w[0]+" "+l,l=0;l<w.length;l++)y[w[l].toLowerCase()]=r;k.platformFeature.datauri=!1;q="undefined"!=typeof Image?new Image:{};q.onload=function(){k.platformFeature.datauri=!0};q.src="data:image/gif;base64,R0lGODlhAQABAIAAAP///wAAACH5BAEAAAAALAAAAAABAAEAAAICRAEAOw==";if(z("IE7-"))try{document.execCommand("BackgroundImageCache",!1,!0)}catch(B){}t=k.namespace(t);t.toString=function(){return s};return t.extend({testImage:q,prettyName:s,test:z,
is:function(i){return z(i)},Cookies:{set:function(i,b,c,a){document.cookie=i+"="+(null==b?"":escape(b))+";path="+(a||(0==location.pathname.indexOf("/")?"":"/")+location.pathname)+(c?";expires="+(new Date(Date.now()+1E3*c)).toGMTString():"")},get:function(i){return(i=document.cookie.match(RegExp("(^|;)\\s*"+i+"\\s*=\\s*(.*?)\\s*(;|$)")))&&unescape(i[2])},remove:function(i,b){document.cookie=i+"=;expires="+(new Date(0)).toGMTString()+";path="+(b||(0==location.pathname.indexOf("/")?"":"/")+location.pathname)}}})})(basis,
this);
(function(k,p){function v(a,b,c){if(null!=b)return a.insertBefore(j(b)?b:y(b),c||null)}function z(a){return s("",a.cloneNode(!0)).innerHTML}function t(a){return j(a)||a&&a.nodeType?a:"string"==typeof a?l.getElementById(a):null}function A(e,j,g){var f,h=[],g="string"==typeof g?getter(g):g||Function.$true;j&26&&g(e)&&h.push(e);switch(j){case 1:case 2:for(f=e;(f=f[u])&&f!==e.document;)g(f)&&h.push(f);break;case 64:for(f=e[b];f;)g(f)&&h.push(f),f=f[c];break;case 4:case 8:e[b]&&(j=new d(e),j.nodes(g,h));
break;case 128:j=new d(e,g);for(j.cursor_=e[c]||e[u];f=j.next();)h.push(f);break;case 256:for(f=e;f=f[c];)g(f)&&h.push(f);break;case 32:g(e[u])&&h.push(e[u]);break;case 512:j=new d(e,g,d.BACKWARD);for(j.cursor_=e[a]||e[u];f=j.next();)h.push(f);break;case 1024:for(f=e;f=f[a];)g(f)&&h.push(f)}return h}function y(a){return l.createTextNode(null!=a?a:"")}function q(){for(var a=l.createDocumentFragment(),b=arguments.length,c=q.array=[],e=0;e<b;e++)c.push(v(a,arguments[e]));return a}function s(a,b){var c=
void 0!=a&&"string"!=typeof a,e=(c?a.description:a)||"",d="div",o=e.match(/^([a-z0-9\_\-]+)(.*)$/i);o&&(d=o[1],e=o[2]);if(""!=e){for(var E=[],G={},j;o=m.exec(e);){if(o[8])throw Error("Create element error in basis.dom.createElement()\n\nDescription:\n> "+e+"\n\nProblem place:\n> "+e.substr(0,o.index)+"--\>"+e.substr(o.index)+"<--");j=o[1]||o[2]||o[3];o[1]?G.id=j:o[2]?E.push(j):"class"!=j&&(G[j]=o[4]?w(o[5],o[6],o[7]):j)}f&&G.name&&/^(input|textarea|select)$/i.test(d)&&(d="<"+d+" name="+G.name+">")}e=
l.createElement(d);if(G){if(G.style&&h)e.style.cssText=G.style;for(var g in G)e.setAttribute(g,G[g],0)}if(E&&E.length)e.className=E.join(" ");1<arguments.length&&v(e,q.apply(0,Array.from(arguments,1).flatten()));if(c&&(a.css&&k.cssom&&k.cssom.setStyle(e,a.css),k.dom.event))for(var i in a)"function"==typeof a[i]?k.dom.event.addHandler(e,i,a[i],e):a[i]instanceof k.dom.event.Handler&&k.dom.event.addHandler(e,i,a[i].handler,a[i].thisObject);return e}function x(a,b){return a[u]?a[u].replaceChild(b,a):
a}function i(a){if(l.selection){var b=l.selection.createRange();0!=b.compareEndPoints("StartToEnd",b)&&b.collapse(a);return b.getBookmark().charCodeAt(2)-2}}var w=Object.coalesce,l=p.document,r=k.Class,B=l.createElement("div"),u="parentNode",b="firstChild",c="nextSibling",a="previousSibling",e;e="function"==typeof B.compareDocumentPosition?function(a,b){return a.compareDocumentPosition(b)}:function(a,b){return a==b?0:a.document!=b.document?33:a.sourceIndex>b.sourceIndex?2|8*b.contains(childA):4|16*
a.contains(childB)};var j;if("undefined"!=typeof Node){if(j=function(a){return a instanceof Node},!Node.prototype.contains)Node.prototype.contains=function(a){return!!(this.compareDocumentPosition(a)&16)}}else j=function(a){return a&&a.ownerDocument===l};var d=r(null,{root_:null,cursor_:null,filter:Function.$true,init:function(a,b,c){this.setRoot(a);this.setDirection(c);if("function"==typeof b)this.filter=b},setDirection:function(e){Object.extend(this,e?{a:"lastChild",b:a,c:c,d:b}:{a:b,b:c,c:a,d:"lastChild"})},
setRoot:function(a){this.root_=a||l;this.reset()},reset:function(){this.cursor_=null},first:function(a){this.reset();return this.next(a)},last:function(a){this.reset();return this.prev(a)},nodes:function(a,b){var c;b||(b=[]);for(this.reset();c=this.next(a);)b.push(c);return b},next:function(a){var a=a||this.filter,b=this.cursor_||this.root_;do for(var c=b[this.a];!c;){if(b===this.root_)return this.cursor_=null;(c=b[this.b])||(b=b[u])}while(!a(b=c));return this.cursor_=b},prev:function(a){var a=a||
this.filter,b=this.cursor_,c=this.c,e=this.d;do{var d=b?b[c]:this.root_[e];if(d){for(;d[e];)d=d[e];b=d}else b&&(b=b[u]);if(!b||b===this.root_){b=null;break}}while(!a(b));return this.cursor_=b},destroy:function(){this.cursor_=this.root_=null}});d.BACKWARD=!0;var g="textContent innerText nodeValue".qw(),f=function(){var a=l.createElement("input");a.name="a";return!/name/.test(z(a))}(),h;B.setAttribute("style","color: red");h="red"!==B.style.color;var m=/#([a-z0-9\_\-\:]+)|\.([a-z0-9\_\-\:]+)|\[([a-z0-9\_\-:]+)(="((?:\\.|[^"])*)"|='((?:\\.|[^'])*)'|=((?:\\.|[^\]])*))?\s*\]|\s*(\S)/gi;
return k.namespace("basis.dom").extend({ELEMENT_NODE:1,ATTRIBUTE_NODE:2,TEXT_NODE:3,CDATA_SECTION_NODE:4,ENTITY_REFERENCE_NODE:5,ENTITY_NODE:6,PROCESSING_INSTRUCTION_NODE:7,COMMENT_NODE:8,DOCUMENT_TYPE_NODE:10,DOCUMENT_NODE:9,DOCUMENT_FRAGMENT_NODE:11,NOTATION_NODE:12,AXIS_ANCESTOR:1,AXIS_ANCESTOR_OR_SELF:2,AXIS_DESCENDANT:4,AXIS_DESCENDANT_OR_SELF:8,AXIS_SELF:16,AXIS_PARENT:32,AXIS_CHILD:64,AXIS_FOLLOWING:128,AXIS_FOLLOWING_SIBLING:256,AXIS_PRESCENDING:512,AXIS_PRESCENDING_SIBLING:1024,INSERT_BEGIN:"begin",
INSERT_END:"end",INSERT_BEFORE:"before",INSERT_AFTER:"after",TreeWalker:d,outerHTML:z,textContent:function(a){for(var b=0,c;c=g[b++];)if(null!=a[c])return a[c];return A(a,4,function(a){return 3==a.nodeType}).map(getter("nodeValue")).join("")},get:t,tag:function(a,b){a=t(a)||l;return"*"==b&&a.all?Array.from(a.all):Array.from(a.getElementsByTagName(b||"*"))},axis:A,findAncestor:function(a,b,c){for(;a&&a!==c;){if(b(a))return a;a=a.parentNode}},createElement:s,createText:y,createFragment:q,insert:function(a,
e,d,g){a=t(a);if(!a)throw Error("basis.dom.insert: destination node can't be null");switch(d){case void 0:case "end":g=null;break;case "begin":g=a[b];break;case "before":break;case "after":g=g[c];break;default:g=Number(d).between(0,a.childNodes.length)?a.childNodes[d]:null}d=!j(a);if(!e||!Array.isArray(e))d=d?e&&a.insertBefore(e,g):v(a,e,g);else if(d)for(var d=[],f=0,o=e.length;f<o;f++)d[f]=a.insertBefore(e[f],g);else a.insertBefore(q.apply(0,e),g),d=q.array;return d},remove:function(a){return a[u]?
a[u].removeChild(a):a},replace:x,swap:function(a,b){if(a===b||e(a,b)&25)return!1;x(a,B);x(b,a);x(B,b);return!0},clone:function(a,b){var c=a.cloneNode(!b);c.attachEvent&&A(c,8).forEach(Event.clearHandlers);return c},clear:function(a){for(a=t(a);a.lastChild;)a.removeChild(a.lastChild);return a},wrap:function(a,b,c){var e=[],c=Function.getter(c||Function.$self),d;for(d in b)for(var o=0;o<a.length;o++){var E=c(a[o]);e[o]=b[d](a[o],o,E)?s(d,E):a[o]}return e},setAttribute:function(a,b,c){null==c?a.removeAttribute(b):
a.setAttribute(b,c)},parentOf:function(a,b){return a.contains(b)},isInside:function(a,b){return a==b||b.contains(a)},focus:function(a,b){try{a=t(a),a.focus(),b&&a.select&&a.select()}catch(c){}},setSelectionRange:function(a,b,c){3>arguments.length&&(c=b);if(a.setSelectionRange)a.setSelectionRange(b,c);else if(a.createTextRange){var e=a.createTextRange();e.collapse(!0);e.moveStart("character",b);e.moveEnd("character",c-b);e.select()}},getSelectionStart:function(a){return"undefined"!=typeof a.selectionStart?
a.selectionStart:i(!0)},getSelectionEnd:function(a){return"undefined"!=typeof a.selectionEnd?a.selectionEnd:i(!1)}})})(basis,this);
(function(k,p){function v(a){return a||p.event}function z(a){return"string"==typeof a?w.get(a):a}function t(a){a=v(a);a.stopPropagation?a.stopPropagation():a.cancelBubble=!0}function A(a){a=v(a);a.preventDefault?a.preventDefault():a.returnValue=!1}function y(a){var b=Array.from(u[a.type]);if(b)for(var c=b.length;0<c--;){var d=b[c];d.handler.call(d.thisObject,a)}}function q(a,c,j,d){a=z(a);if(!a)throw Error("Event.addHandler: can't attach event listener to undefined");if("function"!=typeof j)throw Error("Event.addHandler: handler must be a function");
a[r]||(a[r]={});var g={handler:j,thisObject:d},f=a[r],h=f[c];if(h){for(a=0;c=h[a];a++)if(c.handler===j&&c.thisObject===d)return;h.push(g)}else h=f[c]=[g],h.fireEvent=function(a){a=v(a);if(b&&a&&"undefined"==typeof a.returnValue){y(a);if(!0===a.cancelBubble)return;if("undefined"==typeof a.returnValue)a.returnValue=!0}for(var c=0,e;e=h[c++];)e.handler.call(e.thisObject,a)},a.addEventListener?a.addEventListener(c,h.fireEvent,!1):a.attachEvent("on"+c,h.fireEvent)}function s(a,b,c,d){var a=z(a),g=a[r];
if(g&&(g=g[b]))for(var f=0,h;h=g[f];f++)if(h.handler===c&&h.thisObject===d){g.splice(f,1);g.length||x(a,b);break}}function x(a,b){var a=z(a),c=a[r];if(c)if("string"!=typeof b)for(b in c)x(a,b);else{var d=c[b];d&&(a.removeEventListener?a.removeEventListener(b,d.fireEvent,!1):a.detachEvent("on"+b,d.fireEvent),delete c[b])}}var i=p.document,w=k.dom,l=Function.$null,r="__basisEvents",B={mousewheel:["mousewheel","DOMMouseScroll"]},u={},b=!i.addEventListener,c=function(){function a(){b++||setTimeout(function(){for(var a=
0;a<c.length;a++)c[a].callback.call(c[a].thisObject)},10)}var b=!1,c=[];if(k.ua.is("ie7-"))(function(){var b="_"+Date.now();i.write('<script id="'+b+'" defer src="//:"><\/script>');z(b).onreadystatechange=function(){"complete"==this.readyState&&(w.remove(this),a())}})();else if(k.ua.is("safari525-"))var d=setInterval(function(){/loaded|complete/.test(i.readyState)&&(clearInterval(d),a())},15);else q(i,"DOMContentLoaded",a,!1);q(i,"load",a,!1);q(p,"load",a,!1);return function(a,d){b||c.push({callback:a,
thisObject:d})}}();return k.namespace("basis.dom.event",v).extend({KEY:{BACKSPACE:8,TAB:9,CTRL_ENTER:10,ENTER:13,SHIFT:16,CTRL:17,ALT:18,ESC:27,ESCAPE:27,SPACE:32,PAGEUP:33,PAGEDOWN:34,END:35,HOME:36,LEFT:37,UP:38,RIGHT:39,DOWN:40,INSERT:45,DELETE:46,F5:116},MOUSE_LEFT:{VALUE:1,BIT:1},MOUSE_RIGHT:{VALUE:3,BIT:2},MOUSE_MIDDLE:{VALUE:2,BIT:4},browserEvents:function(a){return B[a]||[a]},Handler:function(a,b){this.handler=a;this.thisObject=b},sender:function(a){a=v(a);return a.target||a.srcElement},cancelBubble:t,
cancelDefault:A,kill:function(a,b){(b=z(b))?q(b,a,Event.kill):(A(a),t(a))},key:function(a){a=v(a);return a.keyCode||a.which||0},charCode:function(a){a=v(a);return a.charCode||a.keyCode||0},mouseButton:function(a,b){a=v(a);return"number"==typeof a.which?a.which==b.VALUE:a.button&b.BIT},mouseX:function(a){a=v(a);return a.changedTouches?a.changedTouches[0].pageX:"pageX"in a?a.pageX:a.clientX+(i.documentElement.scrollLeft||i.body.scrollLeft)},mouseY:function(a){a=v(a);return a.changedTouches?a.changedTouches[0].pageY:
"pageY"in a?a.pageY:a.clientY+(i.documentElement.scrollTop||i.body.scrollTop)},wheelDelta:function(a){a=v(a);return"wheelDelta"in a?a.wheelDelta/120:"DOMMouseScroll"==a.type?-a.detail/3:0},addGlobalHandler:function(a,b,c){var d=u[a];if(d)for(a=d.length;0<a--;){var g=d[a];if(g.handler===b&&g.thisObject===c)return}else i.addEventListener?i.addEventListener(a,y,!0):q(i,a,l),d=u[a]=[];d.push({handler:b,thisObject:c})},removeGlobalHandler:function(a,b,c){var d=u[a];if(d)for(var g=0,f;f=d[g];g++)if(f.handler===
b&&f.thisObject===c){d.splice(g,1);d.length||(delete u[a],i.removeEventListener?i.removeEventListener(a,y,!0):s(i,a,l));break}},addHandler:q,addHandlers:function(a,b,c){var a=z(a),d;for(d in b)q(a,d,b[d],c)},removeHandler:s,clearHandlers:x,fireEvent:function(a,b){var a=z(a),c=a[r];c&&c[b]&&c[b].fireEvent()},onLoad:c,onUnload:function(a,b){q(p,"unload",a,b)}})})(basis,this);
(function(){function k(b,c,a){for(var e=1,j;c;)c&1&&(j=i[e],a&e?(b.addHandler(j.handler,j.context),j.action(j.context.add,b)):(b.removeHandler(j.handler,j.context),j.action(j.context.remove,b))),c>>=1,e<<=1}function p(b){return Array.isArray(b)?b.map(p):{data:b}}var v=basis.Class,z=basis.EventObject,t=Object.values,A=Function.$self,y=z.createEvent,q=z.event,s={},x=[],i={},w=1,l={NONE:0,MASK:0,regType:function(b,c,a){i[w]={handler:c,action:a,context:{add:function(a,c){if(c){var d=l[b]+"_"+a.eventObjectId;
if(!c.subscribers_)c.subscribers_={};if(!c.subscribers_[d]){var g=c.subscriberCount;c.subscribers_[d]=a;c.subscriberCount+=1;c.event_subscribersChanged(c,g)}}},remove:function(a,c){if(c){var d=l[b]+"_"+a.eventObjectId;if(c.subscribers_[d]){var g=c.subscriberCount;delete c.subscribers_[d];c.subscriberCount-=1;c.event_subscribersChanged(c,g)}}}}};l[b]=w;l.MASK|=w;w<<=1}};l.regType("DELEGATE",{delegateChanged:function(b,c){this.remove(b,c);this.add(b,b.delegate)}},function(b,c){b(c,c.delegate)});l.regType("TARGET",
{targetChanged:function(b,c){this.remove(b,c);this.add(b,b.target)}},function(b,c){b(c,c.target)});var r=v(z,{state:"ready",data:null,canHaveDelegate:!0,delegate:null,root:null,cascadeDestroy:!1,isTarget:!1,target:null,active:!1,subscribeTo:l.DELEGATE+l.TARGET,subscriberCount:0,subscribers_:null,event_update:y("update","object","delta"),event_stateChanged:y("stateChanged","object","oldState"),event_delegateChanged:y("delegateChanged","object","oldDelegate"),event_rootChanged:y("rootChanged","object",
"oldRoot"),event_targetChanged:y("targetChanged","object","oldTarget")&&function(b,c){var a=this.listen.target;a&&(c&&c.removeHandler(a,this),this.target&&this.target.addHandler(a,this));q.targetChanged.call(this,b,c)},event_subscribersChanged:y("subscribersChanged","object"),event_activeChanged:y("activeChanged","object"),listen:{delegate:{update:function(b,c){this.data=b.data;this.event_update(this,c)},stateChanged:function(b,c){this.state=b.state;this.event_stateChanged(this,c)},targetChanged:function(b,
c){this.target=b.target;this.event_targetChanged(this,c)},rootChanged:function(b,c){this.data=b.data;this.event_rootChanged(this,c)},destroy:function(){this.cascadeDestroy?this.destroy():this.setDelegate()}}},init:function(b){z.prototype.init.call(this,b);if(b=this.delegate)this.delegate=null,this.data=b.data,this.state=b.state,this.setDelegate(b);else{this.root=this;if(!this.data)this.data={};if(this.isTarget)this.target=this}this.active&&k(this,this.subscribeTo,l.MASK)},isConnected:function(b){if(b instanceof
r){for(;b&&b!==this&&b!==b.delegate;)b=b.delegate;return b===this}return!1},getRootDelegate:function(){for(var b=this;b.delegate&&b.delegate!==b;)b=b.delegate;return b},setDelegate:function(b){if(this.canHaveDelegate&&b&&b instanceof r){if(b.delegate&&this.isConnected(b))return!1}else b=null;if(this.delegate!==b){var c=this.state,a=this.data,e=this.delegate,j=this.target,d=this.root,g={};e&&e.removeHandler(this.listen.delegate,this);if(b){this.delegate=b;this.root=b.root;this.data=b.data;this.state=
b.state;this.target=b.target;b.addHandler(this.listen.delegate,this);for(var f in b.data)!1===f in a&&(g[f]=void 0);for(f in a)a[f]!==b.data[f]&&(g[f]=a[f])}else for(f in this.target=this.delegate=null,this.root=this,this.data={},a)this.data[f]=a[f];this.event_delegateChanged(this,e);this.root!==d&&this.event_rootChanged(this,d);this.target!==j&&this.event_targetChanged(this,j);if(b){for(f in g){this.event_update(this,g);break}c!==this.state&&(""+c!=this.state||c.data!==this.state.data)&&this.event_stateChanged(this,
c)}return!0}return!1},setState:function(b,c){var a=this.target||this.getRootDelegate();if(a!==this)return a.setState(b,c);return this.state!=""+b||this.state.data!=c?(a=this.state,this.state=Object(""+b),this.state.data=c,this.event_stateChanged(this,a),!0):!1},deprecate:function(){"processing"!=this.state&&this.setState("deprecated")},update:function(b){var c=this.target||this.getRootDelegate();if(c!==this)return c.update(b);if(b){var c={},a=0,e;for(e in b)this.data[e]!==b[e]&&(a++,c[e]=this.data[e],
this.data[e]=b[e]);if(a)return this.event_update(this,c),c}return!1},setActive:function(b){b=!!b;return this.active!=b?(this.active=b,this.event_activeChanged(this),k(this,this.subscribeTo,l.MASK*b),!0):!1},setSubscription:function(b){var b=b&l.MASK,c=this.subscribeTo^b;return c?(this.subscribeTo=b,this.active&&k(this,c,b),!0):!1},destroy:function(){this.active&&k(this,this.subscribeTo,0);this.delegate&&this.setDelegate();z.prototype.destroy.call(this);this.data=s;this.state="undefined";this.target=
this.root=null}}),A=v(null,{itemClass:r,keyGetter:A,map_:null,extendConstructor_:!0,init:function(){this.map_={};basis.Cleaner.add(this)},resolve:function(b){return this.get(this.keyGetter(b),b)},create:function(b){var c={};b instanceof r?c.delegate=b:c.data={id:b,title:b};return new this.itemClass(c)},get:function(b,c){var a=b instanceof r?b.eventObjectId:b,e=this.map_[a];!e&&c&&(e=this.map_[a]=this.create(b,c),e.addHandler({destroy:function(){delete this.map_[a]}},this));return e},destroy:function(){basis.Cleaner.remove(this);
for(var b=t(this.map_),c=0,a;a=b[c++];)a.destroy()}}),B=v(r,{state:"undefined",itemCount:0,item_:null,memberMap_:null,cache_:null,event_datasetChanged:y("datasetChanged","dataset","delta")&&function(b,c){var a,e=0,j=0,d;if(a=c.inserted)for(;d=a[e];)this.item_[d.eventObjectId]=d,e++;if(a=c.deleted)for(;d=a[j];)delete this.item_[d.eventObjectId],j++;this.itemCount+=e-j;this.cache_=null;q.datasetChanged.call(this,b,c)},init:function(b){r.prototype.init.call(this,b);this.memberMap_={};this.item_={}},
has:function(b){return!(!b||!this.item_[b.eventObjectId])},getItems:function(){if(!this.cache_)this.cache_=t(this.item_);return this.cache_},pick:function(){for(var b in this.item_)return this.item_[b];return null},top:function(b){var c=[];if(b)for(var a in this.item_)if(c.push(this.item_[a])>=b)break;return c},add:function(){},remove:function(){},set:function(){},sync:function(){},clear:function(){},destroy:function(){this.clear();r.prototype.destroy.call(this);this.cache_=x;this.itemCount=0;this.item_=
this.memberMap_=null}}),u=v(B,{listen:{item:{destroy:function(b){this.memberMap_[b.eventObjectId]&&this.remove([b])}}},init:function(b){B.prototype.init.call(this,b);if(b=this.items)this.set(b),this.items=null},add:function(b){for(var c,a=this.memberMap_,e=[],j=0;j<b.length;j++){var d=b[j];if(d instanceof r){var g=d.eventObjectId;a[g]||(a[g]=d,d.addHandler(this.listen.item,this),e.push(d))}}e.length&&this.event_datasetChanged(this,c={inserted:e});return c},remove:function(b){for(var c,a=this.memberMap_,
e=[],j=0;j<b.length;j++){var d=b[j];if(d instanceof r){var g=d.eventObjectId;a[g]&&(d.removeHandler(this.listen.item,this),delete a[g],e.push(d))}}e.length&&this.event_datasetChanged(this,c={deleted:e});return c},set:function(b){if(!this.itemCount)return this.add(b);if(!b.length)return this.clear();for(var c=this.memberMap_,a={},e=[],j=[],d,g,f,h=0;h<b.length;h++)if(d=b[h],d instanceof r)g=d.eventObjectId,a[g]=d,c[g]||(c[g]=d,d.addHandler(this.listen.item,this),j.push(d));for(g in c)a[g]||(d=c[g],
d.removeHandler(this.listen.item,this),delete c[g],e.push(d));var i;var b={},k;if(j&&j.length)k=b.inserted=j;if(e&&e.length)k=b.deleted=e;k&&(i=b);(f=i)&&this.event_datasetChanged(this,f);return f},sync:function(b,c){if(b){u.setAccumulateState(!0);for(var a=this.memberMap_,e,j,d={},g=[],f,h=0;h<b.length;h++)if(e=b[h],e instanceof r)j=e.eventObjectId,d[j]=e,a[j]||g.push(e);for(j in this.item_)d[j]||this.item_[j].destroy();c&&g.length&&(f=this.add(g));u.setAccumulateState(!1);return f}},clear:function(){var b,
c=this.getItems();if(c.length){for(b=c.length;0<b--;)c[b].removeHandler(this.listen.item,this);this.event_datasetChanged(this,b={deleted:c});this.memberMap_={}}return b}});u.setAccumulateState=function(){function b(a){var b=a.dataset;j.call(b,b,a)}function c(a,c){var e=a.eventObjectId,d=c.inserted,g=c.deleted,i=f[e];if(d&&g)return i&&(delete f[e],b(i)),j.call(a,a,c);if(i){var k=i[d?"inserted":"deleted"];if(k)return k.push.apply(k,d||g);b(i)}f[e]=c;c.dataset=a}function a(){d=1;setAccumulateState(!1)}
var e=B.prototype,j=e.event_datasetChanged,d=0,g,f={};return function(h){if(h){if(0==d)e.event_datasetChanged=c,g=setTimeout(a,0);d++}else if(d-=0<d,0==d)clearTimeout(g),e.event_datasetChanged=j,h=f,f={},t(h).forEach(b)}}();basis.namespace("basis.data",p).extend({STATE:{UNDEFINED:"undefined",READY:"ready",PROCESSING:"processing",ERROR:"error",DEPRECATED:"deprecated"},Subscription:l,Object:r,DataObject:r,KeyObjectMap:A,AbstractDataset:B,Dataset:u})})(basis,this);
(function(k,p){function v(a,c,d,g){for(var c=c.split(/\{([a-z0-9\_]+(?:\|[^}]*)?)\}/i),f=u(),h,i=0;i<c.length;i++)i%2?(h=c[i].split(/\|/),a.getters[h[0]]=d+"childNodes["+g+"]",h=1<h.length?h[1]:h[0]):h=c[i].length?c[i]:null,null!=h&&(B&&(f.lastChild&&f.appendChild(q.createComment("")),g++),f.appendChild(b(h)),g++);return f}function z(a){return function(b){if(!b||!("click"==b.type&&3==b.which)){var c=k.dom.event.sender(b),g,f;do if(g=c.getAttributeNode&&c.getAttributeNode(a))break;while(c=c.parentNode);
if(c&&g){do if(f=c.basisObjectId)if((f=w[f])&&f.templateAction){c=g.nodeValue.qw();g=0;for(var h;h=c[g++];)f.templateAction(h,k.dom.event(b));break}while(c=c.parentNode)}}}}function t(a,b,c){b=b.trim();if(!b)return"";for(var g="",f;f=r.exec(b);){var h=f[2],m=f[4]||f[5]||h;f[3]&&(a.getters[f[3]]=c+'.getAttributeNode("'+h+'")');if(f=h.match(/^event-([a-z]+)/i)){var l=f[1];if(!i[l]){i[l]=!0;f=0;for(var l=k.dom.event.browserEvents(l),p;p=l[f++];)k.dom.event.addGlobalHandler(p,z(h))}if(!window.__basis_emitEvent)window.__basis_emitEvent=
function(a,b){var a=k.dom.event(a),c=this,o;do if(o=c.basisObjectId)if((o=w[o])&&o.templateAction){for(var c=b.qw(),e=0,d;d=c[e++];)o.templateAction(d,k.dom.event(a));break}while(c=c.parentNode)}}g+="class"==h?m.trim().replace(/^(.)|\s+/g,".$1"):"["+h+(m?"="+m.quote('"'):"")+"]"}return g}function A(a,b){if(!a.stack)a.stack=[];if(!a.source)a.source=a.str;b||(b=".");for(var c=u(),g,f=0,h,i=a.stack;h=l.exec(a.str);){g=RegExp.leftContext;a.str=a.str.substr(g.length+h[0].length);if(g.length)c.appendChild(v(a,
g,b,f)),f=c.childNodes.length;if(h[5]){if(h[5]==i[i.length-1])return i.pop(),c;throw"Wrong end tag";}if(h[6])h[7]&&(a.getters[h[7]]=b+"childNodes["+f+"]"),c.appendChild(q.createComment(h[6]));else{g=h[1];var k=h[2],p=!!h[4],r=b+"childNodes["+f+"]";h=s.createElement(g+t(a,h[3],r));k&&(a.getters[k]=r);p||(i.push(g),h.appendChild(A(a,r+".")));c.appendChild(h)}f++}a.str.length&&c.appendChild(v(a,a.str,b,f));if(i.length)throw"No end tag for "+i.reverse();return c}function y(a){if(!this.proto){a=this.source;
if("function"==typeof a)this.source=a=a();for(var a=a.trim(),a={str:a,getters:{element:".childNodes[0]"}},b=A(a),a=Object.iterate(a.getters,function(a,c){for(var e=a.split(/\|/).map(String.format,"obj_.{0}"),d=c.split(/(\.?childNodes\[(\d+)\])/),g=b,f=0;f<d.length;f+=3){var o=d[f+2];if(!o)break;d[f+2]="";g=g.childNodes[o];g.previousSibling?g.nextSibling||(d[f+1]=".lastChild"):d[f+1]=".firstChild"}return{name:e[0],alias:e.join("="),path:"dom_"+d.join("")}}).sortAsObject("path"),c=0;c<a.length;c++)for(var g=
RegExp("^"+a[c].path.forRegExp()),f=c+1,h;h=a[f++];)h.path=h.path.replace(g,a[c].name);this.createInstance=(new Function("proto_","map_","var obj_, dom_; return "+function(a,b){obj_=a||{};dom_=proto_.cloneNode(!0);_code_();if(b&&obj_.element){var c=obj_.element.basisObjectId=map_.seed++;map_[c]=b}return obj_}.toString().replace("_code_()",a.map(String.format,"{alias}={path};\n").join(""))))(b,w);this.clearInstance=(new Function("map_","var obj_; return "+function(a){obj_=a;(a=obj_.element&&obj_.element.basisObjectId)&&
delete map_[a];_code_()}.toString().replace("_code_()",a.map(String.format,"{alias}=null;\n").join(""))))(w)}}var q=p.document,s=k.dom,x=k.Class,i={},w={seed:1},l=/<([a-z0-9\_]+)(?:\{([a-z0-9\_\|]+)\})?([^>]*?)(\/?)>|<\/([a-z0-9\_]+)>|<\!--(\s*\{([a-z0-9\_\|]+)\}\s*|.*?)--\>/i,r=/(?:([a-z0-9\_\-]+):)?([a-z0-9\_\-]+)(?:\{([a-z0-9\_\|]+)\})?(?:="((?:\\.|[^"])*?)"|='((?:\\.|[^'])*?)')?\s*/gi;s.createFragment();var B=1==s.createElement("","a","b").cloneNode(!0).childNodes.length,u=s.createFragment,b=
s.createText,c=x(null,{__extend__:function(a){return a instanceof c?a:new c(a)},init:function(a){this.source=a},createInstance:function(a,b){y.call(this);return this.createInstance(a,b)},clearInstance:function(){y.call(this)}}),a=q.createElement("DIV");return k.namespace("basis.html").extend({Template:c,escape:function(a){return s.createElement("DIV",s.createText(a)).innerHTML},unescape:function(b){a.innerHTML=b;return a.firstChild.nodeValue},string2Html:function(b){a.innerHTML=b;return s.createFragment.apply(null,
Array.from(a.childNodes))}})})(basis,this);
(function(k){function p(a){return a.sortingValue||0}function v(a,b){a=a.sortingValue||0;b=b.sortingValue||0;return+(a>b)||-(a<b)}function z(a,b){a=a.sortingValue||0;b=b.sortingValue||0;return-(a>b)||+(a<b)}function t(a){return a.childNodes.sort(a.localSortingDesc?z:v)}function A(a,b){var c=b.length-1;a.childNodes=b;a.firstChild=b[0]||null;a.lastChild=b[c]||null;for(var e=c;c=b[e];e--)c.nextSibling=b[e+1]||null,c.previousSibling=b[e-1]||null,a.insertBefore(c,c.nextSibling)}function y(a,b){var c=a.childFactory||
a.document&&a.document.childFactory,e,b=Object.extend({document:a.document,contextSelection:a.selection||a.contextSelection},b);if(c&&(e=c.call(a,b),e instanceof a.childClass))return e;if(!e)throw"basis.dom.wrapper: Child node is null";throw"basis.dom.wrapper: Child node has wrong class (expected "+(a.childClass&&a.childClass.className)+" but "+(e&&e.constructor&&e.constructor.className)+")";}function q(){return k.ui.apply(this,arguments)}var s=k.Class,x=k.dom,i=k.data,w=i.Subscription,l=i.DataObject,
r=i.AbstractDataset,B=i.Dataset,u=x.AXIS_DESCENDANT,b=x.AXIS_DESCENDANT_OR_SELF,c=Function.getter,a=Object.complete,e=x.axis,i=k.EventObject.createEvent,j=k.EventObject.event;w.regType("DATASOURCE",{dataSourceChanged:function(a,b){this.remove(a,b);this.add(a,a.dataSource)}},function(a,b){a(b,b.dataSource)});var d=s.ExtensibleProperty(),g={ownerChanged:function(){},destroy:function(a){x.replace(a.element,this)}},f=function(){var a=this.key,b=this.config,c=this.owner,e="function"!=typeof b.existsIf||
b.existsIf(c),d=c.satellite[a];if(e){var e="delegate"in b,f="dataSource"in b,h="function"==typeof b.delegate?b.delegate(c):null,j="function"==typeof b.dataSource?b.dataSource(c):null;if(d)e&&d.setDelegate(h),f&&d.setDataSource(j);else{var F=c.tmpl[b.replace||a],d={owner:c};if(e)d.delegate=h;if(f)d.dataSource=j;b.config&&Object.complete(d,"function"==typeof b.config?b.config(c):b.config);d=new b.instanceOf(d);c.satellite[a]=d;F&&d instanceof k.ui.Node&&d.element&&(x.replace(F,d.element),d.addHandler(g,
F))}}else if(d)d.destroy(),d.owner=null,delete c.satellite[a]},h=s.CustomExtendProperty({update:!0},function(a,b){for(var c in b)a[c]=b[c]?f:null}),m=s(l,{event_update:function(a,b){l.prototype.event_update.call(this,a,b);var c=this.parentNode;c&&(c.matchFunction&&(this.match(),this.match(c.matchFunction)),c.insertBefore(this,this.nextSibling))},event_childNodesModified:i("childNodesModified","node","delta"),event_dataSourceChanged:i("dataSourceChanged","node","oldDataSource"),event_localGroupingChanged:i("localGroupingChanged",
"node","oldGroupingNode"),event_localSortingChanged:i("localSortingChanged","node","oldLocalSorting","oldLocalSortingDesc"),event_ownerChanged:i("ownerChanged","node","oldOwner"),event_satellitesChanged:i("satellitesChanged","node","delta"),subscribeTo:l.prototype.subscribeTo+w.DATASOURCE,listen:{owner:{destroy:function(){this.setOwner()}}},autoDelegateParent:!1,nodeType:"DOMWrapperNode",canHaveChildren:!1,childNodes:null,dataSource:null,colMap_:null,destroyDataSourceMember:!0,document:null,parentNode:null,
nextSibling:null,previousSibling:null,firstChild:null,lastChild:null,localSorting:null,localSortingDesc:!1,localGrouping:null,localGroupingClass:null,groupNode:null,satelliteConfig:d,satellite:null,owner:null,init:function(a){var b=this.dataSource,c=this.childNodes,e=this.localGrouping;if(b)this.dataSource=null;l.prototype.init.call(this,a);if(e)this.localGrouping=null,this.setLocalGrouping(e);if(this.canHaveChildren)this.childNodes=[],b?(this.dataSource=null,this.setDataSource(b)):c&&this.setChildNodes(c);
else{if(c)this.childNodes=null;if(b)this.dataSource=null}if(!this.satellite)this.satellite={};if(this.satelliteConfig!==d)for(var g in this.satelliteConfig)if(a=this.satelliteConfig[g],s.isClass(a)&&(a={instanceOf:a}),"object"==typeof a){b={key:g,owner:this,config:a};a=a.hook?h.__extend__(a.hook):h;for(g in a)if(a[g]===f){this.addHandler(a,b);break}f.call(b)}if(g=this.owner)this.owner=null,this.setOwner(g)},appendChild:function(){},insertBefore:function(){},removeChild:function(){},replaceChild:function(){},
clear:function(){},hasChildNodes:function(){return 0<this.childNodes.length},setChildNodes:function(){},setLocalGrouping:function(){},setLocalSorting:function(){},setDataSource:function(){},setOwner:function(a){if(!a||!1==a instanceof m)a=null;if(this.owner!==a){var b=this.owner;b&&b.removeHandler(this.listen.owner,this);(this.owner=a)&&a.addHandler(this.listen.owner,this);this.event_ownerChanged(this,b)}},destroy:function(){l.prototype.destroy.call(this);this.dataSource?this.setDataSource():this.firstChild&&
this.clear();this.parentNode&&this.parentNode.removeChild(this);if(this.localGrouping)this.localGrouping.destroy(),this.localGrouping=null;this.owner&&this.setOwner();if(this.satellite){for(var a in this.satellite){var b=this.satellite[a];b.destroy();b.owner=null}this.satellite=null}this.lastChild=this.firstChild=this.nextSibling=this.previousSibling=this.parentNode=this.childNodes=this.document=null}}),n=s(m,{autoDestroyIfEmpty:!1,nodes:null,first:null,last:null,init:function(a){this.nodes=[];m.prototype.init.call(this,
a)},insert:function(a,b){var c=this.nodes,e=b?c.indexOf(b):-1;-1==e?(c.push(a),this.last=a):c.splice(e,0,a);this.first=c[0];a.groupNode=this;this.event_childNodesModified(this,{inserted:[a]})},remove:function(a){var b=this.nodes;if(b.remove(a))this.first=b[0]||null,this.last=b[b.length-1]||null,a.groupNode=null,this.event_childNodesModified(this,{deleted:[a]});!this.first&&this.autoDestroyIfEmpty&&this.destroy()},clear:function(){if(this.first){for(var a=this.nodes,b=a.length;0<b--;)a[b].groupNode=
null;this.nodes=[];this.last=this.first=null;this.event_childNodesModified(this,{deleted:a});this.autoDestroyIfEmpty&&this.destroy()}},destroy:function(){m.prototype.destroy.call(this);this.last=this.first=this.nodes=null}}),C={canHaveChildren:!0,childClass:m,childFactory:null,listen:{dataSource:{datasetChanged:function(a,b){var c={},e=[];if(b.deleted)if(c.deleted=e,this.childNodes.length==b.deleted.length){e.push.apply(e,this.childNodes);var d=this.dataSource;this.dataSource=null;this.clear(!0);
this.dataSource=d;this.colMap_={}}else for(var d=0,g;g=b.deleted[d];d++){g=g.eventObjectId;var f=this.colMap_[g];delete this.colMap_[g];f.canHaveDelegate=!0;this.removeChild(f);e.push(f)}if(b.inserted){c.inserted=[];for(d=0;g=b.inserted[d];d++)f=y(this,{cascadeDestroy:!1,delegate:g}),f.canHaveDelegate=!1,this.colMap_[g.eventObjectId]=f,c.inserted.push(f),this.firstChild&&this.insertBefore(f)}this.firstChild?this.event_childNodesModified(this,c):this.setChildNodes(c.inserted);if(this.destroyDataSourceMember&&
e.length)for(d=0;g=e[d];d++)g.destroy()},destroy:function(a){this.dataSource===a&&this.setDataSource()}}},appendChild:function(a){return this.insertBefore(a)},insertBefore:function(a,b){if(!this.canHaveChildren)throw"basis.dom.wrapper: Node can't be inserted at specified point in hierarchy";if(a.firstChild){var c=this;do if(c==a)throw"basis.dom.wrapper: Node can't be inserted at specified point in hierarchy";while(c=c.parentNode)}if(this.dataSource&&!this.dataSource.has(a.delegate))throw"basis.dom.wrapper: Operation is not allowed because node is under dataSource control";
!1==a instanceof this.childClass&&(a=y(this,a instanceof l?{delegate:a}:a));var d=a.parentNode===this,g=a.groupNode,f=this.localGrouping,h=this.localSorting,j,F=this.childNodes,i,I,k=null,c=-1,m=!1,n;if(d)n=a.nextSibling,I=a.previousSibling;if(h&&(b=null,j=this.localSortingDesc,i=h(a)||0,d))if(i===a.sortingValue)m=!0;else if((!n||(j?n.sortingValue<=i:n.sortingValue>=i))&&(!I||(j?I.sortingValue>=i:I.sortingValue<=i)))a.sortingValue=i,m=!0;if(f){k=f.getGroupNode(a);I=k.nodes;if(g===k&&(m||d&&n===b))return a;
h?m?c=n&&n.groupNode===k?I.indexOf(n):I.length:(c=I.binarySearchPos(i,p,j),a.sortingValue=i):c=b&&b.groupNode===k?I.indexOf(b):I.length;if(c<I.length)b=I[c];else if(k.last)b=k.last.nextSibling;else{c=k;for(b=null;(c=c.nextSibling)&&!(b=c.first););}if(a===b||d&&a.nextSibling===b)return g!==k&&(g&&g.remove(a),k.insert(a)),a;c=-1}else if(h){if(m)return a;c=F.binarySearchPos(i,p,j);b=F[c];a.sortingValue=i;if(a===b||d&&n===b)return a}else{if(b&&b.parentNode!==this)throw"basis.dom.wrapper: Node was not found";
if(d){if(n===b)return a;if(a===b)throw"basis.dom.wrapper: Node can't be inserted at specified point in hierarchy";}}d?(a.nextSibling?a.nextSibling.previousSibling=a.previousSibling:this.lastChild=a.previousSibling,a.previousSibling?a.previousSibling.nextSibling=a.nextSibling:this.firstChild=a.nextSibling,a.previousSibling=null,a.nextSibling=null,-1==c?F.remove(a):(j=F.indexOf(a),F.splice(j,1),j<c&&c--),g&&(g.remove(a),g=null)):a.parentNode&&a.parentNode.removeChild(a);g!=k&&k.insert(a,b);if(b){-1==
c&&(c=F.indexOf(b));if(-1==c)throw"basis.dom.wrapper: Node was not found";a.nextSibling=b;F.splice(c,0,a)}else c=F.length,F.push(a),b={previousSibling:this.lastChild},this.lastChild=a;a.parentNode=this;a.previousSibling=b.previousSibling;0==c?this.firstChild=a:b.previousSibling.nextSibling=a;b.previousSibling=a;var q=!1,r=!1,s=this.selection||this.contextSelection;if(!a.document&&a.document!==this.document)q=this.document,a.document=this.document;if(!a.contextSelection&&a.contextSelection!==s)a.contextSelection=
s,r=!a.selection,a.selected&&s.add([a]);a.firstChild&&(q||r)&&e(a,u).forEach(function(a){if(q&&!a.document)a.document=q;if(r&&!a.contextSelection)a.selected&&a.unselect(),a.contextSelection=s});d||(a.match&&a.match(this.matchFunction),a.autoDelegateParent&&a.setDelegate(this),this.dataSource||this.event_childNodesModified(this,{inserted:[a]}));return a},removeChild:function(a){if(null==a||a.parentNode!==this)throw"basis.dom.wrapper: Node was not found";if(!1==a instanceof this.childClass)throw"basis.dom.wrapper: Child node has wrong class";
if(this.dataSource&&this.dataSource.has(a))throw"basis.dom.wrapper: Operation is not allowed because node is under dataSource control";this.childNodes.splice(this.childNodes.indexOf(a),1);a.parentNode=null;a.nextSibling?a.nextSibling.previousSibling=a.previousSibling:this.lastChild=a.previousSibling;a.previousSibling?a.previousSibling.nextSibling=a.nextSibling:this.firstChild=a.nextSibling;a.nextSibling=null;a.previousSibling=null;a.document===this.document&&e(a,b).forEach(function(a){if(a.document==
this.document)a.document=null},this);if(a.contextSelection){for(var c=a.contextSelection,d=a,g=[];d;){if(d.contextSelection===c)d.selected&&g.push(d),d.contextSelection=null;if(!d.selection&&d.firstChild)d=d.firstChild;else if(d.nextSibling)d=d.nextSibling;else for(;d=d.parentNode;)if(d.nextSibling){d=d.nextSibling;break}}c.remove(g)}a.groupNode&&a.groupNode.remove(a);this.dataSource||this.event_childNodesModified(this,{deleted:[a]});a.autoDelegateParent&&a.setDelegate();return a},replaceChild:function(a,
b){if(this.dataSource)throw"basis.dom.wrapper: Operation is not allowed because node is under dataSource control";if(null==b||b.parentNode!==this)throw"basis.dom.wrapper: Node was not found";this.insertBefore(a,b);return this.removeChild(b)},clear:function(a){if(this.dataSource)this.setDataSource();else if(this.firstChild){var b=this.childNodes;this.lastChild=this.firstChild=null;this.childNodes=[];this.event_childNodesModified(this,{deleted:b});for(var c=b.length;0<c--;){var d=b[c];d.parentNode=
null;d.groupNode=null;a?((d.selection||d.document)&&e(d,x.AXIS_DESCENDANT_OR_SELF).forEach(function(a){if(this.selection&&a.selection===this.selection)a.selected&&a.selection.remove([a]),a.selection=null;if(a.document===this.document)a.document=null},this),d.nextSibling=null,d.previousSibling=null,d.autoDelegateParent&&d.setDelegate()):d.destroy()}if(this.localGrouping){a=this.localGrouping.childNodes;for(c=a.length-1;b=a[c];c--)b.clear()}}},setChildNodes:function(a,b){this.dataSource||this.clear(!!b);
if(a&&(!1=="length"in a&&(a=[a]),a.length)){var c=this.event_childNodesModified;this.event_childNodesModified=Function.$undef;for(var d=0,e=a.length;d<e;d++)this.insertBefore(a[d]);this.event_childNodesModified=c;this.event_childNodesModified(this,{inserted:this.childNodes})}},setDataSource:function(a){if(!a||!this.canHaveChildren||!1==a instanceof r)a=null;if(this.dataSource!==a){var b=this.dataSource;if(b)this.colMap_=this.dataSource=null,b.removeHandler(this.listen.dataSource,this),b.itemCount&&
this.clear();if(a)this.dataSource=a,this.colMap_={},a.addHandler(this.listen.dataSource,this),a.itemCount&&this.listen.dataSource.datasetChanged.call(this,a,{inserted:a.getItems()});this.event_dataSourceChanged(this,b)}},setLocalGrouping:function(a){if("function"==typeof a||"string"==typeof a)a={groupGetter:c(a)};!1==a instanceof H&&(a=null!=a&&"object"==typeof a?new this.localGroupingClass(Object.complete({},a)):null);if(this.localGrouping!==a){var b=this.localGrouping,d;if(this.localGrouping){if(!a&&
(this.localGrouping=null,this.firstChild)){d=this.localSorting?t(this):this.childNodes;for(var e=d.length;0<e--;)d[e].groupNode=null;A(this,d)}b.setOwner()}if(a&&(this.localGrouping=a,a.setOwner(this),this.firstChild)){d=this.localSorting?t(this):this.childNodes;for(e=0;a=d[e];e++)a.groupNode=this.localGrouping.getGroupNode(a);for(e=0;a=d[e];e++)a.groupNode.nodes.push(a);d.length=0;for(e=this.localGrouping.nullGroup;e;e=e.nextSibling)a=e.nodes,e.first=a[0]||null,e.last=a[a.length-1]||null,d.push.apply(d,
a),e.event_childNodesModified(e,{inserted:a});A(this,d)}this.event_localGroupingChanged(this,b)}},setLocalSorting:function(a,b){a&&(a=c(a));if(this.localSorting!=a||this.localSortingDesc!=!!b){var d=this.localSorting,e=this.localSortingDesc;this.localSortingDesc=!!b;this.localSorting=a||null;if(a&&this.firstChild){var g=[],f;for(f=this.firstChild;f;f=f.nextSibling)f.sortingValue=a(f)||0;if(this.localGrouping)for(var h=this.localGrouping.nullGroup;h;h=h.nextSibling)f=h.nodes=t({childNodes:h.nodes,
localSortingDesc:this.localSortingDesc}),h.first=f[0]||null,h.last=f[f.length-1]||null,g.push.apply(g,f);else g=t(this);A(this,g)}this.event_localSortingChanged(this,d,e)}},setMatchFunction:function(a){if(this.matchFunction!=a){this.matchFunction=a;for(var b=this.lastChild;b;b=b.previousSibling)b.match(a)}}},w=s(m,{event_enable:i("enable","node"),event_disable:i("disable","node"),event_select:i("select","node"),event_unselect:i("unselect","node"),event_match:i("match","node"),event_unmatch:i("unmatch",
"node"),selectable:!0,selected:!1,selection:null,contextSelection:null,matchFunction:null,matched:!0,disabled:!1,init:function(a){if(this.selection&&!1==this.selection instanceof r)this.selection=new J(this.selection);m.prototype.init.call(this,a);this.disabled&&this.event_disable(this);if(this.selected)this.selected=!1,this.select(!0)},setSelection:function(a){if(this.selection==a)return!1;var b=this.selection;e(this,u,function(c){if(c.contextSelection==b)c.selected&&b&&b.remove([c]),c.contextSelection=
a});this.selection=a;return!0},hasOwnSelection:function(){return!!this.selection},select:function(a){var b=this.selected,c=this.contextSelection;if(c)a?b?c.remove([this]):c.add([this]):this.selectable&&c.set([this]);else if(!b&&this.selectable&&!this.isDisabled())this.selected=!0,this.event_select(this);return this.selected!=b},unselect:function(){var a=this.selected;if(a){var b=this.contextSelection;b?b.remove([this]):(this.selected=!1,this.event_unselect(this))}return this.selected!=a},enable:function(){if(this.disabled)this.disabled=
!1,this.event_enable(this)},disable:function(){if(!this.disabled)this.disabled=!0,this.event_disable(this)},isDisabled:function(){return this.disabled||this.document&&this.document.disabled||!!x.findAncestor(this,c("disabled"))},match:function(a){if("function"!=typeof a)if(this.matched){if(this.underMatch_)this.underMatch_(this,!0),this.underMatch_=null}else this.matched=!0,this.event_match(this);else if(a(this)){if(this.underMatch_=a,!this.matched)this.matched=!0,this.event_match(this)}else if(this.underMatch_=
null,this.matched)this.matched=!1,this.event_unmatch(this)},setMatchFunction:function(){},destroy:function(){this.hasOwnSelection()&&(this.selection.destroy(),delete this.selection);this.unselect();m.prototype.destroy.call(this)}}),D=s(w,C,{}),H=s(m,C,{event_childNodesModified:function(a,b){j.childNodesModified.call(this,a,b);this.nullGroup.nextSibling=this.firstChild;if(b.inserted&&this.dataSource&&this.nullGroup.first)for(var c=this.owner,d=Array.from(this.nullGroup.nodes),e=d.length;0<e--;)c.insertBefore(d[e],
d[e].nextSibling)},event_ownerChanged:function(a,b){b&&b.localGrouping===this&&b.setLocalGrouping(null,!0);this.owner&&this.owner.localGrouping!==this&&this.owner.setLocalGrouping(this);j.ownerChanged.call(this,a,b);!this.owner&&this.autoDestroyWithNoOwner&&this.destroy()},map_:null,autoDestroyWithNoOwner:!0,autoDestroyEmptyGroups:!0,titleGetter:c("data.title"),groupGetter:Function.$undef,childClass:n,childFactory:function(b){return new this.childClass(a(b,{titleGetter:this.titleGetter,autoDestroyIfEmpty:this.dataSource?
!1:this.autoDestroyEmptyGroups}))},init:function(a){this.map_={};this.nullGroup=new n({autoDestroyIfEmpty:!1});m.prototype.init.call(this,a)},getGroupNode:function(a){var a=this.groupGetter(a),b=a instanceof l,c=this.map_[b?a.eventObjectId:a];!c&&!this.dataSource&&(c=this.appendChild(b?{delegate:a}:{data:{id:a,title:a}}));return c||this.nullGroup},insertBefore:function(a,b){a=C.insertBefore.call(this,a,b);if(!1=="groupId_"in a)a.groupId_=a.delegate?a.delegate.eventObjectId:a.data.id,this.map_[a.groupId_]=
a;if(a.first){var c=this.owner,d=c.childNodes,e=a.first,g=a.last,f,h,F;for(f=a;(f=f.previousSibling)&&!(F=f.last););if(!F)F=this.nullGroup.last;for(f=a;(f=f.nextSibling)&&!(h=f.first););if(e.previousSibling!==F||g.nextSibling!==h){if(e.previousSibling)e.previousSibling.nextSibling=g.nextSibling;if(g.nextSibling)g.nextSibling.previousSibling=e.previousSibling;f=d.splice(d.indexOf(e),a.nodes.length);var j=d.indexOf(h);f.unshift(-1!=j?j:d.length,0);d.splice.apply(d,f);e.previousSibling=F;g.nextSibling=
h;if(F)F.nextSibling=e;if(h)h.previousSibling=g;c.firstChild=d[0];c.lastChild=d[d.length-1]}}return a},removeChild:function(a){C.removeChild.call(this,a);delete this.map_[a.groupId_];return a},clear:function(){C.clear.call(this);this.map_={}},destroy:function(){this.setOwner();m.prototype.destroy.call(this);this.map_=null}});m.prototype.localGroupingClass=H;var i=s(r,{autoDestroy:!0,sourceNode:null,listen:{sourceNode:{childNodesModified:function(a,b){var c=this.memberMap_,d={},e=0,g=0,f=b.inserted,
h=b.deleted;if(f&&f.length)for(d.inserted=f;a=f[e];)c[a.eventObjectId]=a,e++;if(h&&h.length)for(d.deleted=h;a=h[g];)delete c[a.eventObjectId],g++;(e||g)&&this.event_datasetChanged(this,d)},destroy:function(){this.autoDestroy?this.destroy():this.setSourceNode()}}},event_sourceNodeChanged:i("sourceNodeChanged")&&function(a,b){j.sourceNodeChanged.call(this,a,b);!this.sourceNode&&this.autoDestroy&&this.destroy()},extendConstructor_:!1,init:function(a,b){r.prototype.init.call(this,b);a&&this.setSourceNode(a)},
setSourceNode:function(a){!1==a instanceof m&&(a=null);if(a!==this.sourceNode){var b=this.sourceNode;b&&(b.removeHandler(this.listen.sourceNode,this),this.listen.sourceNode.childNodesModified.call(this,b,{deleted:b.childNodes}));a&&(a.addHandler(this.listen.sourceNode,this),this.listen.sourceNode.childNodesModified.call(this,a,{inserted:a.childNodes}));this.sourceNode=a;this.event_sourceNodeChanged(this,b)}},destroy:function(){this.setSourceNode();r.prototype.destroy.call(this)}}),J=s(B,{multiple:!1,
event_datasetChanged:function(a,b){B.prototype.event_datasetChanged.call(this,a,b);if(b.inserted)for(var c=0,d;d=b.inserted[c];c++)if(!d.selected)d.selected=!0,d.event_select();if(b.deleted)for(c=0;d=b.deleted[c];c++)if(d.selected)d.selected=!1,d.event_unselect()},add:function(a){if(!this.multiple){if(this.itemCount)return this.set(a);a.splice(1)}for(var b=[],c=0,d;d=a[c];c++)d.contextSelection==this&&d.selectable&&b.push(d);return B.prototype.add.call(this,b)},set:function(a){for(var b=[],c=0,d;d=
a[c];c++)d.contextSelection==this&&d.selectable&&b.push(d);this.multiple||a.splice(1);return B.prototype.set.call(this,b)}});k.namespace("basis.dom.wrapper",q).extend({AbstractNode:m,InteractiveNode:w,Node:D,GroupingNode:H,PartitionNode:n,simpleTemplate:q,ChildNodesDataset:i,Selection:J})})(basis);
(function(k,p){function v(a,b){return A(b,!0).getRule(a,!0)}function z(a,b){var c=a.match(/^([^{]+)\{(.*)\}\s*$/);if(c){for(var d=c[1].trim().split(/\s*,\s*/),e=0;e<d.length;e++)this.addRule(d[e],c[2]||null,b++);return b-1}}function t(a,b){var c=u.createElement(!a?'STYLE[type="text/css"]':'LINK[type="text/css"][rel="{alt}stylesheet"][href={url}]'.format({alt:b?"alternate ":"",url:a.quote('"')}));u.tag(null,"HEAD")[0].appendChild(c);c=c.sheet||c.styleSheet;try{if(!c.cssRules)c.cssRules=c.rules}catch(d){}if(!c.insertRule)c.insertRule=
z;if(!c.deleteRule)c.deleteRule=c.removeRule;return c}function A(a,b){a||(a="DefaultGenericStyleSheet");j[a]||b&&(j[a]=new f(t()));return j[a]}function y(a,b,c,e){for(var e=e||{},b=b.qw(),f=0,h;h=b[f];f++)if("undefined"!=typeof g.style[h]){c&&(k.platformFeature["css-"+a]=h);d[a]={key:h,getter:e[h]};break}}function q(a,b){var c=d[a];if(a=c?c.key:a.replace(/^-ms-/,"ms-").camelize())return{key:a,value:c&&c.getter?c.getter(b):b}}function s(a,b,c){if("function"==typeof a.setProperty)return a.setProperty(b,
c);if(b=q(b,c))return a.style[b.key]=b.value}function x(a,b){for(var c in b)s(a,c,b[c]);return a}function i(a,b){return s(a,"display","string"==typeof b?b:b?"":"none")}function w(a,b){return s(a,"visibility",b?"":"hidden")}function l(a){return D[a]||(D[a]=RegExp("\\s*\\b"+a+"\\b"))}function r(a,b){var c=(b?"g":"s")+a;return J[c]||(J[c]=RegExp((b?"":"\\s*")+"\\b"+a+".*\\b"))}var B=p.document,u=k.dom,b=k.dom.event,c=k.Class,a=/\s*!important/i,e=1,j={},d={},g=u.createElement("DIV");y("opacity","opacity MozOpacity KhtmlOpacity filter",
!0,{fitler:function(a){return"alpha(opacity:"+parseInt(100*a)+")"}});y("border-radius","borderRadius MozBorderRadius WebkitBorderRadius",!0);y("float","cssFloat styleFloat");var f=c(null,{styleSheet:null,rules:null,init:function(a){this.styleSheet=a;this.rules=[];this.map_={}},getRule:function(a,b){if(!this.map_[a]&&b){for(var c=this.styleSheet,d=this.rules.length,e=c.insertRule(a+"{}",d),g=d;g<=e;g++)this.rules.push(new h(c.cssRules[g]));this.map_[a]=d!=e?new m(this.rules.splice(d)):this.rules[d]}return this.map_[a]},
deleteRule:function(a){var b=this.map_[a];if(b){for(var b=b.rules||[b],c=0;c<b.length;c++){var d=this.rules.indexOf(b[c]);this.stylesheet.deleteRule(d);this.rules.splice(d,1)}delete this.map_[a]}},destroy:function(){delete this.rules}}),h=c(null,{rule:null,selector:"",init:function(a){if(a)this.rule=a,this.selector=a.selectorText},setProperty:function(b,c){var d,e=!!a.test(c),g=this.rule.style;if(e||g.getPropertyPriority&&"important"==g.getPropertyPriority(b)){if(c=c.replace(a,""),d=q(b,c)){var f=
d.key;g.setProperty?(e||g.removeProperty(f),g.setProperty(f,d.value,e?"important":"")):g.cssText=g.cssText.replace(RegExp(g[f]?f+"\\s*:\\s*"+g[f]+"(\\s*!important)?\\s*;?":"^","i"),f+": "+d.value+(e?" !important":"")+";")}}else s(this.rule,b,c)},setStyle:function(a){Object.iterate(a,this.setProperty,this)},clear:function(){this.rule.style.cssText=""},destroy:function(){delete this.rule}}),m=c(null,{rules:null,init:function(a){this.rules=a},destroy:function(){delete this.rules}});["setProperty","setStyle",
"clear"].forEach(function(a){m.prototype[a]=function(){for(var b,c=0;b=this.rules[c];c++)b[a].apply(b,arguments)}});var n={};["em","ex","px","%"].forEach(function(a){n["%"==a?"percent":a]=function(b){return 0==b||isNaN(b)?"0":b+a}});var C,D={},H=c(null,{init:function(a){this.element=a},toString:function(){return this.element.className},set:function(a){this.clear();a.qw().forEach(this.add,this)},replace:function(a,b,c){c=c||"";"undefined"!=typeof a&&this.remove(c+a);"undefined"!=typeof b&&this.add(c+
b)},bool:function(a,b){b?this.add(a):this.remove(a)},clear:function(){this.element.className=""},contains:function(a){return!!this.element.className.match(l(a))},item:function(a){return this.element.className.qw()[a]},add:function(a){this.element.className.match(l(a))||(this.element.className+=" "+a)},remove:function(a){var b=this.element.className,a=b.replace(l(a),"");if(a!=b)this.element.className=a},toggle:function(a){var b=this.contains(a);b?this.remove(a):this.add(a);return!b}}),J={},o=c(null,
{delim:"-",init:function(a,b){this.classList=b;this.prefix=a+this.delim},add:function(a){this.classList.add(this.prefix+a)},remove:function(a){this.classList.remove(this.prefix+a)},items:function(){var a=this.classList.toString();if(a)return a.toString().match(r(this.prefix,!0))},set:function(a){var b=this.items(),a="undefined"!=typeof a?this.prefix+a:"",c=this.classList;if(b)if(1==b.length){if(b[0]===a)return;c.remove(b[0])}else this.clear();a&&c.add(a)},clear:function(){this.items().forEach(this.classList.remove,
this.classList)}});p.DOMTokenList&&B.documentElement.classList?(c=H.prototype,Object.extend(p.DOMTokenList.prototype,{set:c.set,replace:c.replace,bool:c.bool,clear:function(){for(var a=this.length;0<a--;)this.remove(this[a])},setPrefixToken:c.setPrefixToken}),C=function(a){return("string"==typeof a?u.get(a):a).classList}):C=function(a){return new H("string"==typeof a?u.get(a):a)};b.onLoad(function(){C(B.body).bool("opacity-not-support",!k.platformFeature["css-opacity"])});u.extend({setStyleProperty:s,
setStyle:x,display:i,show:function(a){return i(a,1)},hide:function(a){return i(a)},visibility:w,visible:function(a){return w(a,1)},invisible:function(a){return w(a)}});return k.namespace("basis.cssom").extend({setStyleProperty:s,setStyle:x,classList:function(a,b){return b?new o(b,C(a)):C(a)},uniqueRule:function(a){var b="genericRule-"+e++;a&&C(a).add(b);a=v("."+b);a.token=b;return a},cssRule:v,getStyleSheet:A,addStyleSheet:t,CssStyleSheetWrapper:f,CssRuleWrapper:h,CssRuleWrapperSet:m}).extend(n)})(basis,
this);
(function(){function k(b,c){var a={},e;if(b&&b.length)e=a.inserted=b;if(c&&c.length)e=a.deleted=c;if(e)return a}var p=basis.Class,v=Object.extend,z=Function.$self,t=Function.$true,A=Function.$false,y=basis.EventObject.createEvent,q=basis.data.Subscription,s=basis.data.DataObject,x=basis.data.KeyObjectMap,i=basis.data.AbstractDataset,w=basis.data.Dataset;Subscription.regType("SOURCE",{sourceChanged:function(b,c){this.remove(b,c);this.add(b,b.source)},sourcesChanged:function(b,c){var a;if(a=c.inserted)for(var e=a.length;0<
e--;)this.add(b,a[e]);if(a=c.deleted)for(e=a.length;0<e--;)this.remove(b,a[e])}},function(b,c){for(var a=c.sources||[c.source],e=0,j;j=a[e++];)b(c,j)});var l=p(i,{subscribeTo:q.SOURCE,event_sourcesChanged:y("sourcesChanged","dataset","delta"),sources:null,rule:function(b){return 0<b},listen:{source:{datasetChanged:function(b,c){var a=this.memberMap_,e={},j,d;if(c.inserted)for(var g=0;j=c.inserted[g];g++)d=j.eventObjectId,a[d]?a[d].count++:a[d]={count:1,object:j},e[d]=a[d];if(c.deleted)for(g=0;j=c.deleted[g];g++)d=
j.eventObjectId,e[d]=a[d],a[d].count--;this.applyRule(e)},destroy:function(b){this.removeSource(b)}}},init:function(b){i.prototype.init.call(this,b);b=this.sources;this.sources=[];b&&b.forEach(this.addSource,this)},setRule:function(b){if("function"!=typeof b)b=l.UNION;if(this.rule!==b)this.rule=b,this.applyRule()},applyRule:function(b){var c=this.memberMap_,a=this.rule,e=this.sources.length,j=[],d=[],g,f,h;b||(b=c);for(var i in b)g=c[i],f=e&&g.count&&a(g.count,e),f!=!!this.item_[i]&&(f?j:d).push(g.object),
0==g.count&&delete c[i];(h=k(j,d))&&this.event_datasetChanged(this,h)},addSource:function(b){if(b instanceof i&&this.sources.add(b)){b.addHandler(this.listen.source,this);var c=this.memberMap_,a;for(a in b.item_)c[a]?c[a].count++:c[a]={count:1,object:b.item_[a]};this.applyRule();this.event_sourcesChanged(this,{inserted:[b]});return!0}},removeSource:function(b){if(this.sources.remove(b)){b.removeHandler(this.listen.source,this);var c=this.memberMap_,a;for(a in b.item_)c[a].count--;this.applyRule();
this.event_sourcesChanged(this,{deleted:[b]});return!0}},setSources:function(b){for(var c=Array.from(this.sources),a=0,e;e=b[a];a++)e instanceof i&&(c.remove(e)||this.addSource(e));c.forEach(this.removeSource,this)},clear:function(){Array.from(this.sources).forEach(this.removeSource,this)},destroy:function(){i.prototype.destroy.call(this);this.sources=null}});l.UNION=l.prototype.rule;l.INTERSECTION=function(b,c){return b==c};l.DIFFERENCE=function(b){return 1==b};l.MORE_THAN_ONE_INCLUDE=function(b,
c){return 1==c||1<b};l.AT_LEAST_ONE_EXCLUDE=function(b,c){return 1==c||b<c};var r=function(b){return!this.has(b)};q.regType("MINUEND",{operandsChanged:function(b,c){this.minuend!==c&&(this.remove(b,c),this.add(b,b.minuend))}},function(b,c){b(c,c.minuend)});q.regType("SUBTRAHEND",{operandsChanged:function(b,c,a){this.subtrahend!==a&&(this.remove(b,a),this.add(b,b.subtrahend))}},function(b,c){b(c,c.subtrahend)});var B=p(i,{subscribeTo:q.MINUEND+q.SUBTRAHEND,minuend:null,subtrahend:null,event_operandsChanged:y("operandsChanged",
"dataset","oldMinuend","oldSubtrahend"),listen:{minuend:{datasetChanged:function(b,c){if(this.subtrahend){var a=k(c.inserted&&c.inserted.filter(r,this.subtrahend),c.deleted&&c.deleted.filter(this.has,this));a&&this.event_datasetChanged(this,a)}},destroy:function(){this.setOperands(null,this.subtrahend)}},subtrahend:{datasetChanged:function(b,c){if(this.minuend){var a=k(c.deleted&&c.deleted.filter(r,this),c.inserted&&c.inserted.filter(this.has,this));a&&this.event_datasetChanged(this,a)}},destroy:function(){this.setOperands(this.minuend,
null)}}},init:function(b){i.prototype.init.call(this,b);var b=this.minuend,c=this.subtrahend;this.subtrahend=this.minuend=null;(b||c)&&this.setOperands(b,c)},setOperands:function(b,c){var a,e=!1;!1==b instanceof i&&(b=null);!1==c instanceof i&&(c=null);var j=this.minuend,d=this.subtrahend;if(j!==b)e=!0,j&&j.removeHandler(this.listen.minuend,this),(this.minuend=b)&&b.addHandler(this.listen.minuend,this);if(d!==c)e=!0,d&&d.removeHandler(this.listen.subtrahend,this),(this.subtrahend=c)&&c.addHandler(this.listen.subtrahend,
this);if(!e)return!1;this.event_operandsChanged(this,j,d);if(!b||!c)this.itemCount&&this.event_datasetChanged(this,a={deleted:this.getItems()});else{var e=[],j=[],g;for(g in this.item_)(!b.item_[g]||c.item_[g])&&e.push(this.item_[g]);for(g in b.item_)!this.item_[g]&&!c.item_[g]&&j.push(b.item_[g]);(a=k(j,e))&&this.event_datasetChanged(this,a)}return a},clear:function(){this.setOperands()}}),u=p(i,{subscribeTo:q.SOURCE,source:null,event_sourceChanged:y("sourceChanged","dataset","oldSource"),map:z,
reduce:A,rule:A,addMemberRef:null,removeMemberRef:null,sourceMap_:null,listen:{sourceObject:{update:function(b){var c=this.map?this.map(b):b;if(!1==c instanceof s||this.reduce(c))c=null;var a=this.sourceMap_[b.eventObjectId],e=a.member;if(e!=c){var j=this.memberMap_,d,g,f;a.member=c;if(e)a=e.eventObjectId,this.removeMemberRef&&this.removeMemberRef(e,b),0==--j[a]&&(delete j[a],f=[e]);if(c)e=c.eventObjectId,this.addMemberRef&&this.addMemberRef(c,b),j[e]?j[e]++:(j[e]=1,g=[c]);(d=k(g,f))&&this.event_datasetChanged(this,
d)}}},source:{datasetChanged:function(b,c){var a=this.sourceMap_,e=this.memberMap_,j=[],d=[],g,f,h;w.setAccumulateState(!0);if(c.inserted)for(var i=0;g=c.inserted[i];i++){h=this.map?this.map(g):g;if(!1==h instanceof s||this.reduce(h))h=null;g.addHandler(this.listen.sourceObject,this);a[g.eventObjectId]={sourceObject:g,member:h};if(h)f=h.eventObjectId,e[f]?e[f]++:(e[f]=1,j.push(h)),this.addMemberRef&&this.addMemberRef(h,g)}if(c.deleted)for(i=0;g=c.deleted[i];i++)if(f=g.eventObjectId,h=a[f].member,
g.removeHandler(this.listen.sourceObject,this),delete a[f],h)f=h.eventObjectId,0==--e[f]&&(delete e[f],d.push(h)),this.removeMemberRef&&this.removeMemberRef(h,g);w.setAccumulateState(!1);(c=k(j,d))&&this.event_datasetChanged(this,c)},destroy:function(){this.setSource()}}},init:function(b){i.prototype.init.call(this,b);this.sourceMap_={};if(b=this.source)this.source=null,this.setSource(b)},setRule:function(b){"function"!=typeof b&&(b=t);if(this.rule!==b)return this.rule=b,this.applyRule()},setMap:function(b){"function"!=
typeof b&&(b=z);if(this.map!==b)return this.map=b,this.applyRule()},setSource:function(b){!1==b instanceof i&&(b=null);if(this.source!==b){var c=this.source;c&&(c.removeHandler(this.listen.source,this),this.listen.source.datasetChanged.call(this,c,{deleted:c.getItems()}));if(this.source=b)b.addHandler(this.listen.source,this),this.listen.source.datasetChanged.call(this,b,{inserted:b.getItems()});this.event_sourceChanged(this,c)}},applyRule:function(){var b=this.sourceMap_,c=this.memberMap_,a,e,i,
d,g,f=[],h=[],l,n;for(n in b){g=b[n];d=g.sourceObject;a=g.member;e=this.map?this.map(d):d;if(!1==e instanceof s||this.reduce(e))e=null;if(a!=e){g.member=e;if(a)i=a.eventObjectId,this.removeMemberRef&&this.removeMemberRef(a,d),c[i]--;if(e)a=e.eventObjectId,this.addMemberRef&&this.addMemberRef(e,d),a in c?c[a]++:(c[a]=1,f.push(e))}}for(i in this.item_)0==c[i]&&(delete c[i],h.push(this.item_[i]));(l=k(f,h))&&this.event_datasetChanged(this,l);return l},clear:function(){this.setSource()},destroy:function(){i.prototype.destroy.call(this);
this.sourceMap_=null}}),A=p(u,{reduce:function(b){return!this.rule(b)},rule:t}),p=p(u,{map:function(b){return this.keyMap.resolve(b)},rule:t,subsetClass:i,keyMap:null,addMemberRef:function(b,c){b.event_datasetChanged(b,{inserted:[c]})},removeMemberRef:function(b,c){b.event_datasetChanged(b,{deleted:[c]})},init:function(b){if(!this.keyMap||!1==this.keyMap instanceof x)this.keyMap=new x(v({keyGetter:this.rule,itemClass:this.subsetClass},this.keyMap));u.prototype.init.call(this,b)},getSubset:function(b,
c){return this.keyMap.get(b,c)},destroy:function(){u.prototype.destroy.call(this);this.keyMap.destroy();this.keyMap=null}});basis.namespace("basis.data.dataset").extend({Merge:l,Subtract:B,MapReduce:u,Subset:A,Split:p})})(basis,this);
(function(k){function p(a){f[a]=f[a]||0;return a+f[a]++}function v(){var a=Array.from(arguments),b=a.pop();"function"!=typeof b&&console.warn("Last argument for calculate field constructor must be a function");for(var c=[],d=[],e=0,g;e<a.length;e++)g=a[e].quote('"'),c.push(g+" in delta"),d.push("data["+g+"]");b=(new Function("calc","return function(delta, data, oldValue){"+(c.length?"if ("+c.join(" || ")+")":"")+"return calc("+d.join(", ")+");"+(c.length?"return oldValue;":"")+"}"))(b);b.args=a;b.isCalcField=
!0;return b}function z(){return v.apply(null,Array.from(arguments).concat(function(){for(var a=[],b=arguments.length;0<b--;){if(null==arguments[b])return null;a.push(arguments[b])}return a.join("-")}))}var t=k.Class,A=k.Cleaner,y=Object.extend,q=Function.$self,s=Function.getter,x=k.data,i=k.EventObject,w=x.Dataset,l=x.dataset.Subset,r=x.dataset.Split,B=x.DataObject,u=x.STATE,b={},c={string:1,number:1},a=[],e=function(a){return isNaN(a)?null:Number(a)},j=function(a){return isNaN(a)?null:Number(a)},
d=function(a){return isNaN(a)?null:parseInt(a)},g=function(a){return null==a?null:""+a},f={},h=k.Class(null,{init:function(a){var b=this.index={};this.normalize=a;this.valueWrapper=function(c,d){var e=a(c,d);return e!==d&&b[e]?d:e};this.calcWrapper=function(c,d){var e=a(c,d);if(e!==d&&b[e])throw"Duplicate value for index "+d+" => "+c;return e};A.add(this)},get:function(a,b){var c=this.index[a];if(c&&(!b||c instanceof b))return c},add:function(a,b){var c=this.index[a];if(b&&(!c||c===b))return this.index[a]=
b,!0},remove:function(a,b){if(this.index[a]===b)return delete this.index[a],!0},destroy:function(){this.index=null}}),x=function(a,b){return function(c){return a.prototype[b].call(this,c&&c.map(this.wrapper))}},m=function(a,b){return function(c){if(!this.name)this.name=p(b);a.prototype.init.call(this,c)}},n=function(a){return function(b,c){w.setAccumulateState(!0);b=(b||[]).map(this.wrapper);w.setAccumulateState(!1);return a.prototype.sync.call(this,b,c)}},C=t(w,{wrapper:Function.$self,init:m(w,"EntitySet"),
sync:n(w),set:x(w,"set"),add:x(w,"add"),remove:x(w,"remove"),destroy:function(){w.prototype.destroy.call(this);delete this.wrapper}}),D=t(C,{set:Function.$false,add:Function.$false,remove:Function.$false,clear:Function.$false}),H=t(l,{init:m(l,"EntityCollection"),sync:n(l)});H.sourceHandler=l.sourceHandler;var J=t(r,{subsetClass:D,init:m(r,"EntityGrouping"),sync:n(r),getSubset:function(a,b){var c=r.prototype.getSubset.call(this,a,b);if(c)c.wrapper=this.wrapper;return c}}),o=function(a){if(this instanceof
o){var b=new E(a||q);return function(a,c){return null!=a?(c instanceof C||(c=b.createEntitySet()),c.set(a instanceof w?a.getItems():Array.from(a)),c):null}}};o.className="basis.entity.EntitySetWrapper";var E=t(null,{init:function(a){this.wrapper=a},createEntitySet:function(){return new C({wrapper:this.wrapper,name:"Set of "+((this.wrapper.entityType||this.wrapper).name||"").quote("{")})}}),G=function(a){if(this instanceof G){var b=function(a,b){if(null!=a){if(a===b||a.entityType===d)return a;var h,
i=d.idField;if(c[typeof a]){if(!i)return;h=a;a={};a[i]=h}else if(d.compositeKey)h=d.compositeKey(a,a);else if(i)h=a[i];else if(f&&(b=d.singleton,!b))return d.singleton=new g(a);null!=h&&e&&(b=e.get(h,d.entityClass));b&&b.entityType===d?b.update(a):b=new g(a);return b}return d.singleton},d=new O(a||{},b),e=d.index__,g=d.entityClass,f=d.isSingleton;y(b,{toString:function(){return this.typeName+"()"},entityType:d,type:b,typeName:d.name,index:e,reader:function(a){return d.reader(a)},get:function(a){return d.get(a)},
addField:function(a,b){d.addField(a,b)},all:d.all,createCollection:function(a,c,e){var g=d.collection_[a];return!g&&c?d.collection_[a]=new H({wrapper:b,source:e||d.all,rule:c}):g},getCollection:function(a){return d.collection_[a]},createGrouping:function(a,c,e){var g=d.grouping_[a];return!g&&c?d.grouping_[a]=new J({wrapper:b,source:e||d.all,rule:c}):g},getGrouping:function(a){return d.grouping_[a]},getSlot:function(a,b){return d.getSlot(a,b)}});return b}};G.className="basis.entity.EntityTypeWrapper";
var N=s("singleton"),K={};t(B,{});var O=t(null,{name:"UntitledEntityType",defaults:null,fields:null,extensible:!1,index__:null,slot_:null,init:function(b,c){this.name=b.name||p(this.name);this.index__=b.index;this.idFields={};a.push(this);this.isSingleton=b.isSingleton;this.wrapper=c;this.all=new D(Object.extend(b.all||{},{wrapper:c}));this.slot_={};if(b.extensible)this.extensible=!0;this.fields={};this.defaults={};this.aliases={};this.getters={};Object.iterate(b.fields,this.addField,this);b.constrains&&
b.constrains.forEach(function(a){this.addCalcField(null,a)},this);if(this.isSingleton)this.get=N;b.aliases&&Object.iterate(b.aliases,this.addAlias,this);this.collection_={};if(b.collections)for(var d in b.collections)this.collection_[d]=new H({name:d,wrapper:c,source:this.all,rule:b.collections[d]||Function.$true});this.grouping_={};if(b.groupings)for(d in b.groupings)this.grouping_[d]=new J({name:d,wrapper:c,source:this.all,rule:b.groupings[d]||Function.$true});this.entityClass=M(this,this.all,this.index__,
this.slot_,this.fields,this.defaults,this.getters).extend({entityType:this,type:c,typeName:this.name,getId:function(){return this.__id__}})},reader:function(a){var b={};if(c[typeof a])return this.idField?(b[this.idField]=a,b):null;if(!a||null==a)return null;for(var d in a){var e=d in this.aliases?this.aliases[d]:"";e&&e in this.fields&&(b[e]=this.fields[e].reader?this.fields[e].reader(a[d]):a[d])}return b},addAlias:function(a,b){b in this.fields&&!1==a in this.aliases&&(this.aliases[a]=b)},addField:function(a,
b){if(!this.all.itemCount){this.aliases[a]=a;"function"==typeof b&&(b={type:b});if("type"in b&&"function"!=typeof b.type)b.type=q;var c=b.type||q;if([e,j,d,g].has(c))b.id=!0;if(b.id){if(!this.index__)this.index__=new h(String);this.idFields[a]=!0;this.idField||this.compositeKey?(this.idField=null,this.compositeKey=z.apply(null,Object.keys(this.idFields))):this.idField=a}b.calc?this.addCalcField(a,b.calc,void 0):this.fields[a]=c;this.defaults[a]="defValue"in b?b.defValue:c();this.getters["get_"+a]=
function(){return this.data[a]};K[a]||(K[a]={destroy:function(){this.set(a,null)}})}},addCalcField:function(a,b,c){if(!a||!this.fields[a]){if(!this.calcs)this.calcs=[];for(var d={args:b.args,wrapper:!c?b:function(a,d,e){return c(b(a,d,e))}},e=this.calcs.length,g=0,f=0;f<this.calcs.length;f++)b.args.has(this.calcs[f].key)&&(g=f+1);if(a){d.key=a;for(f=0;f<this.calcs.length;f++)if(this.calcs[f].args.has(a)){e=f;break}if(g>e)return;if(this.idField&&a==this.idField)this.compositeKey=b;this.fields[a]=function(a,
b){"undefined"!=typeof console&&console.log("Calculate fields are readonly");return b}}else e=g;this.calcs.splice(Math.min(e,g),0,d)}},get:function(a){a=this.getId(a);if(null!=a)return this.index__.get(a,this.entityClass)},getId:function(a){if((this.idField||this.compositeKey)&&null!=a){if(c[typeof a])return a;if(a&&a.entityType===this)return a.__id__;if(a instanceof B)a=a.data;return this.compositeKey?this.compositeKey(a,a):a[this.idField]}},getSlot:function(a){var b=this.getId(a);if(null!=b){var d=
this.slot_[b];d||(c[typeof a]&&(d={},this.idField&&!this.compositeKey&&(d[this.idField]=a),a=d),d=this.slot_[b]=new B({delegate:this.get(b),data:a}));return d}}}),L=t(B,{init:i.prototype.init,event_rollbackUpdate:i.createEvent("rollbackUpdate")}),M=function(a,c,d,e,g,f,h){function j(b,c,d){var e=!1,g=a.calcs,f=b.__id__,h=b.data;try{if(g)for(var i=0,m;m=g[i++];){var n=m.key;if(n){var o=h[n];h[n]=m.wrapper(c,h,h[n]);h[n]!==o&&(c[n]=o,e=!0)}else m.wrapper(c,h)}if(a.compositeKey)b.__id__=a.compositeKey(c,
h,b.__id__);else if(l&&l in c)b.__id__=h[l];b.__id__!==f&&a.index__.calcWrapper(b.__id__)}catch(p){b.__id__=f;for(var q in c)b.data[q]=c[q];if(d)for(q in d)if(!b.modified)b.modified=d;e=!1}b.__id__!==f&&k(b,f,b.__id__);return e}function k(a,b,c){null!=b&&(d.remove(b,a),e[b]&&e[b].setDelegate());null!=c&&(d.add(c,a),e[c]&&e[c].setDelegate(a))}var l=a.idField;return t(L,h,{canHaveDelegate:!1,modified:null,isTarget:!0,extendConstructor_:!1,init:function(a){L.prototype.init.call(this);this.fieldHandlers_=
{};this.data={};this.root=this;this.target=this;var b,d={},e;for(e in g)e in a?(d[e]=f[e],b=g[e](a[e])):b=f[e],b&&b!==this&&b instanceof i&&b.addHandler(K[e],this)&&(this.fieldHandlers_[e]=!0),this.data[e]=b;j(this,d);c.event_datasetChanged(c,{inserted:[this]})},toString:function(){return"[object "+this.constructor.className+"("+this.entityType.name+")]"},get:function(a){return this.data[a]},set:function(b,c,d,e){var f=g[b];if(!f){if(!a.extensible)return;f=q}var h,k=this.modified,c=f(c,this.data[b]),
f=this.data[b];if(c!==f&&(!c||!f||c.constructor!==Date||f.constructor!==Date||+c!==+f))a:{h={};if(b!=l)if(d){if(!k)this.modified=k={};if(!1===b in k)h.rollback={key:b,value:void 0},k[b]=f;else if(k[b]===c&&(h.rollback={key:b,value:c},delete k[b],!Object.keys(k).length))this.modified=null}else if(k&&b in k)if(k[b]!==c){h.rollback={key:b,value:k[b]};k[b]=c;break a}else return!1;this.data[b]=c;this.fieldHandlers_[b]&&(f.removeHandler(K[b],this),this.fieldHandlers_[b]=!1);c&&c!==this&&c instanceof i&&
c.addHandler(K[b],this)&&(this.fieldHandlers_[b]=!0);h.key=b;h.value=f;h.delta={};h.delta[b]=f}else if(!d&&k&&b in k&&(h={rollback:{key:b,value:k[b]}},delete k[b],!Object.keys(k).length))this.modified=null;if(!e&&h){var d=h.key,b=h.delta||{},m;if(h.rollback)m={},m[h.rollback.key]=h.rollback.value;j(this,b,m)&&(d=!0);if(d)this.event_update(this,b),h.delta=b;m&&this.event_rollbackUpdate(this,m)}return h||!1},update:function(a,b){if(a){var c,d={},e,g={},f,h;for(h in a)if(f=this.set(h,a[h],b,!0)){if(f.key)c=
!0,d[f.key]=f.value;if(f.rollback)e=!0,g[f.rollback.key]=f.rollback.value}j(this,d,g)&&(c=!0);c&&this.event_update(this,d);e&&this.event_rollbackUpdate(this,g)}return c?d:!1},reset:function(){this.update(f)},clear:function(){var a={},b;for(b in this.data)a[b]=void 0;return this.update(a)},commit:function(a){if(this.modified){var b=this.modified;this.modified=null}this.update(a);b&&this.event_rollbackUpdate(this,b)},rollback:function(){if(this.state!=u.PROCESSING){if(this.modified){var a=this.modified;
this.modified=null;this.update(a);this.event_rollbackUpdate(this,a)}this.setState(u.READY)}},destroy:function(){for(var a in this.fieldHandlers_)this.data[a].removeHandler(K[a],this);this.fieldHandlers_=b;this.__id__&&k(this,this.__id__,null);B.prototype.destroy.call(this);c.event_datasetChanged(c,{deleted:[this]});this.data=b;this.modified=null}})};k.namespace("basis.entity").extend({isEntity:function(a){return a&&a instanceof M},NumericId:e,NumberId:j,IntId:d,StringId:g,Index:h,CalculateField:v,
EntityType:G,Entity:M,BaseEntity:L,EntitySetType:o,EntitySet:C,ReadOnlyEntitySet:D,Collection:H,Grouping:J})})(basis);
