/*!
 * Basis javasript library 
 * http://code.google.com/p/basis-js/
 *
 * @license
 * GNU General Public License v2.0 <http://www.gnu.org/licenses/gpl-2.0.html>
 */

(function(j){function m(a,b){for(var c in b)a[c]=b[c];return a}function v(a,b){for(var c in b)!1==c in a&&(a[c]=b[c]);return a}function w(a){return null==a||void 0==a}function s(a){return a}function D(a){var b={};a.names=function(a){return Object.slice(b,"string"==typeof a?a.qw():a)};a.extend=function(a){v(b,a);m(this,a);return this};return a}function E(a,b){for(var c=a.split("."),d=j,f,g,e;c.length;)if(f=c.shift(),g=(g?g+".":"")+f,d[f]||(d[f]=D((!c.length?b:null)||function(){},g),e&&(e.namespaces_[g]=
d[f])),d=d[f],!e&&(e=d,!e.namespaces_))e.namespaces_={};return t[a]=d}m(Object,{extend:m,complete:v,keys:function(a){var b=[],c;for(c in a)b.push(c);return b},values:function(a){var b=[],c;for(c in a)b.push(a[c]);return b},slice:function(a,b){var c={};if(!b)return m(c,a);for(var d=0,f;f=b[d++];)f in a&&(c[f]=a[f]);return c},splice:function(a,b){var c={};if(!b)return m(c,a);for(var d=0,f;f=b[d++];)f in a&&(c[f]=a[f],delete a[f]);return c},iterate:function(a,b,c){var d=[],f;for(f in a)d.push(b.call(c,
f,a[f]));return d},coalesce:function(){for(var a=arguments,b=0;b<a.length;b++)if(null!=a[b])return a[b]}});var u=function(){},n=function(){var a=1,b={},c={};a++;return function(d,f){var g,e;if(!f){if(d.getter)return d.getter;if("function"==typeof d)return d}if("function"!=typeof d)c[d]?g=c[d]:(g=new Function("object","return object != null ? object."+d+" : object"),g.path=d,g.getterIdx_=a++,c[d]=g);else if(g=d,!g.getterIdx_)g.getterIdx_=a++;e=g.getterIdx_;var h=b[e];if(h)if("undefined"==typeof f){if(h.nmg)return h.nmg}else for(e=
0;e<h.length;e++){if(h[e].modificator===f)return h[e].getter}else h=b[e]=[];var l=!0;switch(f&&typeof f){case "string":e=function(a){return f.format(g(a))};break;case "function":e=function(a){return f(g(a))};break;case "object":l=!1;e=function(a){return f[g(a)]};break;default:e=g.path?g:function(a){return g(a)}}if(l&&(h.push({getter:e,modificator:f}),"undefined"==typeof f))h.nmg=e;return e.getter=e}}();m(Function,{$undefined:function(a){return void 0==a},$defined:function(a){return void 0!=a},$isNull:w,
$isNotNull:function(a){return null!=a&&void 0!=a},$isSame:function(a){return a===this},$isNotSame:function(a){return a!==this},$self:s,$const:function(a){return function(){return a}},$false:function(){return!1},$true:function(){return!0},$null:function(){return null},$undef:u,getter:n,def:function(a,b,c){c=c||w;return function(d){d=a(d);return c(d)?b:d}},wrapper:function(a){return function(b){var c={};c[a]=b;return c}},lazyInit:function(a,b){var c=0,d;return function(){c++||(d=a.apply(b||this,arguments));
return d}},lazyInitAndRun:function(a,b,c){var d=0,f;return function(){d++||(f=a.call(c||this));b.apply(f,arguments);return f}},runOnce:function(a,b){var c=0;return function(){if(!c++)return a.apply(b||this,arguments)}}});v(Function.prototype,{bind:function(a){var b=this,c=Array.from(arguments,1);return c.length?function(){return b.apply(a,c.concat.apply(c,arguments))}:function(){return b.apply(a,arguments)}}});v(Array,{isArray:function(a){return"[object Array]"===Object.prototype.toString.call(a)}});
m(Array,{from:function(a,b){if(null!=a){var c=a.length;if("undefined"==typeof c)return[a];b||(b=0);if(0<c-b){for(var d=[],f=0,g=b;g<c;)d[f++]=a[g++];return d}}return[]},create:function(a,b,c){for(var d=[],f="function"==typeof b,g=0;g<a;g++)d[g]=f?b.call(c,g,d):b;return d}});v(Array.prototype,{indexOf:function(a,b){b=parseInt(b)||0;if(0>b)return-1;for(;b<this.length;b++)if(this[b]===a)return b;return-1},lastIndexOf:function(a,b){for(var c=this.length,b=parseInt(b),b=isNaN(b)||b>=c?c-1:(b+c)%c;0<=b;b--)if(this[b]===
a)return b;return-1},forEach:function(a,b){for(var c=0,d=this.length;c<d;c++)c in this&&a.call(b,this[c],c,this)},every:function(a,b){for(var c=0,d=this.length;c<d;c++)if(c in this&&!a.call(b,this[c],c,this))return!1;return!0},some:function(a,b){for(var c=0,d=this.length;c<d;c++)if(c in this&&a.call(b,this[c],c,this))return!0;return!1},filter:function(a,b){for(var c=[],d=0,f=this.length;d<f;d++)d in this&&a.call(b,this[d],d,this)&&c.push(this[d]);return c},map:function(a,b){for(var c=[],d=0,f=this.length;d<
f;d++)d in this&&(c[d]=a.call(b,this[d],d,this));return c},reduce:function(a,b){var c=this.length,d=arguments.length;if(0==c&&1==d)throw new TypeError;var f,g=0;1<d&&(f=b,g=1);for(d=0;d<c;d++)d in this&&(f=g++?a.call(null,f,this[d],d,this):this[d]);return f}});m(Array.prototype,{flatten:function(){return this.concat.apply([],this)},repeat:function(a){return Array.create(parseInt(a)||0,this).flatten()},item:function(a){a=parseInt(a||0);return this[0<=a?a:this.length+a]},search:function(a,b,c){Array.lastSearchIndex=
-1;for(var b=Function.getter(b||s),c=parseInt(c)||0,d=this.length;c<d;c++)if(b(this[c])===a)return this[Array.lastSearchIndex=c]},lastSearch:function(a,b,c){Array.lastSearchIndex=-1;for(var b=Function.getter(b||s),d=this.length,c=isNaN(c)||null==c?d:parseInt(c),d=c>d?d:c;0<d--;)if(b(this[d])===a)return this[Array.lastSearchIndex=d]},binarySearchPos:function(a,b,c,d,f,g){if(!this.length)return d?-1:0;var b=Function.getter(b||s),c=!!c,e,f=isNaN(f)?0:f,h=isNaN(g)?this.length-1:g;do if(g=f+h>>1,e=b(this[g]),
c?a>e:a<e)h=g-1;else if(c?a<e:a>e)f=g+1;else return a==e?g:d?-1:0;while(f<=h);return d?-1:g+(e<a^c)},binarySearch:function(a,b){return this.binarySearchPos(a,b,!1,!0)},add:function(a){return-1==this.indexOf(a)&&!!this.push(a)},remove:function(a){a=this.indexOf(a);return-1!=a&&!!this.splice(a,1)},has:function(a){return-1!=this.indexOf(a)},merge:function(a){return this.reduce(m,a||{})},sortAsObject:function(a,b,c){a=Function.getter(a);c=c?-1:1;return this.map(function(b,c){return{i:c,v:a(b)}}).sort(b||
function(a,b){return c*(a.v>b.v||-(a.v<b.v)||(a.i>b.i?1:-1))}).map(function(a){return this[a.i]},this)},set:function(a){if(this!==a)this.length=0,this.push.apply(this,a);return this},clear:function(){this.length=0;return this}});if(![1,2].splice(1).length){var r=Array.prototype.splice;Array.prototype.splice=function(){var a=Array.from(arguments);if(2>a.length)a[1]=this.length;return r.apply(this,a)}}var i={"<":">","[":"]","(":")","{":"}","\u00ab":"\u00bb"};String.Entity={laquo:"\u00ab",raquo:"\u00bb",
nbsp:"\u00a0",quot:'"',quote:'"',copy:"\u00a9",shy:"\u00ad",para:"\u00b6",sect:"\u00a7",deg:"\u00b0",mdash:"\u2014",hellip:"\u2026"};v(String,{toLowerCase:function(a){return(""+a).toLowerCase()},toUpperCase:function(a){return(""+a).toUpperCase()},trim:function(a){return(""+a).trim()},trimLeft:function(a){return(""+a).trimLeft()},trimRight:function(a){return(""+a).trimRight()},isEmpty:function(a){return null==a||""==""+a},isNotEmpty:function(a){return null!=a&&""!=""+a}});v(String.prototype,{trimLeft:function(){return this.replace(/^\s+/,
"")},trimRight:function(){return this.replace(/\s+$/,"")},trim:function(){return this.trimLeft().trimRight()}});m(String.prototype,{toObject:function(a){try{return Function("return 0,"+this)()}catch(b){if(a)throw b;}},toArray:(new String("a"))[0]?function(){return Array.from(this)}:function(){for(var a=[],b=this.length,c=0;c<b;c++)a[c]=this.charAt(c);return a},repeat:function(a){return Array(parseInt(a)+1||0).join(this)},qw:function(){var a=this.trim();return a?a.split(/\s+/):[]},forRegExp:function(){return this.replace(/[\/\\\(\)\[\]\?\{\}\|\*\+\-\.\^\$]/g,
"\\$&")},format:function(a){for(var b={},c=0;c<arguments.length;c++)b[c]=arguments[c];"object"==typeof a&&m(b,a);return this.replace(/\{([a-z\d\_]+)(?::([\.0])(\d+)|:(\?))?\}/gi,function(a,c,g,e,h){a=c in b?b[c]:h?"":a;return g&&!isNaN(a)?(a=Number(a),"."==g?a.toFixed(e):a.lead(e)):a})},quote:function(a,b){var a=a||'"',b=b||i[a]||a,c=(1==a.length?a:"")+(1==b.length?b:"");return a+(c?this.replace(RegExp("["+c.forRegExp()+"]","g"),"\\$&"):this)+b},capitalize:function(){return this.charAt(0).toUpperCase()+
this.substr(1).toLowerCase()},camelize:function(){return this.replace(/-(.)/g,function(a,b){return b.toUpperCase()})},dasherize:function(){return this.replace(/[A-Z]/g,function(a){return"-"+a.toLowerCase()})}});String.format=String.prototype.format;if(11!="|||".split(/\|/).length+"|||".split(/(\|)/).length)String.prototype.split=function(a){if(""==a||a&&""==a.source)return this.toArray();var b=[],c=0,d;if(a instanceof RegExp)for(a.global||(a=RegExp(a.source,/\/([mi]*)$/.exec(a)[1]+"g"));d=a.exec(this);)d[0]=
this.substring(c,d.index),b.push.apply(b,d),c=a.lastIndex;else for(;-1!=(d=this.indexOf(a,c));)b.push(this.substring(c,d)),c=d+a.length;b.push(this.substr(c));return b};if("2"!="12".substr(-1)){var y=String.prototype.substr;String.prototype.substr=function(a,b){return y.call(this,0>a?Math.max(0,this.length+a):a,b)}}m(Number.prototype,{fit:function(a,b){return!isNaN(a)&&this<a?Number(a):!isNaN(b)&&this>b?Number(b):this},between:function(a,b){return!isNaN(this)&&this>=a&&this<=b},quote:function(a,b){return(this+
"").quote(a,b)},toHex:function(){return parseInt(this).toString(16).toUpperCase()},sign:function(){return 0>this?-1:+(0<this)},base:function(a){return!a||isNaN(a)?0:Math.floor(this/a)*a},lead:function(a,b){return(this+"").replace(/\d+/,function(c){return 1<(a-=c.length-1)?Array(a).join(b||0)+c:c})},group:function(a,b){return(this+"").replace(/\d+/,function(c){return c.replace(/\d/g,function(d,f){return!f+(c.length-f)%(a||3)?d:(b||" ")+d})})},format:function(a,b,c,d,f){a=this.toFixed(a);if(b||f)a=
a.replace(/(\d+)(\.?)/,function(a,e,h){return(b?Number(e).group(3,b):e)+(h?f||h:"")});c&&(a=a.replace(/^-?/,"$&"+(c||"")));return a+(d||"")}});v(Date,{now:function(){return+new Date}});1900>(new Date).getYear()&&m(Date.prototype,{getYear:function(){return this.getFullYear()-1900},setYear:function(a){return this.setFullYear(!isNaN(a)&&100>a?Number(a)+1900:a)}});var t={},C=function(){function a(a,e){for(var h=t[a],l=e?e.split(/\./):[];h&&l.length;)h=h[l.shift()];return h}var b=j.document?j.document.getElementsByTagName("SCRIPT"):
null,c=(b?b[b.length-1].src:module.filename).replace(/[^\/]+$/,""),d={},f;"function"==typeof require?f=function(a){return require(requirePath+a.replace(/\./g,"/"))}:(f=function(b,e){var h=b.match(/^([a-z][a-zA-Z0-9\_]*(\.[a-z][a-zA-Z0-9\_]*)*)?/)[0],l=b.substr(h.length?h.length+1:0),o=a(h,l),F=/^basis\./.test(h)?c:(location?location.href:"").replace(/[a-z0-9\-\_\.]+\.[a-z0-9]+$/,"");if(!t[h]||!o)if(/^https?:/.test(F)){if(d[b])throw"Attempt to load namespace, probably cycle require";d[b]=1;var F=F+
(e||"")+b.replace(/\./g,"/")+".js",G=new XMLHttpRequest;G.open("POST",F,!1);G.send(null);if(200==G.status){try{(new Function(G.responseText)).call(j)}catch(J){throw J;}f.sequence.push(b.replace(/\./g,"/")+".js")}else if(404==G.status&&l)C(h);else throw"!";}else throw"Path `"+b+"` can't be resolved";return o||a(h,l)},f.sequence=[]);return f}(),B=function(){function a(a){return"function"==typeof a&&a.basisClass_}var b=Function(),c=1,d={},f=function(){for(var a in{toString:1})return;return!0}();m(b,
{className:"basis.Class",extendConstructor_:!1,prototype:{constructor:null,init:Function(),toString:function(){return"[object "+(this.constructor||this).className+"]"},destroy:function(){for(var a in this)this[a]=null;this.destroy=u}},create:function(e){"function"!=typeof e&&(e=b);var l=Function();l.prototype=e.prototype;for(var l=new l,o={className:e.className+"._SubClass_",basisClass_:!0,superClass_:e,extendConstructor_:!!e.extendConstructor_,__extend__:function(e){return e&&("object"==typeof e||
"function"==typeof e&&!a(e))&&e!==d?b.create.call(null,k,e):e},extend:b.extend,subclass:function(){return b.create.apply(null,[k].concat(Array.from(arguments)))},prototype:l},F=arguments,G=1;G<F.length;G++)o.extend("function"==typeof F[G]&&!a(F[G])?F[G](e.prototype):F[G]);var f={},k=o.extendConstructor_?function(a,k){this.eventObjectId=c++;var e,p;for(p in a)e=this[p],this[p]=e&&e.__extend__?e.__extend__(a[p]):a[p];this.init(k||f)}:function(){this.eventObjectId=c++;this.init.apply(this,arguments)};
l.constructor=k;for(var p in l)l[p]===d&&(l[p]=k);m(k,o);return k},extend:function(a){var e=this.prototype;if(a.prototype)a=a.prototype;for(var b in a){var c=a[b],G=e[b];"className"==b||"extendConstructor_"==b?this[b]=c:e[b]=G&&G.__extend__?G.__extend__(c):c}if(f&&a[b="toString"]!==Object.prototype[b])e[b]=a[b];return this}});var g=function(a,e){return{__extend__:function(a){var b=Function();b.prototype=this;b=new b;e(b,a);return b}}.__extend__(a)},e=function(a){return g(a,m)};return E("basis.Class",
b.create).extend({SELF:d,BaseClass:b,create:b.create,isClass:a,CustomExtendProperty:g,ExtensibleProperty:e,NestedExtProperty:function(a){return g(a,function(a,b){for(var h in b){var c=a[h];a[h]=c&&c.__extend__?c.__extend__(b[h]):e(b[h])}})}})}(),q=function(){function a(a){var e=c[a];e||(e=c[a]=function(){var e=this.handlers_,l,o;if(e&&e.length)for(var e=b.call(e),c=e.length;0<c--;)l=e[c],o=l.handler[a],"function"==typeof o&&o.apply(l.thisObject,arguments)});return e}var b=Array.prototype.slice,c=
{},d,f=B(null,{handlers_:null,event_destroy:d=a("destroy","object"),listen:B.NestedExtProperty(),extendConstructor_:!0,init:function(){if(this.handler)(this.handlers_||(this.handlers_=[])).push({handler:this.handler,thisObject:this.handlerContext||this})},addHandler:function(a,e){var b=this.handlers_;if(!b)b=this.handlers_=[];e||(e=this);for(var l=b.length,o;0<l--;)if(o=b[l],o.handler===a&&o.thisObject===e)return!1;return!!b.push({handler:a,thisObject:e||this})},removeHandler:function(a,e){var b=
this.handlers_;if(b){e||(e=this);for(var l=b.length,o;0<l--;)if(o=b[l],o.handler===a&&o.thisObject===e)return!!b.splice(l,1);return!1}},destroy:function(){if(this.handlers_)d.call(this,this),this.handlers_=null}});f.createEvent=a;f.event=c;return f}(),z=function(){var a=[];return{add:function(b){null!=b&&a.push(b)},remove:function(b){a.remove(b)}}}();(function(){function a(a){if(b){if(a.source!=j||a.data!=c)return;basis.dom.event.kill(a)}d.length&&(a=d.shift(),delete f[a.key],a.fn())}var b="function"==
typeof addEventListener&&"function"==typeof postMessage,c="zeroTimeoutMessage",d=[],f={},g=1;b&&j.addEventListener("message",a,!0);var e=setTimeout;j.setTimeout=function(l,h){var F;h?F=e.call(j,l,h):(F={key:"z"+g++,fn:"function"==typeof l?l:new Function(l)},f[F.key]=F,d.push(F),b?postMessage(c,"*"):F.timer=e.call(j,a,0),F=F.key);return F};var h=clearTimeout;j.clearTimeout=function(a){if(/z\d+/.test(a)){var e=f[a];e&&(clearTimeout(e.timer),d.remove(e),delete f[a])}else return h.call(j,a)}})();var x=
function(){function a(){if(!o)if(g.length){var a=Date.now(),e=Math.max(g[0].eventTime,a);e<h&&(clearTimeout(l),l=setTimeout(c,(h=e)-a))}else l=clearTimeout(l),h=d}function b(l,b){var h=l.eventObjectId,k=e[b]&&e[b][h];k&&(g.remove(k),delete e[b][h],a())}function c(){var l=Date.now(),l=g.binarySearchPos(l+15,f);o=!0;g.splice(0,l).forEach(function(a){delete e[a.eventName][a.object.eventObjectId];a.callback.call(a.object)});o=!1;h=d;a()}var d=2E12,f=n("eventTime"),g=[],e={},h=d,l=null,o=!1;z.add({destroy:function(){o=
!0;clearTimeout(l);g.length=0;e=null}});return{add:function(l,h,o){var k=l.eventObjectId,p=e[h];p||(p=e[h]={});var A=p[k];if(A){if(isNaN(o))return b(l,h);if(A.eventTime==o)return;g.remove(A);A.eventTime=o}else{if(isNaN(o))return;A=p[k]={eventName:h,object:l,eventTime:o,callback:l[h]}}g.splice(g.binarySearchPos(o,f),0,A);a()},remove:b}}();E("basis").extend({namespace:E,platformFeature:{},EventObject:q,TimeEventManager:x,Cleaner:z,require:C});j.basis.locale={}})(this);
(function(j,m){function v(q){for(var j=1E6,q=(""+q).split("."),i=0,a=0;4>i&&i<q.length;i++,j/=100)a+=q[i]*j;return a}function w(){for(var j=0;j<arguments.length;j++){var i=arguments[j].toLowerCase();if(i in D){if(D[i])return!0}else{var m=i.match(/^([a-z]+)(([\d\.]+)([+-=]?))?$/i);if(m){D[i]=!1;var a=m[1].toLowerCase(),b=v(m[3]),m=m[4]||"=";if(a=E[a])return D[i]=!b||"="==m&&a==b||"+"==m&&a>=b||"-"==m&&a<b}}}return!1}var s="basis.ua",D={},E={},u=m.navigator&&m.navigator.userAgent,n="unknown",r={MSIE:["Internet Explorer",
"msie","ie"],Gecko:["Gecko","gecko"],Safari:["Safari","safari"],"iPhone OS":["iPhone","iphone"],AdobeAir:["AdobeAir","air"],AppleWebKit:["WebKit"],Chrome:["Chrome","chrome"],FireFox:["FireFox","firefox","ff"],Iceweasel:["FireFox","firefox","ff"],Shiretoko:["FireFox","firefox","ff"],Opera:["Opera","opera"]},i;for(i in r)if(!("MSIE"==i&&m.opera)&&!("Safari"==i&&u.match(/chrome/i))&&!("AppleWebKit"==i&&u.match(/iphone/i))&&u.match(RegExp(i+".(\\d+(\\.\\d+)*)","i")))for(var y=r[i],t=m.opera&&"function"==
typeof m.opera.version?m.opera.version():RegExp.$1,C=v(t),n=y[0]+" "+t,t=0;t<y.length;t++)E[y[t].toLowerCase()]=C;j.platformFeature.datauri=!1;u="undefined"!=typeof Image?new Image:{};u.onload=function(){j.platformFeature.datauri=!0};u.src="data:image/gif;base64,R0lGODlhAQABAIAAAP///wAAACH5BAEAAAAALAAAAAABAAEAAAICRAEAOw==";if(w("IE7-"))try{document.execCommand("BackgroundImageCache",!1,!0)}catch(B){}s=j.namespace(s);s.toString=function(){return n};return s.extend({testImage:u,prettyName:n,test:w,
is:function(j){return w(j)},Cookies:{set:function(j,i,m,a){document.cookie=j+"="+(null==i?"":escape(i))+";path="+(a||(0==location.pathname.indexOf("/")?"":"/")+location.pathname)+(m?";expires="+(new Date(Date.now()+1E3*m)).toGMTString():"")},get:function(j){return(j=document.cookie.match(RegExp("(^|;)\\s*"+j+"\\s*=\\s*(.*?)\\s*(;|$)")))&&unescape(j[2])},remove:function(j,i){document.cookie=j+"=;expires="+(new Date(0)).toGMTString()+";path="+(i||(0==location.pathname.indexOf("/")?"":"/")+location.pathname)}}})})(basis,
this);
(function(j,m){function v(a,e,b){if(null!=e)return a.insertBefore(c(e)?e:E(e),b||null)}function w(a){return n("",a.cloneNode(!0)).innerHTML}function s(a){return c(a)||a&&a.nodeType?a:"string"==typeof a?t.getElementById(a):null}function D(e,b,h){var c,f=[],h="string"==typeof h?getter(h):h||Function.$true;b&26&&h(e)&&f.push(e);switch(b){case 1:case 2:for(c=e;(c=c[q])&&c!==e.document;)h(c)&&f.push(c);break;case 64:for(c=e[z];c;)h(c)&&f.push(c),c=c[x];break;case 4:case 8:e[z]&&(b=new d(e),b.nodes(h,f));
break;case 128:b=new d(e,h);for(b.cursor_=e[x]||e[q];c=b.next();)f.push(c);break;case 256:for(c=e;c=c[x];)h(c)&&f.push(c);break;case 32:h(e[q])&&f.push(e[q]);break;case 512:b=new d(e,h,d.BACKWARD);for(b.cursor_=e[a]||e[q];c=b.next();)f.push(c);break;case 1024:for(c=e;c=c[a];)h(c)&&f.push(c)}return f}function E(a){return t.createTextNode(null!=a?a:"")}function u(){for(var a=t.createDocumentFragment(),e=arguments.length,b=u.array=[],h=0;h<e;h++)b.push(v(a,arguments[h]));return a}function n(a,b){var c=
void 0!=a&&"string"!=typeof a,d=(c?a.description:a)||"",f="div",k=d.match(/^([a-z0-9\_\-]+)(.*)$/i);k&&(f=k[1],d=k[2]);if(""!=d){for(var p=[],A={},K;k=h.exec(d);){if(k[8])throw Error("Create element error in basis.dom.createElement()\n\nDescription:\n> "+d+"\n\nProblem place:\n> "+d.substr(0,k.index)+"--\>"+d.substr(k.index)+"<--");K=k[1]||k[2]||k[3];k[1]?A.id=K:k[2]?p.push(K):"class"!=K&&(A[K]=k[4]?y(k[5],k[6],k[7]):K)}g&&A.name&&/^(input|textarea|select)$/i.test(f)&&(f="<"+f+" name="+A.name+">")}d=
t.createElement(f);if(A){if(A.style&&e)d.style.cssText=A.style;for(var L in A)d.setAttribute(L,A[L],0)}if(p&&p.length)d.className=p.join(" ");1<arguments.length&&v(d,u.apply(0,Array.from(arguments,1).flatten()));if(c&&(a.css&&j.cssom&&j.cssom.setStyle(d,a.css),j.dom.event))for(var i in a)"function"==typeof a[i]?j.dom.event.addHandler(d,i,a[i],d):a[i]instanceof j.dom.event.Handler&&j.dom.event.addHandler(d,i,a[i].handler,a[i].thisObject);return d}function r(a,e){return a[q]?a[q].replaceChild(e,a):
a}function i(a){if(t.selection){var e=t.selection.createRange();0!=e.compareEndPoints("StartToEnd",e)&&e.collapse(a);return e.getBookmark().charCodeAt(2)-2}}var y=Object.coalesce,t=m.document,C=j.Class,B=t.createElement("div"),q="parentNode",z="firstChild",x="nextSibling",a="previousSibling",b;b="function"==typeof B.compareDocumentPosition?function(a,e){return a.compareDocumentPosition(e)}:function(a,e){return a==e?0:a.document!=e.document?33:a.sourceIndex>e.sourceIndex?2|8*e.contains(childA):4|16*
a.contains(childB)};var c;if("undefined"!=typeof Node){if(c=function(a){return a instanceof Node},!Node.prototype.contains)Node.prototype.contains=function(a){return!!(this.compareDocumentPosition(a)&16)}}else c=function(a){return a&&a.ownerDocument===t};var d=C(null,{root_:null,cursor_:null,filter:Function.$true,init:function(a,e,b){this.setRoot(a);this.setDirection(b);if("function"==typeof e)this.filter=e},setDirection:function(e){Object.extend(this,e?{a:"lastChild",b:a,c:x,d:z}:{a:z,b:x,c:a,d:"lastChild"})},
setRoot:function(a){this.root_=a||t;this.reset()},reset:function(){this.cursor_=null},first:function(a){this.reset();return this.next(a)},last:function(a){this.reset();return this.prev(a)},nodes:function(a,e){var b;e||(e=[]);for(this.reset();b=this.next(a);)e.push(b);return e},next:function(a){var a=a||this.filter,e=this.cursor_||this.root_;do for(var b=e[this.a];!b;){if(e===this.root_)return this.cursor_=null;(b=e[this.b])||(e=e[q])}while(!a(e=b));return this.cursor_=e},prev:function(a){var a=a||
this.filter,e=this.cursor_,b=this.c,h=this.d;do{var c=e?e[b]:this.root_[h];if(c){for(;c[h];)c=c[h];e=c}else e&&(e=e[q]);if(!e||e===this.root_){e=null;break}}while(!a(e));return this.cursor_=e},destroy:function(){this.cursor_=this.root_=null}});d.BACKWARD=!0;var f="textContent innerText nodeValue".qw(),g=function(){var a=t.createElement("input");a.name="a";return!/name/.test(w(a))}(),e;B.setAttribute("style","color: red");e="red"!==B.style.color;var h=/#([a-z0-9\_\-\:]+)|\.([a-z0-9\_\-\:]+)|\[([a-z0-9\_\-:]+)(="((?:\\.|[^"])*)"|='((?:\\.|[^'])*)'|=((?:\\.|[^\]])*))?\s*\]|\s*(\S)/gi;
return j.namespace("basis.dom").extend({ELEMENT_NODE:1,ATTRIBUTE_NODE:2,TEXT_NODE:3,CDATA_SECTION_NODE:4,ENTITY_REFERENCE_NODE:5,ENTITY_NODE:6,PROCESSING_INSTRUCTION_NODE:7,COMMENT_NODE:8,DOCUMENT_TYPE_NODE:10,DOCUMENT_NODE:9,DOCUMENT_FRAGMENT_NODE:11,NOTATION_NODE:12,AXIS_ANCESTOR:1,AXIS_ANCESTOR_OR_SELF:2,AXIS_DESCENDANT:4,AXIS_DESCENDANT_OR_SELF:8,AXIS_SELF:16,AXIS_PARENT:32,AXIS_CHILD:64,AXIS_FOLLOWING:128,AXIS_FOLLOWING_SIBLING:256,AXIS_PRESCENDING:512,AXIS_PRESCENDING_SIBLING:1024,INSERT_BEGIN:"begin",
INSERT_END:"end",INSERT_BEFORE:"before",INSERT_AFTER:"after",TreeWalker:d,outerHTML:w,textContent:function(a){for(var e=0,b;b=f[e++];)if(null!=a[b])return a[b];return D(a,4,function(a){return 3==a.nodeType}).map(getter("nodeValue")).join("")},get:s,tag:function(a,e){a=s(a)||t;return"*"==e&&a.all?Array.from(a.all):Array.from(a.getElementsByTagName(e||"*"))},axis:D,findAncestor:function(a,e,b){for(;a&&a!==b;){if(e(a))return a;a=a.parentNode}},createElement:n,createText:E,createFragment:u,insert:function(a,
e,b,h){a=s(a);if(!a)throw Error("basis.dom.insert: destination node can't be null");switch(b){case void 0:case "end":h=null;break;case "begin":h=a[z];break;case "before":break;case "after":h=h[x];break;default:h=Number(b).between(0,a.childNodes.length)?a.childNodes[b]:null}b=!c(a);if(!e||!Array.isArray(e))b=b?e&&a.insertBefore(e,h):v(a,e,h);else if(b)for(var b=[],d=0,k=e.length;d<k;d++)b[d]=a.insertBefore(e[d],h);else a.insertBefore(u.apply(0,e),h),b=u.array;return b},remove:function(a){return a[q]?
a[q].removeChild(a):a},replace:r,swap:function(a,e){if(a===e||b(a,e)&25)return!1;r(a,B);r(e,a);r(B,e);return!0},clone:function(a,e){var b=a.cloneNode(!e);b.attachEvent&&D(b,8).forEach(Event.clearHandlers);return b},clear:function(a){for(a=s(a);a.lastChild;)a.removeChild(a.lastChild);return a},wrap:function(a,e,b){var h=[],b=Function.getter(b||Function.$self),c;for(c in e)for(var k=0;k<a.length;k++){var p=b(a[k]);h[k]=e[c](a[k],k,p)?n(c,p):a[k]}return h},setAttribute:function(a,e,b){null==b?a.removeAttribute(e):
a.setAttribute(e,b)},parentOf:function(a,e){return a.contains(e)},isInside:function(a,e){return a==e||e.contains(a)},focus:function(a,e){try{a=s(a),a.focus(),e&&a.select&&a.select()}catch(b){}},setSelectionRange:function(a,e,b){3>arguments.length&&(b=e);if(a.setSelectionRange)a.setSelectionRange(e,b);else if(a.createTextRange){var h=a.createTextRange();h.collapse(!0);h.moveStart("character",e);h.moveEnd("character",b-e);h.select()}},getSelectionStart:function(a){return"undefined"!=typeof a.selectionStart?
a.selectionStart:i(!0)},getSelectionEnd:function(a){return"undefined"!=typeof a.selectionEnd?a.selectionEnd:i(!1)}})})(basis,this);
(function(j,m){function v(a){return a||m.event}function w(a){return"string"==typeof a?y.get(a):a}function s(a){a=v(a);a.stopPropagation?a.stopPropagation():a.cancelBubble=!0}function D(a){a=v(a);a.preventDefault?a.preventDefault():a.returnValue=!1}function E(a){var b=Array.from(q[a.type]);if(b)for(var c=b.length;0<c--;){var d=b[c];d.handler.call(d.thisObject,a)}}function u(a,b,c,d){a=w(a);if(!a)throw Error("Event.addHandler: can't attach event listener to undefined");if("function"!=typeof c)throw Error("Event.addHandler: handler must be a function");
a[C]||(a[C]={});var f={handler:c,thisObject:d},g=a[C],e=g[b];if(e){for(a=0;b=e[a];a++)if(b.handler===c&&b.thisObject===d)return;e.push(f)}else e=g[b]=[f],e.fireEvent=function(a){a=v(a);if(z&&a&&"undefined"==typeof a.returnValue){E(a);if(!0===a.cancelBubble)return;if("undefined"==typeof a.returnValue)a.returnValue=!0}for(var b=0,c;c=e[b++];)c.handler.call(c.thisObject,a)},a.addEventListener?a.addEventListener(b,e.fireEvent,!1):a.attachEvent("on"+b,e.fireEvent)}function n(a,b,c,d){var a=w(a),f=a[C];
if(f&&(f=f[b]))for(var g=0,e;e=f[g];g++)if(e.handler===c&&e.thisObject===d){f.splice(g,1);f.length||r(a,b);break}}function r(a,b){var a=w(a),c=a[C];if(c)if("string"!=typeof b)for(b in c)r(a,b);else{var d=c[b];d&&(a.removeEventListener?a.removeEventListener(b,d.fireEvent,!1):a.detachEvent("on"+b,d.fireEvent),delete c[b])}}var i=m.document,y=j.dom,t=Function.$null,C="__basisEvents",B={mousewheel:["mousewheel","DOMMouseScroll"]},q={},z=!i.addEventListener,x=function(){function a(){b++||setTimeout(function(){for(var a=
0;a<c.length;a++)c[a].callback.call(c[a].thisObject)},10)}var b=!1,c=[];if(j.ua.is("ie7-"))(function(){var b="_"+Date.now();i.write('<script id="'+b+'" defer src="//:"><\/script>');w(b).onreadystatechange=function(){"complete"==this.readyState&&(y.remove(this),a())}})();else if(j.ua.is("safari525-"))var d=setInterval(function(){/loaded|complete/.test(i.readyState)&&(clearInterval(d),a())},15);else u(i,"DOMContentLoaded",a,!1);u(i,"load",a,!1);u(m,"load",a,!1);return function(a,d){b||c.push({callback:a,
thisObject:d})}}();return j.namespace("basis.dom.event",v).extend({KEY:{BACKSPACE:8,TAB:9,CTRL_ENTER:10,ENTER:13,SHIFT:16,CTRL:17,ALT:18,ESC:27,ESCAPE:27,SPACE:32,PAGEUP:33,PAGEDOWN:34,END:35,HOME:36,LEFT:37,UP:38,RIGHT:39,DOWN:40,INSERT:45,DELETE:46,F5:116},MOUSE_LEFT:{VALUE:1,BIT:1},MOUSE_RIGHT:{VALUE:3,BIT:2},MOUSE_MIDDLE:{VALUE:2,BIT:4},browserEvents:function(a){return B[a]||[a]},Handler:function(a,b){this.handler=a;this.thisObject=b},sender:function(a){a=v(a);return a.target||a.srcElement},cancelBubble:s,
cancelDefault:D,kill:function(a,b){(b=w(b))?u(b,a,Event.kill):(D(a),s(a))},key:function(a){a=v(a);return a.keyCode||a.which||0},charCode:function(a){a=v(a);return a.charCode||a.keyCode||0},mouseButton:function(a,b){a=v(a);return"number"==typeof a.which?a.which==b.VALUE:a.button&b.BIT},mouseX:function(a){a=v(a);return a.changedTouches?a.changedTouches[0].pageX:"pageX"in a?a.pageX:a.clientX+(i.documentElement.scrollLeft||i.body.scrollLeft)},mouseY:function(a){a=v(a);return a.changedTouches?a.changedTouches[0].pageY:
"pageY"in a?a.pageY:a.clientY+(i.documentElement.scrollTop||i.body.scrollTop)},wheelDelta:function(a){a=v(a);return"wheelDelta"in a?a.wheelDelta/120:"DOMMouseScroll"==a.type?-a.detail/3:0},addGlobalHandler:function(a,b,c){var d=q[a];if(d)for(a=d.length;0<a--;){var f=d[a];if(f.handler===b&&f.thisObject===c)return}else i.addEventListener?i.addEventListener(a,E,!0):u(i,a,t),d=q[a]=[];d.push({handler:b,thisObject:c})},removeGlobalHandler:function(a,b,c){var d=q[a];if(d)for(var f=0,g;g=d[f];f++)if(g.handler===
b&&g.thisObject===c){d.splice(f,1);d.length||(delete q[a],i.removeEventListener?i.removeEventListener(a,E,!0):n(i,a,t));break}},addHandler:u,addHandlers:function(a,b,c){var a=w(a),d;for(d in b)u(a,d,b[d],c)},removeHandler:n,clearHandlers:r,fireEvent:function(a,b){var a=w(a),c=a[C];c&&c[b]&&c[b].fireEvent()},onLoad:x,onUnload:function(a,b){u(m,"unload",a,b)}})})(basis,this);
(function(){function j(a,b,c){for(var d=1,f;b;)b&1&&(f=C[d],c&d?(a.addHandler(f.handler,f.context),f.action(f.context.add,a)):(a.removeHandler(f.handler,f.context),f.action(f.context.remove,a))),b>>=1,d<<=1}function m(a,b){var c={},d;if(a&&a.length)d=c.inserted=a;if(b&&b.length)d=c.deleted=b;if(d)return c}function v(a){return Array.isArray(a)?a.map(v):{data:a}}var w=basis.Class,s=basis.EventObject,D=Object.values,E=Function.$self,u=Function.$true,n=Function.$false,r=s.createEvent,i=s.event,y={},t=
[],C={},B=1,q={NONE:0,MASK:0,regType:function(a,b,c){C[B]={handler:b,action:c,context:{add:function(b,h){if(h){var c=q[a]+"_"+b.eventObjectId;if(!h.subscribers_)h.subscribers_={};if(!h.subscribers_[c]){var d=h.subscriberCount;h.subscribers_[c]=b;h.subscriberCount+=1;h.event_subscribersChanged(h,d)}}},remove:function(b,h){if(h){var c=q[a]+"_"+b.eventObjectId;if(h.subscribers_[c]){var d=h.subscriberCount;delete h.subscribers_[c];h.subscriberCount-=1;h.event_subscribersChanged(h,d)}}}}};q[a]=B;q.MASK|=
B;B<<=1}};q.regType("DELEGATE",{delegateChanged:function(a,b){this.remove(a,b);this.add(a,a.delegate)}},function(a,b){a(b,b.delegate)});q.regType("TARGET",{targetChanged:function(a,b){this.remove(a,b);this.add(a,a.target)}},function(a,b){a(b,b.target)});q.regType("SOURCE",{sourceChanged:function(a,b){this.remove(a,b);this.add(a,a.source)},sourcesChanged:function(a,b){var c;if(c=b.inserted)for(var d=c.length;0<d--;)this.add(a,c[d]);if(c=b.deleted)for(d=c.length;0<d--;)this.remove(a,c[d])}},function(a,
b){for(var c=b.sources||[b.source],d=0,f;f=c[d++];)a(b,f)});var z=w(s,{state:"ready",data:null,canHaveDelegate:!0,delegate:null,root:null,cascadeDestroy:!1,isTarget:!1,target:null,active:!1,subscribeTo:q.DELEGATE+q.TARGET,subscriberCount:0,subscribers_:null,event_update:r("update","object","delta"),event_stateChanged:r("stateChanged","object","oldState"),event_delegateChanged:r("delegateChanged","object","oldDelegate"),event_rootChanged:r("rootChanged","object","oldRoot"),event_targetChanged:r("targetChanged",
"object","oldTarget")&&function(a,b){var c=this.listen.target;c&&(b&&b.removeHandler(c,this),this.target&&this.target.addHandler(c,this));i.targetChanged.call(this,a,b)},event_subscribersChanged:r("subscribersChanged","object"),event_activeChanged:r("activeChanged","object"),listen:{delegate:{update:function(a,b){this.data=a.data;this.event_update(this,b)},stateChanged:function(a,b){this.state=a.state;this.event_stateChanged(this,b)},targetChanged:function(a,b){this.target=a.target;this.event_targetChanged(this,
b)},rootChanged:function(a,b){this.data=a.data;this.event_rootChanged(this,b)},destroy:function(){this.cascadeDestroy?this.destroy():this.setDelegate()}}},init:function(a){s.prototype.init.call(this,a);if(a=this.delegate)this.delegate=null,this.data=a.data,this.state=a.state,this.setDelegate(a);else{this.root=this;if(!this.data)this.data={};if(this.isTarget)this.target=this}this.active&&j(this,this.subscribeTo,q.MASK)},isConnected:function(a){if(a instanceof z){for(;a&&a!==this&&a!==a.delegate;)a=
a.delegate;return a===this}return!1},getRootDelegate:function(){for(var a=this;a.delegate&&a.delegate!==a;)a=a.delegate;return a},setDelegate:function(a){if(this.canHaveDelegate&&a&&a instanceof z){if(a.delegate&&this.isConnected(a))return!1}else a=null;if(this.delegate!==a){var b=this.state,c=this.data,d=this.delegate,f=this.target,g=this.root,i={};d&&d.removeHandler(this.listen.delegate,this);if(a){this.delegate=a;this.root=a.root;this.data=a.data;this.state=a.state;this.target=a.target;a.addHandler(this.listen.delegate,
this);for(var k in a.data)!1===k in c&&(i[k]=void 0);for(k in c)c[k]!==a.data[k]&&(i[k]=c[k])}else for(k in this.target=this.delegate=null,this.root=this,this.data={},c)this.data[k]=c[k];this.event_delegateChanged(this,d);this.root!==g&&this.event_rootChanged(this,g);this.target!==f&&this.event_targetChanged(this,f);if(a){for(k in i){this.event_update(this,i);break}b!==this.state&&(""+b!=this.state||b.data!==this.state.data)&&this.event_stateChanged(this,b)}return!0}return!1},setState:function(a,
b){var c=this.target||this.getRootDelegate();if(c!==this)return c.setState(a,b);return this.state!=""+a||this.state.data!=b?(c=this.state,this.state=Object(""+a),this.state.data=b,this.event_stateChanged(this,c),!0):!1},deprecate:function(){"processing"!=this.state&&this.setState("deprecated")},update:function(a){var b=this.target||this.getRootDelegate();if(b!==this)return b.update(a);if(a){var b={},c=0,d;for(d in a)this.data[d]!==a[d]&&(c++,b[d]=this.data[d],this.data[d]=a[d]);if(c)return this.event_update(this,
b),b}return!1},setActive:function(a){a=!!a;return this.active!=a?(this.active=a,this.event_activeChanged(this),j(this,this.subscribeTo,q.MASK*a),!0):!1},setSubscription:function(a){var a=a&q.MASK,b=this.subscribeTo^a;return b?(this.subscribeTo=a,this.active&&j(this,b,a),!0):!1},destroy:function(){this.active&&j(this,this.subscribeTo,0);this.delegate&&this.setDelegate();s.prototype.destroy.call(this);this.data=y;this.state="undefined";this.target=this.root=null}}),x=w(null,{itemClass:z,keyGetter:E,
map_:null,extendConstructor_:!0,init:function(){this.map_={};basis.Cleaner.add(this)},resolve:function(a){return this.get(this.keyGetter(a),a)},create:function(a){var b={};a instanceof z?b.delegate=a:b.data={id:a,title:a};return new this.itemClass(b)},get:function(a,b){var c=a instanceof z?a.eventObjectId:a,d=this.map_[c];!d&&b&&(d=this.map_[c]=this.create(a,b),d.addHandler({destroy:function(){delete this.map_[c]}},this));return d},destroy:function(){basis.Cleaner.remove(this);for(var a=D(this.map_),
b=0,c;c=a[b++];)c.destroy()}}),a=w(z,{state:"undefined",itemCount:0,item_:null,memberMap_:null,cache_:null,event_datasetChanged:r("datasetChanged","dataset","delta")&&function(a,b){var c,d=0,f=0,g;if(c=b.inserted)for(;g=c[d];)this.item_[g.eventObjectId]=g,d++;if(c=b.deleted)for(;g=c[f];)delete this.item_[g.eventObjectId],f++;this.itemCount+=d-f;this.cache_=null;i.datasetChanged.call(this,a,b)},init:function(a){z.prototype.init.call(this,a);this.memberMap_={};this.item_={}},has:function(a){return!(!a||
!this.item_[a.eventObjectId])},getItems:function(){if(!this.cache_)this.cache_=D(this.item_);return this.cache_},pick:function(){for(var a in this.item_)return this.item_[a];return null},top:function(a){var b=[];if(a)for(var c in this.item_)if(b.push(this.item_[c])>=a)break;return b},add:function(){},remove:function(){},set:function(){},sync:function(){},clear:function(){},destroy:function(){this.clear();z.prototype.destroy.call(this);this.cache_=t;this.itemCount=0;this.item_=this.memberMap_=null}}),
b=w(a,{listen:{item:{destroy:function(a){this.memberMap_[a.eventObjectId]&&this.remove([a])}}},init:function(b){a.prototype.init.call(this,b);if(b=this.items)this.set(b),this.items=null},add:function(a){for(var b,c=this.memberMap_,d=[],f=0;f<a.length;f++){var g=a[f];if(g instanceof z){var i=g.eventObjectId;c[i]||(c[i]=g,g.addHandler(this.listen.item,this),d.push(g))}}d.length&&this.event_datasetChanged(this,b={inserted:d});return b},remove:function(a){for(var b,c=this.memberMap_,d=[],f=0;f<a.length;f++){var g=
a[f];if(g instanceof z){var i=g.eventObjectId;c[i]&&(g.removeHandler(this.listen.item,this),delete c[i],d.push(g))}}d.length&&this.event_datasetChanged(this,b={deleted:d});return b},set:function(a){if(!this.itemCount)return this.add(a);if(!a.length)return this.clear();for(var b=this.memberMap_,c={},d=[],f=[],g,i,k,p=0;p<a.length;p++)if(g=a[p],g instanceof z)i=g.eventObjectId,c[i]=g,b[i]||(b[i]=g,g.addHandler(this.listen.item,this),f.push(g));for(i in b)c[i]||(g=b[i],g.removeHandler(this.listen.item,
this),delete b[i],d.push(g));(k=m(f,d))&&this.event_datasetChanged(this,k);return k},sync:function(a,c){if(a){b.setAccumulateState(!0);for(var d=this.memberMap_,f,g,i={},j=[],k,p=0;p<a.length;p++)if(f=a[p],f instanceof z)g=f.eventObjectId,i[g]=f,d[g]||j.push(f);for(g in this.item_)i[g]||this.item_[g].destroy();c&&j.length&&(k=this.add(j));b.setAccumulateState(!1);return k}},clear:function(){var a,b=this.getItems();if(b.length){for(a=b.length;0<a--;)b[a].removeHandler(this.listen.item,this);this.event_datasetChanged(this,
a={deleted:b});this.memberMap_={}}return a}});b.setAccumulateState=function(){function b(a){var k=a.dataset;g.call(k,k,a)}function c(a,d){var h=a.eventObjectId,f=d.inserted,l=d.deleted,i=k[h];if(f&&l)return i&&(delete k[h],b(i)),g.call(a,a,d);if(i){var o=i[f?"inserted":"deleted"];if(o)return o.push.apply(o,f||l);b(i)}k[h]=d;d.dataset=a}function d(){i=1;setAccumulateState(!1)}var f=a.prototype,g=f.event_datasetChanged,i=0,j,k={};return function(a){if(a){if(0==i)f.event_datasetChanged=c,j=setTimeout(d,
0);i++}else if(i-=0<i,0==i)clearTimeout(j),f.event_datasetChanged=g,a=k,k={},D(a).forEach(b)}}();var c=w(a,{subscribeTo:q.SOURCE,event_sourcesChanged:r("sourcesChanged","dataset","delta"),sources:null,rule:function(a){return 0<a},listen:{source:{datasetChanged:function(a,b){var c=this.memberMap_,d={},f,g;if(b.inserted)for(var i=0;f=b.inserted[i];i++)g=f.eventObjectId,c[g]?c[g].count++:c[g]={count:1,object:f},d[g]=c[g];if(b.deleted)for(i=0;f=b.deleted[i];i++)g=f.eventObjectId,d[g]=c[g],c[g].count--;
this.applyRule(d)},destroy:function(a){this.removeSource(a)}}},init:function(b){a.prototype.init.call(this,b);b=this.sources;this.sources=[];b&&b.forEach(this.addSource,this)},setRule:function(a){if("function"!=typeof a)a=c.UNION;if(this.rule!==a)this.rule=a,this.applyRule()},applyRule:function(a){var b=this.memberMap_,c=this.rule,d=this.sources.length,f=[],g=[],i,k,p;a||(a=b);for(var A in a)i=b[A],k=d&&i.count&&c(i.count,d),k!=!!this.item_[A]&&(k?f:g).push(i.object),0==i.count&&delete b[A];(p=m(f,
g))&&this.event_datasetChanged(this,p)},addSource:function(b){if(b instanceof a&&this.sources.add(b)){b.addHandler(this.listen.source,this);var c=this.memberMap_,d;for(d in b.item_)c[d]?c[d].count++:c[d]={count:1,object:b.item_[d]};this.applyRule();this.event_sourcesChanged(this,{inserted:[b]});return!0}},removeSource:function(a){if(this.sources.remove(a)){a.removeHandler(this.listen.source,this);var b=this.memberMap_,c;for(c in a.item_)b[c].count--;this.applyRule();this.event_sourcesChanged(this,
{deleted:[a]});return!0}},setSources:function(b){for(var c=Array.from(this.sources),d=0,f;f=b[d];d++)f instanceof a&&(c.remove(f)||this.addSource(f));c.forEach(this.removeSource,this)},clear:function(){Array.from(this.sources).forEach(this.removeSource,this)},destroy:function(){a.prototype.destroy.call(this);this.sources=null}});c.UNION=c.prototype.rule;c.INTERSECTION=function(a,b){return a==b};c.DIFFERENCE=function(a){return 1==a};c.MORE_THAN_ONE_INCLUDE=function(a,b){return 1==b||1<a};c.AT_LEAST_ONE_EXCLUDE=
function(a,b){return 1==b||a<b};var d=function(a){return!this.has(a)},f=w(a,{minuend:null,subtrahend:null,listen:{minuend:{datasetChanged:function(a,b){if(this.subtrahend){var c=m(b.inserted&&b.inserted.filter(d,this.subtrahend),b.deleted&&b.deleted.filter(this.has,this));c&&this.event_datasetChanged(this,c)}},destroy:function(){this.setOperands(null,this.subtrahend)}},subtrahend:{datasetChanged:function(a,b){if(this.minuend){var c=m(b.deleted&&b.deleted.filter(d,this),b.inserted&&b.inserted.filter(this.has,
this));c&&this.event_datasetChanged(this,c)}},destroy:function(){this.setOperands(this.minuend,null)}}},init:function(b){a.prototype.init.call(this,b);var b=this.minuend,c=this.subtrahend;this.subtrahend=this.minuend=null;(b||c)&&this.setOperands(b,c)},setOperands:function(b,c){var d;!1==b instanceof a&&(b=null);!1==c instanceof a&&(c=null);var f=this.minuend,g=this.subtrahend;if(f!==b)f&&f.removeHandler(this.listen.minuend,this),(this.minuend=b)&&b.addHandler(this.listen.minuend,this);if(g!==c)g&&
g.removeHandler(this.listen.subtrahend,this),(this.subtrahend=c)&&c.addHandler(this.listen.subtrahend,this);if(!b||!c)this.itemCount&&this.event_datasetChanged(this,d={deleted:this.getItems()});else{var f=[],g=[],i;for(i in this.item_)(!b.item_[i]||c.item_[i])&&f.push(this.item_[i]);for(i in b.item_)!this.item_[i]&&!c.item_[i]&&g.push(b.item_[i]);(d=m(g,f))&&this.event_datasetChanged(this,d)}return d},clear:function(){this.setOperands()}}),g=w(a,{source:null,event_sourceChanged:r("sourceChanged",
"dataset","oldSource"),map:E,reduce:n,rule:n,addMemberRef:null,removeMemberRef:null,sourceMap_:null,listen:{sourceObject:{update:function(a){var b=this.map?this.map(a):a;if(!1==b instanceof z||this.reduce(b))b=null;var c=this.sourceMap_[a.eventObjectId],d=c.member;if(d!=b){var f=this.memberMap_,g,i,k;c.member=b;if(d)c=d.eventObjectId,this.removeMemberRef&&this.removeMemberRef(d,a),0==--f[c]&&(delete f[c],k=[d]);if(b)d=b.eventObjectId,this.addMemberRef&&this.addMemberRef(b,a),f[d]?f[d]++:(f[d]=1,i=
[b]);(g=m(i,k))&&this.event_datasetChanged(this,g)}}},source:{datasetChanged:function(a,c){var d=this.sourceMap_,f=this.memberMap_,g=[],i=[],j,k,p;b.setAccumulateState(!0);if(c.inserted)for(var A=0;j=c.inserted[A];A++){p=this.map?this.map(j):j;if(!1==p instanceof z||this.reduce(p))p=null;j.addHandler(this.listen.sourceObject,this);d[j.eventObjectId]={sourceObject:j,member:p};if(p)k=p.eventObjectId,f[k]?f[k]++:(f[k]=1,g.push(p)),this.addMemberRef&&this.addMemberRef(p,j)}if(c.deleted)for(A=0;j=c.deleted[A];A++)if(k=
j.eventObjectId,p=d[k].member,j.removeHandler(this.listen.sourceObject,this),delete d[k],p)k=p.eventObjectId,0==--f[k]&&(delete f[k],i.push(p)),this.removeMemberRef&&this.removeMemberRef(p,j);b.setAccumulateState(!1);(c=m(g,i))&&this.event_datasetChanged(this,c)},destroy:function(){this.setSource()}}},init:function(b){a.prototype.init.call(this,b);this.sourceMap_={};if(b=this.source)this.source=null,this.setSource(b)},setRule:function(a){"function"!=typeof a&&(a=u);if(this.rule!==a)return this.rule=
a,this.applyRule()},setMap:function(a){"function"!=typeof a&&(a=E);if(this.map!==a)return this.map=a,this.applyRule()},setSource:function(b){!1==b instanceof a&&(b=null);if(this.source!==b){var c=this.source;c&&(c.removeHandler(this.listen.source,this),this.listen.source.datasetChanged.call(this,c,{deleted:c.getItems()}));if(this.source=b)b.addHandler(this.listen.source,this),this.listen.source.datasetChanged.call(this,b,{inserted:b.getItems()});this.event_sourceChanged(this,c)}},applyRule:function(){var a=
this.sourceMap_,b=this.memberMap_,c,d,f,g,i,k=[],p=[],A,K;for(K in a){i=a[K];g=i.sourceObject;c=i.member;d=this.map?this.map(g):g;if(!1==d instanceof z||this.reduce(d))d=null;if(c!=d){i.member=d;if(c)f=c.eventObjectId,this.removeMemberRef&&this.removeMemberRef(c,g),b[f]--;if(d)c=d.eventObjectId,this.addMemberRef&&this.addMemberRef(d,g),c in b?b[c]++:(b[c]=1,k.push(d))}}for(f in this.item_)0==b[f]&&(delete b[f],p.push(this.item_[f]));(A=m(k,p))&&this.event_datasetChanged(this,A);return A},clear:function(){this.setSource()},
destroy:function(){a.prototype.destroy.call(this);this.sourceMap_=null}}),n=w(g,{reduce:function(a){return!this.rule(a)},rule:u}),w=w(g,{map:function(a){return this.keyMap.resolve(a)},rule:u,subsetClass:a,keyMap:null,addMemberRef:function(a,b){a.event_datasetChanged(a,{inserted:[b]})},removeMemberRef:function(a,b){a.event_datasetChanged(a,{deleted:[b]})},init:function(a){if(!this.keyMap||!1==this.keyMap instanceof x)this.keyMap=new x(Object.extend({keyGetter:this.rule,itemClass:this.subsetClass},
this.keyMap));g.prototype.init.call(this,a)},getSubset:function(a,b){return this.keyMap.get(a,b)},destroy:function(){g.prototype.destroy.call(this);this.keyMap.destroy();this.keyMap=null}});Object.extend(b,{Merge:c,Subtract:f,MapReduce:g,Subset:n,Split:w});basis.namespace("basis.data",v).extend({STATE:{UNDEFINED:"undefined",READY:"ready",PROCESSING:"processing",ERROR:"error",DEPRECATED:"deprecated"},Subscription:q,Object:z,DataObject:z,KeyObjectMap:x,AbstractDataset:a,Dataset:b,AggregateDataset:c,
Collection:n,Grouping:w});basis.namespace("basis.data.dataset").extend({Merge:c,Subtract:f,MapReduce:g,Subset:n,Split:w})})(basis,this);
(function(j,m){function v(a,c,d,f){for(var c=c.split(/\{([a-z0-9\_]+(?:\|[^}]*)?)\}/i),g=q(),e,h=0;h<c.length;h++)h%2?(e=c[h].split(/\|/),a.getters[e[0]]=d+"childNodes["+f+"]",e=1<e.length?e[1]:e[0]):e=c[h].length?c[h]:null,null!=e&&(B&&(g.lastChild&&g.appendChild(u.createComment("")),f++),g.appendChild(z(e)),f++);return g}function w(a){return function(c){if(!c||!("click"==c.type&&3==c.which)){var d=j.dom.event.sender(c),f,g;do if(f=d.getAttributeNode&&d.getAttributeNode(a))break;while(d=d.parentNode);
if(d&&f){do if(g=d.basisObjectId)if((g=y[g])&&g.templateAction){d=f.nodeValue.qw();f=0;for(var e;e=d[f++];)g.templateAction(e,j.dom.event(c));break}while(d=d.parentNode)}}}}function s(a,c,d){c=c.trim();if(!c)return"";for(var f="",g;g=C.exec(c);){var e=g[2],h=g[4]||g[5]||e;g[3]&&(a.getters[g[3]]=d+'.getAttributeNode("'+e+'")');if(g=e.match(/^event-([a-z]+)/i)){var l=g[1];if(!i[l]){i[l]=!0;g=0;for(var l=j.dom.event.browserEvents(l),m;m=l[g++];)j.dom.event.addGlobalHandler(m,w(e))}if(!window.__basis_emitEvent)window.__basis_emitEvent=
function(a,b){var a=j.dom.event(a),c=this,k;do if(k=c.basisObjectId)if((k=y[k])&&k.templateAction){for(var c=b.qw(),p=0,d;d=c[p++];)k.templateAction(d,j.dom.event(a));break}while(c=c.parentNode)}}f+="class"==e?h.trim().replace(/^(.)|\s+/g,".$1"):"["+e+(h?"="+h.quote('"'):"")+"]"}return f}function D(a,c){if(!a.stack)a.stack=[];if(!a.source)a.source=a.str;c||(c=".");for(var d=q(),f,g=0,e,h=a.stack;e=t.exec(a.str);){f=RegExp.leftContext;a.str=a.str.substr(f.length+e[0].length);if(f.length)d.appendChild(v(a,
f,c,g)),g=d.childNodes.length;if(e[5]){if(e[5]==h[h.length-1])return h.pop(),d;throw"Wrong end tag";}if(e[6])e[7]&&(a.getters[e[7]]=c+"childNodes["+g+"]"),d.appendChild(u.createComment(e[6]));else{f=e[1];var i=e[2],j=!!e[4],m=c+"childNodes["+g+"]";e=n.createElement(f+s(a,e[3],m));i&&(a.getters[i]=m);j||(h.push(f),e.appendChild(D(a,m+".")));d.appendChild(e)}g++}a.str.length&&d.appendChild(v(a,a.str,c,g));if(h.length)throw"No end tag for "+h.reverse();return d}function E(a){if(!this.proto){a=this.source;
if("function"==typeof a)this.source=a=a();for(var a=a.trim(),a={str:a,getters:{element:".childNodes[0]"}},c=D(a),a=Object.iterate(a.getters,function(a,b){for(var d=a.split(/\|/).map(String.format,"obj_.{0}"),e=b.split(/(\.?childNodes\[(\d+)\])/),f=c,g=0;g<e.length;g+=3){var k=e[g+2];if(!k)break;e[g+2]="";f=f.childNodes[k];f.previousSibling?f.nextSibling||(e[g+1]=".lastChild"):e[g+1]=".firstChild"}return{name:d[0],alias:d.join("="),path:"dom_"+e.join("")}}).sortAsObject("path"),d=0;d<a.length;d++)for(var f=
RegExp("^"+a[d].path.forRegExp()),g=d+1,e;e=a[g++];)e.path=e.path.replace(f,a[d].name);this.createInstance=(new Function("proto_","map_","var obj_, dom_; return "+function(a,b){obj_=a||{};dom_=proto_.cloneNode(!0);_code_();if(b&&obj_.element){var c=obj_.element.basisObjectId=map_.seed++;map_[c]=b}return obj_}.toString().replace("_code_()",a.map(String.format,"{alias}={path};\n").join(""))))(c,y);this.clearInstance=(new Function("map_","var obj_; return "+function(a){obj_=a;(a=obj_.element&&obj_.element.basisObjectId)&&
delete map_[a];_code_()}.toString().replace("_code_()",a.map(String.format,"{alias}=null;\n").join(""))))(y)}}var u=m.document,n=j.dom,r=j.Class,i={},y={seed:1},t=/<([a-z0-9\_]+)(?:\{([a-z0-9\_\|]+)\})?([^>]*?)(\/?)>|<\/([a-z0-9\_]+)>|<\!--(\s*\{([a-z0-9\_\|]+)\}\s*|.*?)--\>/i,C=/(?:([a-z0-9\_\-]+):)?([a-z0-9\_\-]+)(?:\{([a-z0-9\_\|]+)\})?(?:="((?:\\.|[^"])*?)"|='((?:\\.|[^'])*?)')?\s*/gi;n.createFragment();var B=1==n.createElement("","a","b").cloneNode(!0).childNodes.length,q=n.createFragment,z=
n.createText,x=r(null,{__extend__:function(a){return a instanceof x?a:new x(a)},init:function(a){this.source=a},createInstance:function(a,c){E.call(this);return this.createInstance(a,c)},clearInstance:function(){E.call(this)}}),a=u.createElement("DIV");return j.namespace("basis.html").extend({Template:x,escape:function(a){return n.createElement("DIV",n.createText(a)).innerHTML},unescape:function(b){a.innerHTML=b;return a.firstChild.nodeValue},string2Html:function(b){a.innerHTML=b;return n.createFragment.apply(null,
Array.from(a.childNodes))}})})(basis,this);
(function(j){function m(a){return a.sortingValue||0}function v(a,b){a=a.sortingValue||0;b=b.sortingValue||0;return+(a>b)||-(a<b)}function w(a,b){a=a.sortingValue||0;b=b.sortingValue||0;return-(a>b)||+(a<b)}function s(a){return a.childNodes.sort(a.localSortingDesc?w:v)}function D(a,b){var c=b.length-1;a.childNodes=b;a.firstChild=b[0]||null;a.lastChild=b[c]||null;for(var d=c;c=b[d];d--)c.nextSibling=b[d+1]||null,c.previousSibling=b[d-1]||null,a.insertBefore(c,c.nextSibling)}function E(a,b){var c=a.childFactory||
a.document&&a.document.childFactory,d,b=Object.extend({document:a.document,contextSelection:a.selection||a.contextSelection},b);if(c&&(d=c.call(a,b),d instanceof a.childClass))return d;if(!d)throw"basis.dom.wrapper: Child node is null";throw"basis.dom.wrapper: Child node has wrong class (expected "+(a.childClass&&a.childClass.className)+" but "+(d&&d.constructor&&d.constructor.className)+")";}function u(){return j.ui.apply(this,arguments)}var n=j.Class,r=j.dom,i=j.data,y=i.Subscription,t=i.DataObject,
C=i.AbstractDataset,B=i.Dataset,q=r.AXIS_DESCENDANT,z=r.AXIS_DESCENDANT_OR_SELF,x=Function.getter,a=Object.complete,b=r.axis,i=j.EventObject.createEvent,c=j.EventObject.event;y.regType("DATASOURCE",{dataSourceChanged:function(a,b){this.remove(a,b);this.add(a,a.dataSource)}},function(a,b){a(b,b.dataSource)});var d=n.ExtensibleProperty(),f={ownerChanged:function(){},destroy:function(a){r.replace(a.element,this)}},g=function(){var a=this.key,b=this.config,c=this.owner,d="function"!=typeof b.existsIf||
b.existsIf(c),e=c.satellite[a];if(d){var d="delegate"in b,g="dataSource"in b,h="function"==typeof b.delegate?b.delegate(c):null,i="function"==typeof b.dataSource?b.dataSource(c):null;if(e)d&&e.setDelegate(h),g&&e.setDataSource(i);else{var H=c.tmpl[b.replace||a],e={owner:c};if(d)e.delegate=h;if(g)e.dataSource=i;b.config&&Object.complete(e,"function"==typeof b.config?b.config(c):b.config);e=new b.instanceOf(e);c.satellite[a]=e;H&&e instanceof j.ui.Node&&e.element&&(r.replace(H,e.element),e.addHandler(f,
H))}}else if(e)e.destroy(),e.owner=null,delete c.satellite[a]},e=n.CustomExtendProperty({update:!0},function(a,b){for(var c in b)a[c]=b[c]?g:null}),h=n(t,{event_update:function(a,b){t.prototype.event_update.call(this,a,b);var c=this.parentNode;c&&(c.matchFunction&&(this.match(),this.match(c.matchFunction)),c.insertBefore(this,this.nextSibling))},event_childNodesModified:i("childNodesModified","node","delta"),event_dataSourceChanged:i("dataSourceChanged","node","oldDataSource"),event_localGroupingChanged:i("localGroupingChanged",
"node","oldGroupingNode"),event_localSortingChanged:i("localSortingChanged","node","oldLocalSorting","oldLocalSortingDesc"),event_ownerChanged:i("ownerChanged","node","oldOwner"),event_satellitesChanged:i("satellitesChanged","node","delta"),subscribeTo:t.prototype.subscribeTo+y.DATASOURCE,listen:{owner:{destroy:function(){this.setOwner()}}},autoDelegateParent:!1,nodeType:"DOMWrapperNode",canHaveChildren:!1,childNodes:null,dataSource:null,colMap_:null,destroyDataSourceMember:!0,document:null,parentNode:null,
nextSibling:null,previousSibling:null,firstChild:null,lastChild:null,localSorting:null,localSortingDesc:!1,localGrouping:null,localGroupingClass:null,groupNode:null,satelliteConfig:d,satellite:null,owner:null,init:function(a){var b=this.dataSource,c=this.childNodes,f=this.localGrouping;if(b)this.dataSource=null;t.prototype.init.call(this,a);if(f)this.localGrouping=null,this.setLocalGrouping(f);if(this.canHaveChildren)this.childNodes=[],b?(this.dataSource=null,this.setDataSource(b)):c&&this.setChildNodes(c);
else{if(c)this.childNodes=null;if(b)this.dataSource=null}if(!this.satellite)this.satellite={};if(this.satelliteConfig!==d)for(var h in this.satelliteConfig)if(a=this.satelliteConfig[h],n.isClass(a)&&(a={instanceOf:a}),"object"==typeof a){b={key:h,owner:this,config:a};a=a.hook?e.__extend__(a.hook):e;for(h in a)if(a[h]===g){this.addHandler(a,b);break}g.call(b)}if(h=this.owner)this.owner=null,this.setOwner(h)},appendChild:function(){},insertBefore:function(){},removeChild:function(){},replaceChild:function(){},
clear:function(){},hasChildNodes:function(){return 0<this.childNodes.length},setChildNodes:function(){},setLocalGrouping:function(){},setLocalSorting:function(){},setDataSource:function(){},setOwner:function(a){if(!a||!1==a instanceof h)a=null;if(this.owner!==a){var b=this.owner;b&&b.removeHandler(this.listen.owner,this);(this.owner=a)&&a.addHandler(this.listen.owner,this);this.event_ownerChanged(this,b)}},destroy:function(){t.prototype.destroy.call(this);this.dataSource?this.setDataSource():this.firstChild&&
this.clear();this.parentNode&&this.parentNode.removeChild(this);if(this.localGrouping)this.localGrouping.destroy(),this.localGrouping=null;this.owner&&this.setOwner();if(this.satellite){for(var a in this.satellite){var b=this.satellite[a];b.destroy();b.owner=null}this.satellite=null}this.lastChild=this.firstChild=this.nextSibling=this.previousSibling=this.parentNode=this.childNodes=this.document=null}}),l=n(h,{autoDestroyIfEmpty:!1,nodes:null,first:null,last:null,init:function(a){this.nodes=[];h.prototype.init.call(this,
a)},insert:function(a,b){var c=this.nodes,d=b?c.indexOf(b):-1;-1==d?(c.push(a),this.last=a):c.splice(d,0,a);this.first=c[0];a.groupNode=this;this.event_childNodesModified(this,{inserted:[a]})},remove:function(a){var b=this.nodes;if(b.remove(a))this.first=b[0]||null,this.last=b[b.length-1]||null,a.groupNode=null,this.event_childNodesModified(this,{deleted:[a]});!this.first&&this.autoDestroyIfEmpty&&this.destroy()},clear:function(){if(this.first){for(var a=this.nodes,b=a.length;0<b--;)a[b].groupNode=
null;this.nodes=[];this.last=this.first=null;this.event_childNodesModified(this,{deleted:a});this.autoDestroyIfEmpty&&this.destroy()}},destroy:function(){h.prototype.destroy.call(this);this.last=this.first=this.nodes=null}}),o={canHaveChildren:!0,childClass:h,childFactory:null,listen:{dataSource:{datasetChanged:function(a,b){var c={},d=[];if(b.deleted)if(c.deleted=d,this.childNodes.length==b.deleted.length){d.push.apply(d,this.childNodes);var e=this.dataSource;this.dataSource=null;this.clear(!0);
this.dataSource=e;this.colMap_={}}else for(var e=0,f;f=b.deleted[e];e++){f=f.eventObjectId;var g=this.colMap_[f];delete this.colMap_[f];g.canHaveDelegate=!0;this.removeChild(g);d.push(g)}if(b.inserted){c.inserted=[];for(e=0;f=b.inserted[e];e++)g=E(this,{cascadeDestroy:!1,delegate:f}),g.canHaveDelegate=!1,this.colMap_[f.eventObjectId]=g,c.inserted.push(g),this.firstChild&&this.insertBefore(g)}this.firstChild?this.event_childNodesModified(this,c):this.setChildNodes(c.inserted);if(this.destroyDataSourceMember&&
d.length)for(e=0;f=d[e];e++)f.destroy()},destroy:function(a){this.dataSource===a&&this.setDataSource()}}},appendChild:function(a){return this.insertBefore(a)},insertBefore:function(a,c){if(!this.canHaveChildren)throw"basis.dom.wrapper: Node can't be inserted at specified point in hierarchy";if(a.firstChild){var d=this;do if(d==a)throw"basis.dom.wrapper: Node can't be inserted at specified point in hierarchy";while(d=d.parentNode)}if(this.dataSource&&!this.dataSource.has(a.delegate))throw"basis.dom.wrapper: Operation is not allowed because node is under dataSource control";
!1==a instanceof this.childClass&&(a=E(this,a instanceof t?{delegate:a}:a));var e=a.parentNode===this,f=a.groupNode,g=this.localGrouping,h=this.localSorting,i,H=this.childNodes,j,I,l=null,d=-1,o=!1,n;if(e)n=a.nextSibling,I=a.previousSibling;if(h&&(c=null,i=this.localSortingDesc,j=h(a)||0,e))if(j===a.sortingValue)o=!0;else if((!n||(i?n.sortingValue<=j:n.sortingValue>=j))&&(!I||(i?I.sortingValue>=j:I.sortingValue<=j)))a.sortingValue=j,o=!0;if(g){l=g.getGroupNode(a);I=l.nodes;if(f===l&&(o||e&&n===c))return a;
h?o?d=n&&n.groupNode===l?I.indexOf(n):I.length:(d=I.binarySearchPos(j,m,i),a.sortingValue=j):d=c&&c.groupNode===l?I.indexOf(c):I.length;if(d<I.length)c=I[d];else if(l.last)c=l.last.nextSibling;else{d=l;for(c=null;(d=d.nextSibling)&&!(c=d.first););}if(a===c||e&&a.nextSibling===c)return f!==l&&(f&&f.remove(a),l.insert(a)),a;d=-1}else if(h){if(o)return a;d=H.binarySearchPos(j,m,i);c=H[d];a.sortingValue=j;if(a===c||e&&n===c)return a}else{if(c&&c.parentNode!==this)throw"basis.dom.wrapper: Node was not found";
if(e){if(n===c)return a;if(a===c)throw"basis.dom.wrapper: Node can't be inserted at specified point in hierarchy";}}e?(a.nextSibling?a.nextSibling.previousSibling=a.previousSibling:this.lastChild=a.previousSibling,a.previousSibling?a.previousSibling.nextSibling=a.nextSibling:this.firstChild=a.nextSibling,a.previousSibling=null,a.nextSibling=null,-1==d?H.remove(a):(i=H.indexOf(a),H.splice(i,1),i<d&&d--),f&&(f.remove(a),f=null)):a.parentNode&&a.parentNode.removeChild(a);f!=l&&l.insert(a,c);if(c){-1==
d&&(d=H.indexOf(c));if(-1==d)throw"basis.dom.wrapper: Node was not found";a.nextSibling=c;H.splice(d,0,a)}else d=H.length,H.push(a),c={previousSibling:this.lastChild},this.lastChild=a;a.parentNode=this;a.previousSibling=c.previousSibling;0==d?this.firstChild=a:c.previousSibling.nextSibling=a;c.previousSibling=a;var M=!1,r=!1,s=this.selection||this.contextSelection;if(!a.document&&a.document!==this.document)M=this.document,a.document=this.document;if(!a.contextSelection&&a.contextSelection!==s)a.contextSelection=
s,r=!a.selection,a.selected&&s.add([a]);a.firstChild&&(M||r)&&b(a,q).forEach(function(a){if(M&&!a.document)a.document=M;if(r&&!a.contextSelection)a.selected&&a.unselect(),a.contextSelection=s});e||(a.match&&a.match(this.matchFunction),a.autoDelegateParent&&a.setDelegate(this),this.dataSource||this.event_childNodesModified(this,{inserted:[a]}));return a},removeChild:function(a){if(null==a||a.parentNode!==this)throw"basis.dom.wrapper: Node was not found";if(!1==a instanceof this.childClass)throw"basis.dom.wrapper: Child node has wrong class";
if(this.dataSource&&this.dataSource.has(a))throw"basis.dom.wrapper: Operation is not allowed because node is under dataSource control";this.childNodes.splice(this.childNodes.indexOf(a),1);a.parentNode=null;a.nextSibling?a.nextSibling.previousSibling=a.previousSibling:this.lastChild=a.previousSibling;a.previousSibling?a.previousSibling.nextSibling=a.nextSibling:this.firstChild=a.nextSibling;a.nextSibling=null;a.previousSibling=null;a.document===this.document&&b(a,z).forEach(function(a){if(a.document==
this.document)a.document=null},this);if(a.contextSelection){for(var c=a.contextSelection,d=a,e=[];d;){if(d.contextSelection===c)d.selected&&e.push(d),d.contextSelection=null;if(!d.selection&&d.firstChild)d=d.firstChild;else if(d.nextSibling)d=d.nextSibling;else for(;d=d.parentNode;)if(d.nextSibling){d=d.nextSibling;break}}c.remove(e)}a.groupNode&&a.groupNode.remove(a);this.dataSource||this.event_childNodesModified(this,{deleted:[a]});a.autoDelegateParent&&a.setDelegate();return a},replaceChild:function(a,
b){if(this.dataSource)throw"basis.dom.wrapper: Operation is not allowed because node is under dataSource control";if(null==b||b.parentNode!==this)throw"basis.dom.wrapper: Node was not found";this.insertBefore(a,b);return this.removeChild(b)},clear:function(a){if(this.dataSource)this.setDataSource();else if(this.firstChild){var c=this.childNodes;this.lastChild=this.firstChild=null;this.childNodes=[];this.event_childNodesModified(this,{deleted:c});for(var d=c.length;0<d--;){var e=c[d];e.parentNode=
null;e.groupNode=null;a?((e.selection||e.document)&&b(e,r.AXIS_DESCENDANT_OR_SELF).forEach(function(a){if(this.selection&&a.selection===this.selection)a.selected&&a.selection.remove([a]),a.selection=null;if(a.document===this.document)a.document=null},this),e.nextSibling=null,e.previousSibling=null,e.autoDelegateParent&&e.setDelegate()):e.destroy()}if(this.localGrouping){a=this.localGrouping.childNodes;for(d=a.length-1;c=a[d];d--)c.clear()}}},setChildNodes:function(a,b){this.dataSource||this.clear(!!b);
if(a&&(!1=="length"in a&&(a=[a]),a.length)){var c=this.event_childNodesModified;this.event_childNodesModified=Function.$undef;for(var d=0,e=a.length;d<e;d++)this.insertBefore(a[d]);this.event_childNodesModified=c;this.event_childNodesModified(this,{inserted:this.childNodes})}},setDataSource:function(a){if(!a||!this.canHaveChildren||!1==a instanceof C)a=null;if(this.dataSource!==a){var b=this.dataSource;if(b)this.colMap_=this.dataSource=null,b.removeHandler(this.listen.dataSource,this),b.itemCount&&
this.clear();if(a)this.dataSource=a,this.colMap_={},a.addHandler(this.listen.dataSource,this),a.itemCount&&this.listen.dataSource.datasetChanged.call(this,a,{inserted:a.getItems()});this.event_dataSourceChanged(this,b)}},setLocalGrouping:function(a){if("function"==typeof a||"string"==typeof a)a={groupGetter:x(a)};!1==a instanceof G&&(a=null!=a&&"object"==typeof a?new this.localGroupingClass(Object.complete({},a)):null);if(this.localGrouping!==a){var b=this.localGrouping,c;if(this.localGrouping){if(!a&&
(this.localGrouping=null,this.firstChild)){c=this.localSorting?s(this):this.childNodes;for(var d=c.length;0<d--;)c[d].groupNode=null;D(this,c)}b.setOwner()}if(a&&(this.localGrouping=a,a.setOwner(this),this.firstChild)){c=this.localSorting?s(this):this.childNodes;for(d=0;a=c[d];d++)a.groupNode=this.localGrouping.getGroupNode(a);for(d=0;a=c[d];d++)a.groupNode.nodes.push(a);c.length=0;for(d=this.localGrouping.nullGroup;d;d=d.nextSibling)a=d.nodes,d.first=a[0]||null,d.last=a[a.length-1]||null,c.push.apply(c,
a),d.event_childNodesModified(d,{inserted:a});D(this,c)}this.event_localGroupingChanged(this,b)}},setLocalSorting:function(a,b){a&&(a=x(a));if(this.localSorting!=a||this.localSortingDesc!=!!b){var c=this.localSorting,d=this.localSortingDesc;this.localSortingDesc=!!b;this.localSorting=a||null;if(a&&this.firstChild){var e=[],f;for(f=this.firstChild;f;f=f.nextSibling)f.sortingValue=a(f)||0;if(this.localGrouping)for(var g=this.localGrouping.nullGroup;g;g=g.nextSibling)f=g.nodes=s({childNodes:g.nodes,
localSortingDesc:this.localSortingDesc}),g.first=f[0]||null,g.last=f[f.length-1]||null,e.push.apply(e,f);else e=s(this);D(this,e)}this.event_localSortingChanged(this,c,d)}},setMatchFunction:function(a){if(this.matchFunction!=a){this.matchFunction=a;for(var b=this.lastChild;b;b=b.previousSibling)b.match(a)}}},y=n(h,{event_enable:i("enable","node"),event_disable:i("disable","node"),event_select:i("select","node"),event_unselect:i("unselect","node"),event_match:i("match","node"),event_unmatch:i("unmatch",
"node"),selectable:!0,selected:!1,selection:null,contextSelection:null,matchFunction:null,matched:!0,disabled:!1,init:function(a){if(this.selection&&!1==this.selection instanceof C)this.selection=new J(this.selection);h.prototype.init.call(this,a);this.disabled&&this.event_disable(this);if(this.selected)this.selected=!1,this.select(!0)},setSelection:function(a){if(this.selection==a)return!1;var c=this.selection;b(this,q,function(b){if(b.contextSelection==c)b.selected&&c&&c.remove([b]),b.contextSelection=
a});this.selection=a;return!0},hasOwnSelection:function(){return!!this.selection},select:function(a){var b=this.selected,c=this.contextSelection;if(c)a?b?c.remove([this]):c.add([this]):this.selectable&&c.set([this]);else if(!b&&this.selectable&&!this.isDisabled())this.selected=!0,this.event_select(this);return this.selected!=b},unselect:function(){var a=this.selected;if(a){var b=this.contextSelection;b?b.remove([this]):(this.selected=!1,this.event_unselect(this))}return this.selected!=a},enable:function(){if(this.disabled)this.disabled=
!1,this.event_enable(this)},disable:function(){if(!this.disabled)this.disabled=!0,this.event_disable(this)},isDisabled:function(){return this.disabled||this.document&&this.document.disabled||!!r.findAncestor(this,x("disabled"))},match:function(a){if("function"!=typeof a)if(this.matched){if(this.underMatch_)this.underMatch_(this,!0),this.underMatch_=null}else this.matched=!0,this.event_match(this);else if(a(this)){if(this.underMatch_=a,!this.matched)this.matched=!0,this.event_match(this)}else if(this.underMatch_=
null,this.matched)this.matched=!1,this.event_unmatch(this)},setMatchFunction:function(){},destroy:function(){this.hasOwnSelection()&&(this.selection.destroy(),delete this.selection);this.unselect();h.prototype.destroy.call(this)}}),F=n(y,o,{}),G=n(h,o,{event_childNodesModified:function(a,b){c.childNodesModified.call(this,a,b);this.nullGroup.nextSibling=this.firstChild;if(b.inserted&&this.dataSource&&this.nullGroup.first)for(var d=this.owner,e=Array.from(this.nullGroup.nodes),f=e.length;0<f--;)d.insertBefore(e[f],
e[f].nextSibling)},event_ownerChanged:function(a,b){b&&b.localGrouping===this&&b.setLocalGrouping(null,!0);this.owner&&this.owner.localGrouping!==this&&this.owner.setLocalGrouping(this);c.ownerChanged.call(this,a,b);!this.owner&&this.autoDestroyWithNoOwner&&this.destroy()},map_:null,autoDestroyWithNoOwner:!0,autoDestroyEmptyGroups:!0,titleGetter:x("data.title"),groupGetter:Function.$undef,childClass:l,childFactory:function(b){return new this.childClass(a(b,{titleGetter:this.titleGetter,autoDestroyIfEmpty:this.dataSource?
!1:this.autoDestroyEmptyGroups}))},init:function(a){this.map_={};this.nullGroup=new l({autoDestroyIfEmpty:!1});h.prototype.init.call(this,a)},getGroupNode:function(a){var a=this.groupGetter(a),b=a instanceof t,c=this.map_[b?a.eventObjectId:a];!c&&!this.dataSource&&(c=this.appendChild(b?{delegate:a}:{data:{id:a,title:a}}));return c||this.nullGroup},insertBefore:function(a,b){a=o.insertBefore.call(this,a,b);if(!1=="groupId_"in a)a.groupId_=a.delegate?a.delegate.eventObjectId:a.data.id,this.map_[a.groupId_]=
a;if(a.first){var c=this.owner,d=c.childNodes,e=a.first,f=a.last,g,h,i;for(g=a;(g=g.previousSibling)&&!(i=g.last););if(!i)i=this.nullGroup.last;for(g=a;(g=g.nextSibling)&&!(h=g.first););if(e.previousSibling!==i||f.nextSibling!==h){if(e.previousSibling)e.previousSibling.nextSibling=f.nextSibling;if(f.nextSibling)f.nextSibling.previousSibling=e.previousSibling;g=d.splice(d.indexOf(e),a.nodes.length);var j=d.indexOf(h);g.unshift(-1!=j?j:d.length,0);d.splice.apply(d,g);e.previousSibling=i;f.nextSibling=
h;if(i)i.nextSibling=e;if(h)h.previousSibling=f;c.firstChild=d[0];c.lastChild=d[d.length-1]}}return a},removeChild:function(a){o.removeChild.call(this,a);delete this.map_[a.groupId_];return a},clear:function(){o.clear.call(this);this.map_={}},destroy:function(){this.setOwner();h.prototype.destroy.call(this);this.map_=null}});h.prototype.localGroupingClass=G;var i=n(C,{autoDestroy:!0,sourceNode:null,listen:{sourceNode:{childNodesModified:function(a,b){var c=this.memberMap_,d={},e=0,f=0,g=b.inserted,
h=b.deleted;if(g&&g.length)for(d.inserted=g;a=g[e];)c[a.eventObjectId]=a,e++;if(h&&h.length)for(d.deleted=h;a=h[f];)delete c[a.eventObjectId],f++;(e||f)&&this.event_datasetChanged(this,d)},destroy:function(){this.autoDestroy?this.destroy():this.setSourceNode()}}},event_sourceNodeChanged:i("sourceNodeChanged")&&function(a,b){c.sourceNodeChanged.call(this,a,b);!this.sourceNode&&this.autoDestroy&&this.destroy()},extendConstructor_:!1,init:function(a,b){C.prototype.init.call(this,b);a&&this.setSourceNode(a)},
setSourceNode:function(a){!1==a instanceof h&&(a=null);if(a!==this.sourceNode){var b=this.sourceNode;b&&(b.removeHandler(this.listen.sourceNode,this),this.listen.sourceNode.childNodesModified.call(this,b,{deleted:b.childNodes}));a&&(a.addHandler(this.listen.sourceNode,this),this.listen.sourceNode.childNodesModified.call(this,a,{inserted:a.childNodes}));this.sourceNode=a;this.event_sourceNodeChanged(this,b)}},destroy:function(){this.setSourceNode();C.prototype.destroy.call(this)}}),J=n(B,{multiple:!1,
event_datasetChanged:function(a,b){B.prototype.event_datasetChanged.call(this,a,b);if(b.inserted)for(var c=0,d;d=b.inserted[c];c++)if(!d.selected)d.selected=!0,d.event_select();if(b.deleted)for(c=0;d=b.deleted[c];c++)if(d.selected)d.selected=!1,d.event_unselect()},add:function(a){if(!this.multiple){if(this.itemCount)return this.set(a);a.splice(1)}for(var b=[],c=0,d;d=a[c];c++)d.contextSelection==this&&d.selectable&&b.push(d);return B.prototype.add.call(this,b)},set:function(a){for(var b=[],c=0,d;d=
a[c];c++)d.contextSelection==this&&d.selectable&&b.push(d);this.multiple||a.splice(1);return B.prototype.set.call(this,b)}});j.namespace("basis.dom.wrapper",u).extend({AbstractNode:h,InteractiveNode:y,Node:F,GroupingNode:G,PartitionNode:l,simpleTemplate:u,ChildNodesDataset:i,Selection:J})})(basis);
(function(j,m){function v(a,b){return D(b,!0).getRule(a,!0)}function w(a,b){var c=a.match(/^([^{]+)\{(.*)\}\s*$/);if(c){for(var d=c[1].trim().split(/\s*,\s*/),e=0;e<d.length;e++)this.addRule(d[e],c[2]||null,b++);return b-1}}function s(a,b){var c=q.createElement(!a?'STYLE[type="text/css"]':'LINK[type="text/css"][rel="{alt}stylesheet"][href={url}]'.format({alt:b?"alternate ":"",url:a.quote('"')}));q.tag(null,"HEAD")[0].appendChild(c);c=c.sheet||c.styleSheet;try{if(!c.cssRules)c.cssRules=c.rules}catch(d){}if(!c.insertRule)c.insertRule=
w;if(!c.deleteRule)c.deleteRule=c.removeRule;return c}function D(a,b){a||(a="DefaultGenericStyleSheet");c[a]||b&&(c[a]=new g(s()));return c[a]}function E(a,b,c,e){for(var e=e||{},b=b.qw(),g=0,h;h=b[g];g++)if("undefined"!=typeof f.style[h]){c&&(j.platformFeature["css-"+a]=h);d[a]={key:h,getter:e[h]};break}}function u(a,b){var c=d[a];if(a=c?c.key:a.replace(/^-ms-/,"ms-").camelize())return{key:a,value:c&&c.getter?c.getter(b):b}}function n(a,b,c){if("function"==typeof a.setProperty)return a.setProperty(b,
c);if(b=u(b,c))return a.style[b.key]=b.value}function r(a,b){for(var c in b)n(a,c,b[c]);return a}function i(a,b){return n(a,"display","string"==typeof b?b:b?"":"none")}function y(a,b){return n(a,"visibility",b?"":"hidden")}function t(a){return F[a]||(F[a]=RegExp("\\s*\\b"+a+"\\b"))}function C(a,b){var c=(b?"g":"s")+a;return J[c]||(J[c]=RegExp("\\s*\\b"+a+".*\\b"))}var B=m.document,q=j.dom,z=j.dom.event,x=j.Class,a=/\s*!important/i,b=1,c={},d={},f=q.createElement("DIV");E("opacity","opacity MozOpacity KhtmlOpacity filter",
!0,{fitler:function(a){return"alpha(opacity:"+parseInt(100*a)+")"}});E("border-radius","borderRadius MozBorderRadius WebkitBorderRadius",!0);E("float","cssFloat styleFloat");var g=x(null,{styleSheet:null,rules:null,init:function(a){this.styleSheet=a;this.rules=[];this.map_={}},getRule:function(a,b){if(!this.map_[a]&&b){for(var c=this.styleSheet,d=this.rules.length,f=c.insertRule(a+"{}",d),g=d;g<=f;g++)this.rules.push(new e(c.cssRules[g]));this.map_[a]=d!=f?new h(this.rules.splice(d)):this.rules[d]}return this.map_[a]},
deleteRule:function(a){var b=this.map_[a];if(b){for(var b=b.rules||[b],c=0;c<b.length;c++){var d=this.rules.indexOf(b[c]);this.stylesheet.deleteRule(d);this.rules.splice(d,1)}delete this.map_[a]}},destroy:function(){delete this.rules}}),e=x(null,{rule:null,selector:"",init:function(a){if(a)this.rule=a,this.selector=a.selectorText},setProperty:function(b,c){var d,e=!!a.test(c),f=this.rule.style;if(e||f.getPropertyPriority&&"important"==f.getPropertyPriority(b)){if(c=c.replace(a,""),d=u(b,c)){var g=
d.key;f.setProperty?(e||f.removeProperty(g),f.setProperty(g,d.value,e?"important":"")):f.cssText=f.cssText.replace(RegExp(f[g]?g+"\\s*:\\s*"+f[g]+"(\\s*!important)?\\s*;?":"^","i"),g+": "+d.value+(e?" !important":"")+";")}}else n(this.rule,b,c)},setStyle:function(a){Object.iterate(a,this.setProperty,this)},clear:function(){this.rule.style.cssText=""},destroy:function(){delete this.rule}}),h=x(null,{rules:null,init:function(a){this.rules=a},destroy:function(){delete this.rules}});["setProperty","setStyle",
"clear"].forEach(function(a){h.prototype[a]=function(){for(var b,c=0;b=this.rules[c];c++)b[a].apply(b,arguments)}});var l={};["em","ex","px","%"].forEach(function(a){l["%"==a?"percent":a]=function(b){return 0==b||isNaN(b)?"0":b+a}});var o,F={},G=x(null,{init:function(a){this.element=a},toString:function(){return this.element.className},set:function(a){this.clear();a.qw().forEach(this.add,this)},replace:function(a,b,c){c=c||"";"undefined"!=typeof a&&this.remove(c+a);"undefined"!=typeof b&&this.add(c+
b)},bool:function(a,b){b?this.add(a):this.remove(a)},clear:function(){this.element.className=""},contains:function(a){return!!this.element.className.match(t(a))},item:function(a){return this.element.className.qw()[a]},add:function(a){this.element.className.match(t(a))||(this.element.className+=" "+a)},remove:function(a){var b=this.element.className,a=b.replace(t(a),"");if(a!=b)this.element.className=a},toggle:function(a){var b=this.contains(a);b?this.remove(a):this.add(a);return!b}}),J={},k=x(null,
{delim:"-",init:function(a,b){this.classList=b;this.prefix=a+this.delim},add:function(a){this.classList.add(this.prefix+a)},remove:function(a){this.classList.remove(this.prefix+a)},items:function(){var a=this.classList.toString();if(a)return a.toString().match(C(this.prefix,!0))},set:function(a){var b=this.items(),a="undefined"!=typeof a?this.prefix+a:"",c=this.classList;if(b)if(1==b.length){if(b[0]===a)return;c.remove(b[0])}else this.clear();a&&c.add(a)},clear:function(){this.items().forEach(this.classList.remove,
this.classList)}});m.DOMTokenList&&B.documentElement.classList?(x=G.prototype,Object.extend(m.DOMTokenList.prototype,{set:x.set,replace:x.replace,bool:x.bool,clear:function(){for(var a=this.length;0<a--;)this.remove(this[a])},setPrefixToken:x.setPrefixToken}),o=function(a){return("string"==typeof a?q.get(a):a).classList}):o=function(a){return new G("string"==typeof a?q.get(a):a)};z.onLoad(function(){o(B.body).bool("opacity-not-support",!j.platformFeature["css-opacity"])});q.extend({setStyleProperty:n,
setStyle:r,display:i,show:function(a){return i(a,1)},hide:function(a){return i(a)},visibility:y,visible:function(a){return y(a,1)},invisible:function(a){return y(a)}});return j.namespace("basis.cssom").extend({setStyleProperty:n,setStyle:r,classList:function(a,b){return b?new k(b,o(a)):o(a)},uniqueRule:function(a){var c="genericRule-"+b++;a&&o(a).add(c);a=v("."+c);a.token=c;return a},cssRule:v,getStyleSheet:D,addStyleSheet:s,CssStyleSheetWrapper:g,CssRuleWrapper:e,CssRuleWrapperSet:h}).extend(l)})(basis,
this);
(function(j){function m(a){g[a]=g[a]||0;return a+g[a]++}function v(){var a=Array.from(arguments),b=a.pop();"function"!=typeof b&&console.warn("Last argument for calculate field constructor must be a function");for(var c=[],d=[],e=0,f;e<a.length;e++)f=a[e].quote('"'),c.push(f+" in delta"),d.push("data["+f+"]");b=(new Function("calc","return function(delta, data, oldValue){"+(c.length?"if ("+c.join(" || ")+")":"")+"return calc("+d.join(", ")+");"+(c.length?"return oldValue;":"")+"}"))(b);b.args=a;b.isCalcField=
!0;return b}function w(){return v.apply(null,Array.from(arguments).concat(function(){for(var a=[],b=arguments.length;0<b--;){if(null==arguments[b])return null;a.push(arguments[b])}return a.join("-")}))}var s=j.Class,D=j.Cleaner,E=Object.extend,u=Function.$self,n=Function.getter,r=j.data,i=j.EventObject,y=r.Dataset,t=r.Collection,C=r.Grouping,B=r.DataObject,q=r.STATE,z={},x={string:1,number:1},a=[],b=function(a){return isNaN(a)?null:Number(a)},c=function(a){return isNaN(a)?null:Number(a)},d=function(a){return isNaN(a)?
null:parseInt(a)},f=function(a){return null==a?null:""+a},g={},e=j.Class(null,{init:function(a){var b=this.index={};this.normalize=a;this.valueWrapper=function(c,d){var e=a(c,d);return e!==d&&b[e]?d:e};this.calcWrapper=function(c,d){var e=a(c,d);if(e!==d&&b[e])throw"Duplicate value for index "+d+" => "+c;return e};D.add(this)},get:function(a,b){var c=this.index[a];if(c&&(!b||c instanceof b))return c},add:function(a,b){var c=this.index[a];if(b&&(!c||c===b))return this.index[a]=b,!0},remove:function(a,
b){if(this.index[a]===b)return delete this.index[a],!0},destroy:function(){this.index=null}}),r=function(a,b){return function(c){return a.prototype[b].call(this,c&&c.map(this.wrapper))}},h=function(a,b){return function(c){if(!this.name)this.name=m(b);a.prototype.init.call(this,c)}},l=function(a){return function(b,c){y.setAccumulateState(!0);b=(b||[]).map(this.wrapper);y.setAccumulateState(!1);return a.prototype.sync.call(this,b,c)}},o=s(y,{wrapper:Function.$self,init:h(y,"EntitySet"),sync:l(y),set:r(y,
"set"),add:r(y,"add"),remove:r(y,"remove"),destroy:function(){y.prototype.destroy.call(this);delete this.wrapper}}),F=s(o,{set:Function.$false,add:Function.$false,remove:Function.$false,clear:Function.$false}),G=s(t,{init:h(t,"EntityCollection"),sync:l(t)});G.sourceHandler=t.sourceHandler;var J=s(C,{subsetClass:F,init:h(C,"EntityGrouping"),sync:l(C),getSubset:function(a,b){var c=C.prototype.getSubset.call(this,a,b);if(c)c.wrapper=this.wrapper;return c}}),k=function(a){if(this instanceof k){var b=
new p(a||u);return function(a,c){return null!=a?(c instanceof o||(c=b.createEntitySet()),c.set(a instanceof y?a.getItems():Array.from(a)),c):null}}};k.className="basis.entity.EntitySetWrapper";var p=s(null,{init:function(a){this.wrapper=a},createEntitySet:function(){return new o({wrapper:this.wrapper,name:"Set of "+((this.wrapper.entityType||this.wrapper).name||"").quote("{")})}}),A=function(a){if(this instanceof A){var b=function(a,b){if(null!=a){if(a===b||a.entityType===c)return a;var g,h=c.idField;
if(x[typeof a]){if(!h)return;g=a;a={};a[h]=g}else if(c.compositeKey)g=c.compositeKey(a,a);else if(h)g=a[h];else if(f&&(b=c.singleton,!b))return c.singleton=new e(a);null!=g&&d&&(b=d.get(g,c.entityClass));b&&b.entityType===c?b.update(a):b=new e(a);return b}return c.singleton},c=new P(a||{},b),d=c.index__,e=c.entityClass,f=c.isSingleton;E(b,{toString:function(){return this.typeName+"()"},entityType:c,type:b,typeName:c.name,index:d,reader:function(a){return c.reader(a)},get:function(a){return c.get(a)},
addField:function(a,b){c.addField(a,b)},all:c.all,createCollection:function(a,d,e){var f=c.collection_[a];return!f&&d?c.collection_[a]=new G({wrapper:b,source:e||c.all,rule:d}):f},getCollection:function(a){return c.collection_[a]},createGrouping:function(a,d,e){var f=c.grouping_[a];return!f&&d?c.grouping_[a]=new J({wrapper:b,source:e||c.all,rule:d}):f},getGrouping:function(a){return c.grouping_[a]},getSlot:function(a,b){return c.getSlot(a,b)}});return b}};A.className="basis.entity.EntityTypeWrapper";
var K=n("singleton"),L={};s(B,{});var P=s(null,{name:"UntitledEntityType",defaults:null,fields:null,extensible:!1,index__:null,slot_:null,init:function(b,c){this.name=b.name||m(this.name);this.index__=b.index;this.idFields={};a.push(this);this.isSingleton=b.isSingleton;this.wrapper=c;this.all=new F(Object.extend(b.all||{},{wrapper:c}));this.slot_={};if(b.extensible)this.extensible=!0;this.fields={};this.defaults={};this.aliases={};this.getters={};Object.iterate(b.fields,this.addField,this);b.constrains&&
b.constrains.forEach(function(a){this.addCalcField(null,a)},this);if(this.isSingleton)this.get=K;b.aliases&&Object.iterate(b.aliases,this.addAlias,this);this.collection_={};if(b.collections)for(var d in b.collections)this.collection_[d]=new G({name:d,wrapper:c,source:this.all,rule:b.collections[d]||Function.$true});this.grouping_={};if(b.groupings)for(d in b.groupings)this.grouping_[d]=new J({name:d,wrapper:c,source:this.all,rule:b.groupings[d]||Function.$true});this.entityClass=O(this,this.all,this.index__,
this.slot_,this.fields,this.defaults,this.getters).extend({entityType:this,type:c,typeName:this.name,getId:function(){return this.__id__}})},reader:function(a){var b={};if(x[typeof a])return this.idField?(b[this.idField]=a,b):null;if(!a||null==a)return null;for(var c in a){var d=c in this.aliases?this.aliases[c]:"";d&&d in this.fields&&(b[d]=this.fields[d].reader?this.fields[d].reader(a[c]):a[c])}return b},addAlias:function(a,b){b in this.fields&&!1==a in this.aliases&&(this.aliases[a]=b)},addField:function(a,
g){if(!this.all.itemCount){this.aliases[a]=a;"function"==typeof g&&(g={type:g});if("type"in g&&"function"!=typeof g.type)g.type=u;var h=g.type||u;if([b,c,d,f].has(h))g.id=!0;if(g.id){if(!this.index__)this.index__=new e(String);this.idFields[a]=!0;this.idField||this.compositeKey?(this.idField=null,this.compositeKey=w.apply(null,Object.keys(this.idFields))):this.idField=a}g.calc?this.addCalcField(a,g.calc,void 0):this.fields[a]=h;this.defaults[a]="defValue"in g?g.defValue:h();this.getters["get_"+a]=
function(){return this.data[a]};L[a]||(L[a]={destroy:function(){this.set(a,null)}})}},addCalcField:function(a,b,c){if(!a||!this.fields[a]){if(!this.calcs)this.calcs=[];for(var d={args:b.args,wrapper:!c?b:function(a,d,e){return c(b(a,d,e))}},e=this.calcs.length,f=0,g=0;g<this.calcs.length;g++)b.args.has(this.calcs[g].key)&&(f=g+1);if(a){d.key=a;for(g=0;g<this.calcs.length;g++)if(this.calcs[g].args.has(a)){e=g;break}if(f>e)return;if(this.idField&&a==this.idField)this.compositeKey=b;this.fields[a]=function(a,
b){"undefined"!=typeof console&&console.log("Calculate fields are readonly");return b}}else e=f;this.calcs.splice(Math.min(e,f),0,d)}},get:function(a){a=this.getId(a);if(null!=a)return this.index__.get(a,this.entityClass)},getId:function(a){if((this.idField||this.compositeKey)&&null!=a){if(x[typeof a])return a;if(a&&a.entityType===this)return a.__id__;if(a instanceof B)a=a.data;return this.compositeKey?this.compositeKey(a,a):a[this.idField]}},getSlot:function(a){var b=this.getId(a);if(null!=b){var c=
this.slot_[b];c||(x[typeof a]&&(c={},this.idField&&!this.compositeKey&&(c[this.idField]=a),a=c),c=this.slot_[b]=new B({delegate:this.get(b),data:a}));return c}}}),N=s(B,{init:i.prototype.init,event_rollbackUpdate:i.createEvent("rollbackUpdate")}),O=function(a,b,c,d,e,f,g){function h(b,c,d){var e=!1,f=a.calcs,g=b.__id__,i=b.data;try{if(f)for(var l=0,m;m=f[l++];){var n=m.key;if(n){var o=i[n];i[n]=m.wrapper(c,i,i[n]);i[n]!==o&&(c[n]=o,e=!0)}else m.wrapper(c,i)}if(a.compositeKey)b.__id__=a.compositeKey(c,
i,b.__id__);else if(k&&k in c)b.__id__=i[k];b.__id__!==g&&a.index__.calcWrapper(b.__id__)}catch(q){b.__id__=g;for(var p in c)b.data[p]=c[p];if(d)for(p in d)if(!b.modified)b.modified=d;e=!1}b.__id__!==g&&j(b,g,b.__id__);return e}function j(a,b,e){null!=b&&(c.remove(b,a),d[b]&&d[b].setDelegate());null!=e&&(c.add(e,a),d[e]&&d[e].setDelegate(a))}var k=a.idField;return s(N,g,{canHaveDelegate:!1,modified:null,isTarget:!0,extendConstructor_:!1,init:function(a){N.prototype.init.call(this);this.fieldHandlers_=
{};this.data={};this.root=this;this.target=this;var c,d={},g;for(g in e)g in a?(d[g]=f[g],c=e[g](a[g])):c=f[g],c&&c!==this&&c instanceof i&&c.addHandler(L[g],this)&&(this.fieldHandlers_[g]=!0),this.data[g]=c;h(this,d);b.event_datasetChanged(b,{inserted:[this]})},toString:function(){return"[object "+this.constructor.className+"("+this.entityType.name+")]"},get:function(a){return this.data[a]},set:function(b,c,d,f){var g=e[b];if(!g){if(!a.extensible)return;g=u}var j,l=this.modified,c=g(c,this.data[b]),
g=this.data[b];if(c!==g&&(!c||!g||c.constructor!==Date||g.constructor!==Date||+c!==+g))a:{j={};if(b!=k)if(d){if(!l)this.modified=l={};if(!1===b in l)j.rollback={key:b,value:void 0},l[b]=g;else if(l[b]===c&&(j.rollback={key:b,value:c},delete l[b],!Object.keys(l).length))this.modified=null}else if(l&&b in l)if(l[b]!==c){j.rollback={key:b,value:l[b]};l[b]=c;break a}else return!1;this.data[b]=c;this.fieldHandlers_[b]&&(g.removeHandler(L[b],this),this.fieldHandlers_[b]=!1);c&&c!==this&&c instanceof i&&
c.addHandler(L[b],this)&&(this.fieldHandlers_[b]=!0);j.key=b;j.value=g;j.delta={};j.delta[b]=g}else if(!d&&l&&b in l&&(j={rollback:{key:b,value:l[b]}},delete l[b],!Object.keys(l).length))this.modified=null;if(!f&&j){var d=j.key,b=j.delta||{},m;if(j.rollback)m={},m[j.rollback.key]=j.rollback.value;h(this,b,m)&&(d=!0);if(d)this.event_update(this,b),j.delta=b;m&&this.event_rollbackUpdate(this,m)}return j||!1},update:function(a,b){if(a){var c,d={},e,f={},g,i;for(i in a)if(g=this.set(i,a[i],b,!0)){if(g.key)c=
!0,d[g.key]=g.value;if(g.rollback)e=!0,f[g.rollback.key]=g.rollback.value}h(this,d,f)&&(c=!0);c&&this.event_update(this,d);e&&this.event_rollbackUpdate(this,f)}return c?d:!1},reset:function(){this.update(f)},clear:function(){var a={},b;for(b in this.data)a[b]=void 0;return this.update(a)},commit:function(a){if(this.modified){var b=this.modified;this.modified=null}this.update(a);b&&this.event_rollbackUpdate(this,b)},rollback:function(){if(this.state!=q.PROCESSING){if(this.modified){var a=this.modified;
this.modified=null;this.update(a);this.event_rollbackUpdate(this,a)}this.setState(q.READY)}},destroy:function(){for(var a in this.fieldHandlers_)this.data[a].removeHandler(L[a],this);this.fieldHandlers_=z;this.__id__&&j(this,this.__id__,null);B.prototype.destroy.call(this);b.event_datasetChanged(b,{deleted:[this]});this.data=z;this.modified=null}})};j.namespace("basis.entity").extend({isEntity:function(a){return a&&a instanceof O},NumericId:b,NumberId:c,IntId:d,StringId:f,Index:e,CalculateField:v,
EntityType:A,Entity:O,BaseEntity:N,EntitySetType:k,EntitySet:o,ReadOnlyEntitySet:F,Collection:G,Grouping:J})})(basis);
